import{createHash}from'node:crypto'
import{existsSync,readFileSync}from'node:fs'
import{describe,expect,it}from'vitest'

const migration=readFileSync('supabase/migrations/202609040002_canonical_davi_sales_archive.sql','utf8')
const metadata=JSON.parse(readFileSync('scripts/manifests/canonical-davi-sales-archive-20260904.json','utf8'))
const privateManifest=metadata.private_payload as string
type ManifestRow={sale_id:string;organization_id:string;expected_updated_at:string;amount:string;client_id:string;perfume_id:string;sale_date:string;sale_type:string;volume_ml:string;payment_status:string}
const canonical=(rows:ManifestRow[])=>rows.slice().sort((a,b)=>a.sale_id.localeCompare(b.sale_id)).map(row=>[row.sale_id,row.organization_id,row.expected_updated_at,row.amount,row.client_id,row.perfume_id,row.sale_date,row.sale_type,row.volume_ml,row.payment_status].join('|')).join('\n')
const sha=(value:string)=>createHash('sha256').update(value).digest('hex')
const stripComments=(sql:string)=>sql.replace(/--.*$/gm,'').replace(/\/\*[\s\S]*?\*\//g,'')
const code=stripComments(migration)
const apply=code.slice(code.indexOf('create or replace function public.apply_approved_canonical_davi_sales_archive'),code.indexOf('create or replace function public.rollback_approved_canonical_davi_sales_archive'))
const rollback=code.slice(code.indexOf('create or replace function public.rollback_approved_canonical_davi_sales_archive'))
const trigger=code.slice(code.indexOf('create or replace function public.sync_sale_inventory_allocation'),code.indexOf('create or replace function public.apply_approved_canonical_davi_sales_archive'))

type Sale={id:string;organization_id:string;updated_at:string;deleted_at:string|null;client_id:string;perfume_id:string;sale_date:string;sale_type:string;volume_ml:string;amount:string;payment_status:string;shipment?:boolean;allocation?:boolean}
type State={sales:Sale[];inventory_items:unknown[];inventory_allocations:unknown[];inventory_movements:unknown[];clients:unknown[];perfumes:unknown[];audits:{kind:string}[];completed:boolean;rolledBack:boolean}
const fixture=(count=333):{state:State;manifest:ManifestRow[]}=>{
 const manifest=Array.from({length:count},(_,index)=>({sale_id:`00000000-0000-4000-8000-${String(index).padStart(12,'0')}`,organization_id:metadata.organization_id,expected_updated_at:'2026-09-04T18:00:00.000+00:00',amount:'100.00',client_id:'10000000-0000-4000-8000-000000000001',perfume_id:'20000000-0000-4000-8000-000000000001',sale_date:'2026-08-01',sale_type:'SPLIT',volume_ml:'3.000',payment_status:'paid'}))
 const sales=manifest.map(row=>({id:row.sale_id,organization_id:row.organization_id,updated_at:row.expected_updated_at,deleted_at:null,client_id:row.client_id,perfume_id:row.perfume_id,sale_date:row.sale_date,sale_type:row.sale_type,volume_ml:row.volume_ml,amount:row.amount,payment_status:row.payment_status}))
 return{manifest,state:{sales,inventory_items:[{id:'item',available_ml:'100.000'}],inventory_allocations:[],inventory_movements:[],clients:[{id:'client'}],perfumes:[{id:'perfume'}],audits:[],completed:false,rolledBack:false}}
}
const snapshot=(state:State)=>JSON.stringify(state)
const applyModel=(state:State,manifest:ManifestRow[],hash=sha(canonical(manifest)))=>{
 if(state.completed)return{idempotent:true,archived:0}
 if(hash!==sha(canonical(manifest)))throw new Error('manifest_hash')
 for(const row of manifest){const sale=state.sales.find(item=>item.id===row.sale_id);if(!sale)throw new Error('missing');if(sale.organization_id!==row.organization_id)throw new Error('tenant');if(sale.deleted_at)throw new Error('archived');if(sale.updated_at!==row.expected_updated_at)throw new Error('stale');if(sale.client_id!==row.client_id||sale.perfume_id!==row.perfume_id||sale.sale_date!==row.sale_date||sale.sale_type!==row.sale_type||sale.volume_ml!==row.volume_ml||sale.amount!==row.amount||sale.payment_status!==row.payment_status)throw new Error('identity');if(sale.allocation)throw new Error('allocation');if(sale.shipment)throw new Error('shipment')}
 for(const row of manifest){const sale=state.sales.find(item=>item.id===row.sale_id)!;sale.deleted_at='2026-09-04T19:00:00.000Z';sale.updated_at='2026-09-04T19:00:00.000Z';state.audits.push({kind:'sale'})}state.completed=true;state.audits.push({kind:'batch'});return{idempotent:false,archived:manifest.length}
}
const rollbackModel=(state:State)=>{if(state.rolledBack)return{idempotent:true,restored:0};for(const sale of state.sales)if(sale.updated_at!=='2026-09-04T19:00:00.000Z'||sale.deleted_at!=='2026-09-04T19:00:00.000Z')throw new Error('changed');for(const sale of state.sales){sale.deleted_at=null;sale.updated_at='2026-09-04T20:00:00.000Z';state.audits.push({kind:'rollback_sale'})}state.rolledBack=true;state.audits.push({kind:'rollback_batch'});return{idempotent:false,restored:state.sales.length}}

describe('canonical Davi sales archive migration',()=>{
 it('fixa fonte, lote, motivo, 333 vendas e R$ 75.793,00',()=>{expect(metadata).toMatchObject({sale_count:333,amount:'75793.00',reason:'absent_from_canonical_davi_snapshot'});for(const value of[metadata.batch_id,metadata.organization_id,metadata.source_sha256,metadata.manifest_sha256,metadata.reason])expect(migration).toContain(value);expect(migration).toContain('approved_count constant integer := 333');expect(migration).toContain('approved_amount constant numeric := 75793.00')})
 it.skipIf(!existsSync(privateManifest))('o manifesto real tem exatamente 333 vendas, R$ 75.793,00 e os hashes aprovados',()=>{const bytes=readFileSync(privateManifest);const rows=JSON.parse(bytes.toString('utf8'))as ManifestRow[];expect(rows).toHaveLength(333);expect(new Set(rows.map(row=>row.sale_id)).size).toBe(333);expect(rows.reduce((sum,row)=>sum+Math.round(Number(row.amount)*100),0)).toBe(7_579_300);expect(sha(bytes.toString('utf8'))).toBe(metadata.manifest_sha256);expect(sha(canonical(rows))).toBe(metadata.payload_sha256)})
 it('pré-valida lote inteiro com FOR UPDATE, tenant, estado, timestamp e identidade',()=>{for(const value of['for update','canonical_archive_wrong_tenant','canonical_archive_sale_already_archived','canonical_archive_stale_sale','canonical_archive_commercial_identity_mismatch'])expect(apply.toLowerCase()).toContain(value.toLowerCase());expect(apply.indexOf('for item in select value')).toBeLessThan(apply.indexOf("perform set_config('ruah.canonical_davi_archive_batch'"))})
 it('recusa alocação, preparação, envio, solicitação e movimento',()=>{for(const value of['canonical_archive_active_allocation','canonical_archive_active_preparation','canonical_archive_incompatible_shipment','canonical_archive_customer_shipment_request','canonical_archive_inventory_movement'])expect(apply).toContain(value)})
 it('autentica forma, contagem, valor, pagamento e SHA-256 do manifesto aprovado',()=>{for(const value of['jsonb_object_keys(manifest_row.value)','as manifest_row(value)','canonical_archive_manifest_count_mismatch','canonical_archive_duplicate_sale','canonical_archive_manifest_payload_mismatch','canonical_archive_manifest_amount_mismatch',"public.ai_sha256_hex(string_agg(concat_ws('|',","before_row.payment_status::text is distinct from item->>'payment_status'"])expect(apply).toContain(value);expect(apply).not.toContain('jsonb_object_length');expect(apply).not.toMatch(/->>'sale_id'\|\|/)})
 it('uma divergência após dry-run aborta o lote antes de qualquer alteração',()=>{const{state,manifest}=fixture();state.sales[332].updated_at='changed';const before=snapshot(state);expect(()=>applyModel(state,manifest)).toThrow('stale');expect(snapshot(state)).toBe(before)})
 it('recusa tenant, venda arquivada, alocação, envio e hash incorreto',()=>{for(const kind of['tenant','archived','allocation','shipment','hash']as const){const{state,manifest}=fixture(1);if(kind==='tenant')state.sales[0].organization_id='wrong';if(kind==='archived')state.sales[0].deleted_at='old';if(kind==='allocation')state.sales[0].allocation=true;if(kind==='shipment')state.sales[0].shipment=true;expect(()=>applyModel(state,manifest,kind==='hash'?'wrong':sha(canonical(manifest)))).toThrow()}})
 it('aplica 333 atomicamente, mantém domínios protegidos byte a byte e é idempotente',()=>{const{state,manifest}=fixture();const protectedBefore=JSON.stringify({inventory_items:state.inventory_items,inventory_allocations:state.inventory_allocations,inventory_movements:state.inventory_movements,clients:state.clients,perfumes:state.perfumes,payments:state.sales.map(s=>s.payment_status)});expect(applyModel(state,manifest)).toEqual({idempotent:false,archived:333});expect(state.sales.every(s=>s.deleted_at!==null)).toBe(true);expect(JSON.stringify({inventory_items:state.inventory_items,inventory_allocations:state.inventory_allocations,inventory_movements:state.inventory_movements,clients:state.clients,perfumes:state.perfumes,payments:state.sales.map(s=>s.payment_status)})).toBe(protectedBefore);expect(applyModel(state,manifest)).toEqual({idempotent:true,archived:0});expect(state.audits).toHaveLength(334)})
 it('rollback restaura só deleted_at/updated_at sem estoque e também é idempotente',()=>{const{state,manifest}=fixture();applyModel(state,manifest);const protectedBefore=JSON.stringify({inventory_items:state.inventory_items,inventory_allocations:state.inventory_allocations,inventory_movements:state.inventory_movements,clients:state.clients,perfumes:state.perfumes,payments:state.sales.map(s=>s.payment_status)});expect(rollbackModel(state)).toEqual({idempotent:false,restored:333});expect(state.sales.every(s=>s.deleted_at===null)).toBe(true);expect(JSON.stringify({inventory_items:state.inventory_items,inventory_allocations:state.inventory_allocations,inventory_movements:state.inventory_movements,clients:state.clients,perfumes:state.perfumes,payments:state.sales.map(s=>s.payment_status)})).toBe(protectedBefore);expect(rollbackModel(state)).toEqual({idempotent:true,restored:0})})
 it('rollback após alteração posterior é recusado sem restauração parcial',()=>{const{state,manifest}=fixture();applyModel(state,manifest);state.sales[200].updated_at='later';const before=snapshot(state);expect(()=>rollbackModel(state)).toThrow('changed');expect(snapshot(state)).toBe(before)})
 it('bypass do trigger é local, service_role, batch+hash+sale e só aceita deleted_at/updated_at',()=>{for(const value of["auth.role()='service_role'","current_setting('ruah.canonical_davi_archive_batch',true)","current_setting('ruah.canonical_davi_archive_manifest',true)","current_setting('ruah.canonical_davi_archive_sale_id',true)","to_jsonb(old)-'deleted_at'-'updated_at'","to_jsonb(new)-'deleted_at'-'updated_at'"])expect(trigger).toContain(value);expect(code).not.toMatch(/disable\s+trigger/i)})
 it('apply e rollback não escrevem em estoque, alocações, movimentos, pagamentos, clientes ou perfumes',()=>{for(const block of[apply,rollback]){expect(block).not.toMatch(/update\s+public\.inventory_items/i);expect(block).not.toMatch(/insert\s+into\s+public\.inventory_allocations/i);expect(block).not.toMatch(/update\s+public\.inventory_allocations/i);expect(block).not.toMatch(/insert\s+into\s+public\.inventory_movements/i);expect(block).not.toMatch(/update\s+public\.(clients|perfumes)/i);expect(block).not.toMatch(/payment_status\s*=/i)}expect(apply).toMatch(/update public\.sales set deleted_at=now\(\),updated_at=now\(\)/);expect(rollback).toMatch(/update public\.sales set\s+deleted_at=/)})
 it('RPCs são service_role, auditam por venda+lote e rollback compara o estado completo',()=>{expect(apply).toContain("auth.role() is distinct from 'service_role'");expect(rollback).toContain("auth.role() is distinct from 'service_role'");expect(apply).toContain("'canonical_davi_sale_archived'");expect(apply).toContain("'canonical_davi_sales_archive_completed'");expect(rollback).toContain("to_jsonb(sale_row) is distinct from archive_log.metadata->'after'");expect(rollback).toContain("'canonical_davi_sales_archive_rolled_back'");expect(code).not.toMatch(/delete\s+from\s+public\.sales/i)})
})
