import{describe,expect,it}from'vitest'
import{readFileSync}from'node:fs'

const read=(path:string)=>readFileSync(path,'utf8')
const root=read('src/portal/CustomerPortalRoot.tsx')
const launch=read('supabase/migrations/202608200006_customer_portal_launch_aal1.sql')
const foundation=read('supabase/migrations/202608200001_customer_portal.sql')
const invite=read('supabase/functions/customer-account-invite/index.ts')
const registration=read('supabase/functions/customer-registration-start/index.ts')
const mailer=read('supabase/functions/_shared/customer-invite.ts')
const records=read('src/lib/records.ts')
const clientDetails=read('src/pages/ClientDetailsPage.tsx')

describe('Minha RUAH launch without mandatory MFA',()=>{
  it('keeps administrative e-mail invites on secure generated links delivered by Resend',()=>{expect(invite).toContain("generateLink({ type: 'invite'");expect(invite).toContain('sendInviteEmail');expect(mailer).toContain("fetch('https://api.resend.com/emails'");expect(mailer).toContain("Deno.env.get('RESEND_API_KEY')")})
  it('does not claim delivery without a successful Resend response and provider id',()=>{expect(mailer).toContain('const raw=await response.text()');expect(mailer).toContain("status:'failed',provider:'resend'");expect(mailer).toContain('provider_message_id:result.id');expect(registration).toContain("emailResult.status!=='sent'");expect(invite).toContain("sent_email_at: emailResult.status === 'sent'")})
  it('keeps transport and premium e-mail presentation separated',()=>{expect(mailer).toContain('export function renderCustomerInviteEmail');expect(mailer).toContain('export function renderCustomerInviteText');expect(mailer).toContain('html:renderCustomerInviteEmail(input)');expect(mailer).toContain('text:renderCustomerInviteText(input)');expect(mailer).toContain('CRIAR MINHA SENHA')})
  it('sends exactly the normalized address received from registration without a QA override',()=>{expect(registration).toContain('sendInviteEmail({to:email');expect(mailer).toContain('to:[input.to]');expect(`${registration}\n${mailer}`).not.toContain(['@resend','.dev'].join(''))})
  it('keeps registration in retry state on failure and shows confirmed success only after invite_sent',()=>{const page=root.slice(root.indexOf('function RegistrationPage'),root.indexOf('function RecoveryPage'));expect(page).toContain("result.status!=='invite_sent'");expect(page).toContain('setError(');expect(page).toContain('setSentTo(result.email)');expect(page).toContain('Link enviado para seu e-mail.');expect(page).toContain('REENVIAR LINK EM ${seconds}S');expect(page).not.toContain('finally{setSent')})
  it('returns a structured non-success when the Auth invite user already exists',()=>{expect(registration).toContain("account_already_exists");expect(registration).toContain('alreadyExists?409:502');expect(registration).not.toContain('if(error||!generated.user||!generated.properties?.action_link)return json(generic,200')})
  it('keeps the administrative modal open on provider failure and confirms only sent channels',()=>{expect(clientDetails).toContain("result.channels.email.status!=='sent'");expect(clientDetails).toContain('setInviteError(');expect(clientDetails).toContain('setInviteSuccess(true)');expect(clientDetails).toContain("inviteError?'Tentar novamente':'Enviar convite'");expect(clientDetails).not.toContain('setInviteOpen(false);await reload()')})
  it('propagates provider_message_id through both Edge Function results',()=>{expect(registration).toContain('provider_message_id:emailResult.provider_message_id');expect(invite).toContain('channels: { email: emailResult');expect(records).toContain('provider_message_id?:string')})
  it('keeps invitation activation, password creation, login and recovery without forcing MFA',()=>{expect(root).toContain('function ActivateCompletePage');expect(root).toContain('updateUser({ password })');expect(root).toContain("setStep('success')");expect(root).toContain("auth.signOut().then(()=>go('/minha-ruah/entrar'))");expect(root).toContain('signInWithPassword');expect(root).toContain('resetPasswordForEmail')})
  it('keeps public registration generic and linked to verified auth identity',()=>{expect(registration).toContain("generateLink({type:'invite'");expect(registration).toContain("upsert({organization_id:org,auth_user_id:generated.user.id");expect(registration).toContain('sendInviteEmail');expect(registration).not.toMatch(/body\.client_id/)})
  it('allows AAL1 launch only through an authenticated active client account',()=>{expect(launch).toContain('auth.uid() is not null');expect(launch).toContain('ca.auth_user_id=auth.uid()');expect(launch).toContain("ca.status='active'")})
  it('keeps every private RPC scoped by current_customer_client without frontend client ids',()=>{for(const name of ['customer_custody','customer_shipment_requests_list','customer_purchase_history','customer_delivery_history','customer_profile','customer_support_tickets_list']){const start=foundation.indexOf(`create or replace function public.${name}(`),body=foundation.slice(start,foundation.indexOf('$$;',start));expect(start,name).toBeGreaterThan(-1);expect(body,name).toContain('current_customer_client()');expect(body,name).not.toMatch(/p_client_id/)}})
  it('keeps unresolved and review identities without a private active link',()=>{const conflict=launch.slice(launch.indexOf('if cardinality(email_ids)'),launch.indexOf("target:=coalesce"));expect(conflict).toContain("status='review_required'");expect(conflict).not.toContain('insert into public.client_accounts')})
  it('keeps MFA implementation and route available while launch flag defaults off',()=>{expect(root).toContain("path==='/minha-ruah/mfa'");expect(root).toContain('function MfaPage');expect(root).toContain('mfa.enroll');expect(root).toContain('mfa.challenge');expect(root).toContain('mfa.verify');expect(read('.env.example')).toContain('VITE_CUSTOMER_MFA_REQUIRED=false')})
})
