import{describe,expect,it}from'vitest'
import{readFileSync}from'node:fs'
const sql=readFileSync('supabase/migrations/202608230010_inventory_station_preparation.sql','utf8'),receipt=readFileSync('supabase/migrations/202608230005_preparation_sale_type.sql','utf8'),station=readFileSync('src/pages/InventoryStationPage.tsx','utf8'),inventory=readFileSync('src/pages/InventoryPage.tsx','utf8'),preparation=readFileSync('src/lib/preparation.ts','utf8'),label=readFileSync('src/legacy/operations/pages/PerfumePrintLabelPage.tsx','utf8')
describe('P0 absoluto estoque e estação do perfume',()=>{
 it('venda sem chegada não cria item, movimento ou RUAH-P',()=>{expect(receipt).toContain('nasce exclusivamente dentro de inventory_receive_perfume');expect(sql).toContain("when a.id is null then 'AGUARDANDO PERFUME'");expect(sql).not.toMatch(/create trigger.*sales.*inventory/i)})
 it('primeiro recebimento é atômico e a única entrada física',()=>{const fn=sql.slice(sql.indexOf('create or replace function public.inventory_receive_perfume'),sql.indexOf('create function public.inventory_preparation_totals'));expect(fn).toContain('ensure_perfume_operational_code');expect(fn).toContain("inventory_apply(item.id,p_received_ml,'entry'");expect(fn).toContain("'inventory_physical_receipt'")})
 it('segundo recebimento reutiliza item e código e incrementa somente recebido',()=>{expect(sql).toContain('on conflict(organization_id,perfume_id) do nothing');expect(receipt).toContain('if p.operational_code is not null then return p.operational_code');expect(sql).toContain('p_received_ml')})
 it('recebimento reconcilia vendas anteriores sem baixar físico',()=>{expect(sql).toContain("sale.payment_status='paid'");expect(sql).toContain("sale.inventory_allocation_eligible");expect(sql).not.toContain('sale.sale_date>=item.reference_date');expect(sql).toContain('item.available_ml>=s.volume_ml');expect(sql).toContain('available_ml=available_ml-s.volume_ml');expect(sql).not.toMatch(/physical_ml\s*=\s*physical_ml\s*-\s*s\.volume_ml/)})
 it('scan é zero-write e mostra estoque e candidatos',()=>{expect(preparation).toContain('previewInventoryStation');const preview=preparation.slice(preparation.indexOf('export async function previewInventoryStation'),preparation.indexOf('export async function confirmInventoryStationPreparation'));expect(preview).not.toContain("supabase.rpc('inventory_station_confirm_preparation'");expect(station).toContain('Estoque físico');expect(station).toContain('O bip apenas identificou o perfume. Nada foi alterado.')})
 it('scanner aceita Enter/manual e recupera foco',()=>{expect(station).toContain('onSubmit=');expect(station).toContain('autoFocus');expect(station).toContain("manualInput.current?.focus()")})
 it('SPLIT e APC aparecem separados e APC não entra no total',()=>{expect(station).toContain("(['SPLIT','APC']as const)");expect(station).toContain("item.sale_type==='SPLIT'");expect(station).toContain('TOTAL SPLIT:')})
 it('seleção parcial envia apenas allocations marcadas',()=>{expect(station).toContain('perfume.items.filter(item=>selected.has(item.allocation_id)).map');expect(station).toContain('setSelected')})
 it('confirmação é atômica e idempotente usando batches existentes',()=>{const fn=sql.slice(sql.indexOf('inventory_station_confirm_preparation'));for(const value of['pg_advisory_xact_lock','preparation_batch_create','preparation_batch_identify','preparation_batch_confirm',"'inventory_station_preparation_confirmed'"])expect(fn).toContain(value);expect(fn).toContain("'already_confirmed',true")})
 it('confirmação não recebe novamente nem toca shipment/postagem',()=>{const fn=sql.slice(sql.indexOf('create function public.inventory_station_confirm_preparation'),sql.indexOf('-- O status comercial é derivado'));for(const forbidden of['inventory_apply(','insert into public.inventory_movements','post_shipment(','shipment_items','superfrete'])expect(fn).not.toContain(forbidden)})
 it('Davi deriva todos os estados operacionais',()=>{for(const state of['AGUARDANDO PERFUME','AGUARDANDO PREPARAÇÃO','EM PREPARAÇÃO','PRONTO PARA ENVIO','ENVIO EM ANDAMENTO','ENVIADO'])expect(sql).toContain(state)})
 it('estoque separa preparação de envio e não oferece ajuste manual de ML',()=>{expect(inventory).toContain('<dt>Em preparo</dt>');expect(inventory).toContain('<dt>Em envio</dt>');for(const action of['Custo','Mínimo','Atualizar vendas'])expect(inventory).toContain(action);for(const hidden of['Estação de estoque','Abrir no leitor','Ajustar saldo','Entrada física em ML'])expect(inventory).not.toContain(hidden)})
 it('saldo fica protegido contra ajuste manual; custo e mínimo continuam editáveis',()=>{expect(inventory).not.toContain('const receiveEntry=async');expect(inventory).not.toContain('const correctBalance=async');expect(inventory).not.toContain('await adjustInventory(row.item_id,delta,reason)');expect(inventory).toContain('setPerfumeCost');expect(inventory).toContain('updateInventoryMinimum')})
 it('etiqueta conserva payload RUAH-P único em humano, QR e Code128',()=>{expect(label).toContain('<BarcodeImage value={label.operational_code}');expect(label).toContain('<QrCodeImage value={label.operational_code}');expect(label).toContain('<code>{label.operational_code}</code>');expect(inventory).toContain('printPerfumeLabel')})
})
