import {authenticatedOrganization,fetchOperationalInventory} from './records'
import {supabase} from './supabase'

export type PreparationPerfume={id:string;full_name_raw:string;brand_house:string|null;operational_code:string|null}
export type PreparationCandidate={allocation_id:string;client_name:string;sale_type:string|null;quantity_ml:number;prepared_ml:number;remaining_ml:number;bottle_tracking_status:string}
export type PreparationBottle={id:string;bottle_code:string;bottle_label:string;physical_ml:number}
export type PreparationItemInput={allocation_id:string;quantity_ml:number;source_bottle_id:string|null}

export async function fetchPreparationPerfumes(){const {organizationId}=await authenticatedOrganization();const {data,error}=await supabase!.from('perfumes').select('id,full_name_raw,brand_house,operational_code').eq('organization_id',organizationId).order('full_name_raw');if(error)throw new Error(error.message);return(data??[])as PreparationPerfume[]}
export async function fetchPreparationCandidates(perfumeId:string){await authenticatedOrganization();const {data,error}=await supabase!.rpc('preparation_candidates',{p_perfume_id:perfumeId});if(error)throw new Error(error.message);return(data??[])as PreparationCandidate[]}
export async function fetchPreparationBottles(perfumeId:string){const {organizationId}=await authenticatedOrganization();const {data,error}=await supabase!.from('inventory_bottles').select('id,bottle_code,bottle_label,physical_ml').eq('organization_id',organizationId).eq('perfume_id',perfumeId).eq('status','active').gt('physical_ml',0).order('bottle_code');if(error)throw new Error(error.message);return(data??[])as PreparationBottle[]}
export async function resolvePerfumeOperationalCode(code:string){await authenticatedOrganization();const {data,error}=await supabase!.rpc('resolve_perfume_operational_code',{p_code:code});if(error)throw new Error(error.message);return((data??[])[0]??null)as({perfume_id:string;perfume_name:string;brand_house:string|null;operational_code:string}|null)}
export async function createPreparationBatch(perfumeId:string,items:PreparationItemInput[]){await authenticatedOrganization();const {data,error}=await supabase!.rpc('preparation_batch_create',{p_perfume_id:perfumeId,p_items:items});if(error)throw new Error(error.message);return data as string}
export async function identifyPreparationBatch(batchId:string,code:string){await authenticatedOrganization();const {data,error}=await supabase!.rpc('preparation_batch_identify',{p_batch_id:batchId,p_code:code});if(error)throw new Error(error.message);return data as {ok:boolean;reason?:string;expected?:string;scanned?:string;perfume?:string;total_ml?:number;item_count?:number}}
export async function confirmPreparationBatch(batchId:string){await authenticatedOrganization();const {data,error}=await supabase!.rpc('preparation_batch_confirm',{p_batch_id:batchId});if(error)throw new Error(error.message);return data as {ok:boolean;already_confirmed:boolean;message?:string;total_ml?:number;item_count?:number}}
export type InventoryStationPreview={perfume_id:string;perfume_name:string;brand_house:string|null;operational_code:string;physical_ml:number;available_ml:number;items:PreparationCandidate[]}
export async function previewInventoryStation(code:string){const perfume=await resolvePerfumeOperationalCode(code);if(!perfume)return null;const[items,balances]=await Promise.all([fetchPreparationCandidates(perfume.perfume_id),fetchOperationalInventory()]),balance=balances.find(row=>row.perfume_id===perfume.perfume_id);if(!balance)return null;return{...perfume,physical_ml:Number(balance.physical_ml),available_ml:Number(balance.available_ml),items}as InventoryStationPreview}
export async function confirmInventoryStationPreparation(code:string,items:PreparationItemInput[],idempotencyKey:string){await authenticatedOrganization();const{data,error}=await supabase!.rpc('inventory_station_confirm_preparation',{p_operational_code:code,p_items:items,p_idempotency_key:idempotencyKey});if(error)throw new Error(error.message);return data as{ok:boolean;already_confirmed:boolean;batch_id:string;item_count:number;total_ml:number}}
export function printPerfumeLabel(perfume:PreparationPerfume){if(!perfume.operational_code)throw new Error('Este perfume ainda não foi recebido fisicamente.');const query=new URLSearchParams({codes:perfume.operational_code});window.open(`/print/perfume?${query}`,'_blank','width=640,height=420')}
