const labels:Record<string,string>={
  draft:'Rascunho',requested:'Preparando envio',awaiting_customer_approval:'Aguardando aprovação do cliente',customer_approved:'Aprovado pelo cliente',label_pending:'Emitindo etiqueta',label_released:'Etiqueta liberada',posted:'Postado',delivered:'Entregue',cancelled:'Cancelado',reserved:'Produto reservado',shipping:'Em preparação para envio',shipped:'Enviado',released:'Liberado',review_required:'Precisa de conferência',reconciled:'Conferido',pending:'Pendente',active:'Ativo',inactive:'Inativo',operational_stock:'Estoque operacional',legacy_manual_verified:'Conferido manualmente',shipment_created:'Envio criado',quote_selected:'Frete selecionado',customer_approved_event:'Cliente aprovou o frete',shipment_posted:'Pedido postado',shipment_delivered:'Pedido entregue',shipment_cancelled:'Envio cancelado',
}
export const operationalLabel=(value:unknown)=>{const key=String(value??'').trim();return labels[key]??key.replaceAll('_',' ').replace(/^./,letter=>letter.toUpperCase())}
// SUPERFRETE_STATE_APPLY_ERROR/SUPERFRETE_PRINT_PERSIST_ERROR/
// SUPERFRETE_INVALID_RESPONSE têm texto próprio porque descrevem uma falha
// LOCAL do RUAH depois que a SuperFrete já confirmou/respondeu — nunca
// devem herdar o texto genérico de "revise os dados", que sugere um
// problema do lado do pedido, não da sincronização.
export const friendlyIntegrationError=(value:unknown)=>{const text=String(value??'').trim();if(!text)return'';const known:Record<string,string>={SUPERFRETE_PROVIDER_PROCESSING:'A SuperFrete ainda está preparando o arquivo.',SUPERFRETE_FILE_MISSING:'O pedido existe, mas o arquivo ainda não foi retornado.',SUPERFRETE_FILE_AUTH_OR_EXPIRED:'O link do arquivo expirou ou exige nova autenticação.',SUPERFRETE_FILE_HTML:'A SuperFrete retornou uma página em vez do PDF oficial.',SUPERFRETE_FILE_INVALID_URL:'A URL retornada para a etiqueta não é válida ou confiável.',SUPERFRETE_FILE_EXTERNAL_ERROR:'A consulta do arquivo falhou ou excedeu o tempo.',PHYSICAL_CONFERENCE_PENDING:'Envio aguardando conferência física — bipe o frasco ou split pendente e sincronize novamente.',SUPERFRETE_STATE_APPLY_ERROR:'A SuperFrete confirmou o pedido, mas o RUAH não conseguiu salvar o novo estado. Sincronize novamente.',SUPERFRETE_PRINT_PERSIST_ERROR:'O estado foi sincronizado, mas o RUAH não conseguiu salvar o status de impressão. Sincronize novamente.',SUPERFRETE_INVALID_RESPONSE:'A SuperFrete respondeu em um formato inesperado. Sincronize novamente.'};if(known[text])return known[text];if(/SUPERFRETE|HTTP[_ ]?\d|^[A-Z0-9_]+$/.test(text))return'Não foi possível concluir a operação com a transportadora. Revise os dados e tente novamente.';return text}

export const statusLabel: Record<string, string> = { paid: 'Pago', pending: 'Aguardando', cancelled: 'Cancelado', unknown: 'Desconhecido' }
