import{describe,expect,it}from'vitest'
import{readFileSync}from'node:fs'
const migration=readFileSync('supabase/migrations/202608230009_sale_payment_attachments.sql','utf8'),page=readFileSync('src/pages/DaviExcelPage.tsx','utf8'),drafts=readFileSync('src/components/DaviExcelNewRows.tsx','utf8'),panel=readFileSync('src/components/SalePaymentAttachmentsModal.tsx','utf8'),client=readFileSync('src/lib/sale-payment-attachments.ts','utf8'),edge=readFileSync('supabase/functions/sale-payment-attachment-upload/index.ts','utf8')
describe('P0 comprovantes canônicos por venda',()=>{
 it('cria migration 230009 sem alterar a responsabilidade da 230008',()=>{expect(migration).toContain('create table public.sale_payment_attachments');expect(migration).toContain('sale_id uuid not null references public.sales(id)')})
 it('usa bucket privado, limite e MIME allowlist',()=>{expect(migration).toContain("'sale-payment-attachments','sale-payment-attachments',false,10485760");for(const mime of['application/pdf','image/jpeg','image/png','image/webp'])expect(migration).toContain(`'${mime}'`)})
 it('isola tenant e exige sales.edit no banco e Storage',()=>{expect(migration.match(/has_org_permission\([^)]*'sales\.edit'/g)?.length).toBeGreaterThanOrEqual(7);expect(migration).toContain("s.organization_id=(storage.foldername(name))[1]::uuid");expect(migration).toContain("s.id=(storage.foldername(name))[2]::uuid")})
 it('valida magic bytes também no backend, não só no browser',()=>{for(const signature of['%PDF-','RIFF','WEBP','137,80,78,71,13,10,26,10'])expect(edge).toContain(signature);expect(edge).toContain('file.type!==rule.mime');expect(edge).toContain('file.size>max')})
 it('faz cleanup se metadata falhar e retry não duplica id',()=>{expect(edge).toContain("remove([path])");expect(migration).toContain('on conflict(id) do nothing');expect(migration).toContain("raise exception 'attachment_conflict'")})
 it('signed URL é temporária e nunca persistida',()=>{expect(client).toContain('createSignedUrl(attachment.storage_path,60');expect(migration).not.toMatch(/signed_url/i)})
 it('soft-delete exige confirmação humana e audita upload/exclusão',()=>{expect(panel).toContain("confirm('Excluir este comprovante?')");expect(migration).toContain('deleted_at=now(),deleted_by=auth.uid()');expect(migration).toContain("'sale_payment_attachment_uploaded'");expect(migration).toContain("'sale_payment_attachment_deleted'")})
 it('coluna e contador usam sale.id e suportam vários anexos',()=>{expect(page).toContain('<th>ANEXOS</th>');expect(page).toContain('data-sale-id={row.id}');expect(page).toContain('row.attachment_count');expect(migration).not.toMatch(/unique\s*\(sale_id\)/i)})
 it('draft bloqueia anexo até obter sale.id',()=>{expect(drafts).toContain('Salve a venda antes de anexar comprovantes.');expect(drafts).toContain('📎 —')})
 it('filtro com/sem combina no servidor com os demais filtros',()=>{expect(page).toContain('COM ANEXO');expect(page).toContain('SEM ANEXO');expect(migration).toContain("$1->>'attachment'='with'");expect(migration).toContain("$1->>'attachment'='without'");expect(migration).toContain("$1#>'{columns,payment}'")})
 it('upload não altera pagamento e edição mantém o mesmo sale.id',()=>{expect(migration).not.toMatch(/update\s+public\.sales/i);expect(edge).not.toContain('payment_status');expect(page).toContain('row.id===attachmentSale?.id');expect(page).toContain('key={row.id}')})
 it('viewer não recebe acesso financeiro automaticamente',()=>{expect(page).toContain('Sem acesso financeiro');expect(page).toContain('canEdit&&<label className="davi-attachment-filter"');expect(migration).toContain("has_org_permission(a.organization_id,'sales.edit')")})
})
