import {context,json} from '../_shared/security.ts'
import {classifyClientMatches,countSaleCandidateLines,missingShippingFields,normalizeBatchName,normalizePerfumeName,parseDaviSalesBatch,parseShippingAvailability,perfumeIdentity} from '../_shared/sales-batch-domain.ts'

const sha256=async(value:string)=>[...new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value)))].map(x=>x.toString(16).padStart(2,'0')).join('')

Deno.serve(async req=>{
  const ctx=await context(req,{allowSingleOrganizationFallback:true});if('response'in ctx)return ctx.response
  if(ctx.role==='viewer')return json({error:{code:'forbidden',message:'Perfil sem permissão para preparar importações.'}},403,req)
  const text=String(ctx.body.text??'').trim().slice(0,20000),saleDate=String(ctx.body.sale_date??'')
  if(!text||!/^[0-9]{4}-[0-9]{2}-[0-9]{2}$/.test(saleDate))return json({error:{code:'invalid_payload',message:'Mensagem e data das vendas são obrigatórias.'}},400,req)
  const requestId=crypto.randomUUID(),lineCount=text.split(/\r?\n/).length,candidateCount=countSaleCandidateLines(text)
  let parsed;try{parsed=parseDaviSalesBatch(text)}catch{console.warn(JSON.stringify({stage:'sales_batch_unrecognized',request_id:requestId,text_length:text.length,line_count:lineCount,candidate_sale_lines:candidateCount,llm_sales_count:0,fallback_sales_count:0,schema_errors_count:1}));return json({error:{code:'parse_failed',message:'Não foi possível reconhecer uma lista de vendas válida.'}},422,req)}
  if(!parsed.sales.length){console.warn(JSON.stringify({stage:'sales_batch_unrecognized',request_id:requestId,text_length:text.length,line_count:lineCount,candidate_sale_lines:candidateCount,llm_sales_count:0,fallback_sales_count:0,schema_errors_count:0}));return json({error:{code:candidateCount?'sales_unrecognized':'sales_missing',message:candidateCount?'Encontrei possíveis vendas, mas não consegui interpretar algumas linhas.':'Nenhuma venda foi reconhecida na mensagem.',details:candidateCount?{candidate_count:candidateCount}:undefined,request_id:requestId}},422,req)}
  const key=Deno.env.get('OPENAI_API_KEY');if(parsed.source_format==='whatsapp'&&!key)return json({error:{code:'assistant_unavailable',message:'A interpretação com IA não está disponível agora.'}},503,req)
  if(parsed.source_format==='whatsapp')try{
    const ai=await fetch('https://api.openai.com/v1/responses',{method:'POST',signal:AbortSignal.timeout(30_000),headers:{authorization:`Bearer ${key}`,'content-type':'application/json'},body:JSON.stringify({model:Deno.env.get('OPENAI_MODEL')||'gpt-5-mini',reasoning:{effort:'low'},input:[{role:'system',content:'Extraia somente telefone e endereço explicitamente associados a cada cliente nesta lista brasileira. Nunca invente nem complete. Linhas de saldo disponível não são clientes nem vendas e devem ser ignoradas nesta extração. Retorne null quando ausente.'},{role:'user',content:text}],text:{format:{type:'json_schema',name:'sales_batch_contacts',strict:true,schema:{type:'object',additionalProperties:false,required:['contacts'],properties:{contacts:{type:'array',items:{type:'object',additionalProperties:false,required:['client_name','phone','address'],properties:{client_name:{type:'string'},phone:{type:['string','null']},address:{type:['string','null']}}}}}}}}})})
    if(ai.ok){const body=await ai.json(),raw=body.output?.flatMap((x:Record<string,unknown>)=>Array.isArray(x.content)?x.content:[]).find((x:Record<string,unknown>)=>x.type==='output_text')?.text,contacts=JSON.parse(String(raw||'{"contacts":[]}')).contacts??[];parsed={...parsed,sales:parsed.sales.map(sale=>{const contact=contacts.find((x:Record<string,unknown>)=>normalizeBatchName(x.client_name)===normalizeBatchName(sale.client_name));return contact?{...sale,phone:contact.phone??null,address:contact.address??null}:sale})}}
  }catch{/* parser determinístico permanece válido; nenhum write ocorreu */}
  const fingerprint=await sha256(`${saleDate}|${parsed.source_format}|${parsed.bottle_number}|${parsed.sales.map(s=>`${normalizeBatchName(s.perfume_name||parsed.perfume)}:${normalizeBatchName(s.client_name)}:${s.sale_type}:${s.volume_ml}:${s.amount}`).sort().join('|')}`)
  const [{data:clients},{data:perfumes},{data:inventory},{data:prior},{data:existingSales}]=await Promise.all([
    ctx.client.from('clients').select('id,name,normalized_name,phone,whatsapp_phone,email,cpf,cnpj,postal_code,address_line,address_number,complement,district,city,state').eq('organization_id',ctx.organizationId).is('deleted_at',null),
    ctx.client.from('perfumes').select('id,full_name_raw,normalized_name').eq('organization_id',ctx.organizationId),
    ctx.client.rpc('inventory_operational_rows',{org_id:ctx.organizationId}),
    ctx.client.from('ai_sales_batches').select('id,created_at,perfume_name,bottle_number,sales_count,status').eq('organization_id',ctx.organizationId).eq('fingerprint',fingerprint).limit(1),
    ctx.client.from('sales').select('id,client_name_raw,sale_type,volume_ml,amount,perfume_name_raw').eq('organization_id',ctx.organizationId).eq('sale_date',saleDate).is('deleted_at',null),
  ])
  const enrichedSales=parsed.sales.map(sale=>{const salePerfume=sale.perfume_name||parsed.perfume,resolution=classifyClientMatches(sale.client_name,clients??[]),match=resolution.match,possible=(existingSales??[]).some(row=>normalizeBatchName(row.client_name_raw)===normalizeBatchName(sale.client_name)&&normalizeBatchName(row.perfume_name_raw)===normalizeBatchName(salePerfume)&&row.sale_type===sale.sale_type&&Number(row.volume_ml)===sale.volume_ml&&Number(row.amount)===sale.amount);return {...sale,client_match_status:resolution.status,client_id:match?.id??null,client:match??null,suggestions:resolution.suggestions.map(c=>({id:c.id,name:c.name,missing_shipping_fields:missingShippingFields(c)})),missing_shipping_fields:match?missingShippingFields(match):['CPF','telefone','CEP','endereço','número','bairro','cidade','UF'],possible_duplicate:possible}})
  const resolvePerfume=(name:string)=>{const identity=perfumeIdentity(name),normalized=identity.normalized_perfume_name,exact=(perfumes??[]).filter(p=>normalizePerfumeName(p.normalized_name||p.full_name_raw)===normalized),suggested=exact.length?exact:(perfumes??[]).filter(p=>{const candidate=normalizePerfumeName(p.full_name_raw);return candidate.includes(normalized)||normalized.includes(candidate)}),matches=suggested.slice(0,8),perfume=exact.length===1?exact[0]:suggested.length===1?suggested[0]:null,stock=(inventory??[]).find((row:Record<string,unknown>)=>row.perfume_id===perfume?.id)??null;return{...identity,perfume_match_status:perfume?'found':matches.length?'review':'new',perfume_id:perfume?.id??null,perfume_matches:matches,inventory:stock,inventory_item_id:stock?.item_id??null}}
  const primary={...resolvePerfume(parsed.perfume),bottle_number:parsed.bottle_number},groups=(parsed.groups??[]).map(group=>{const resolved=resolvePerfume(group.raw_perfume_name||group.perfume);return{...group,...resolved,sales:enrichedSales.filter(sale=>normalizePerfumeName(sale.perfume_name)===group.normalized_perfume_name)}})
  const availability=parseShippingAvailability(text,saleDate)
  // Um lote antigo cujas vendas foram todas apagadas não é duplicidade ativa:
  // o operador precisa poder revisar e importar novamente. Se ao menos uma
  // venda equivalente ainda existe, o bloqueio de duplicidade permanece.
  const activeDuplicate=enrichedSales.some(sale=>sale.possible_duplicate)?(prior??[])[0]??null:null
  return json({data:{...parsed,...primary,...availability,groups,sale_date:saleDate,shipping_deadline_date:availability.shipping_available_date,fingerprint,duplicate_batch:activeDuplicate,sales:enrichedSales,summary:{clients:enrichedSales.length,found:enrichedSales.filter(x=>x.client_match_status==='found').length,new:enrichedSales.filter(x=>x.client_match_status==='new').length,review:enrichedSales.filter(x=>x.client_match_status==='review').length,shipping_ready:enrichedSales.filter(x=>x.missing_shipping_fields.length===0).length,shipping_incomplete:enrichedSales.filter(x=>x.missing_shipping_fields.length>0).length}},meta:{writes:0,requires_human_confirmation:true,llm_role:parsed.source_format==='tsv'?'not_used':'language_interpretation_only',stock_writes:0,shipment_writes:0}},200,req)
})
