import {expect,test} from '@playwright/test'

const perfumes=['BLOCKADE — MIND GAMES','BLONDE AMBER — CLIVE CHRISTIAN','FRENCH DEFENSE — MIND GAMES','FÈVE NECTAR — PLACE DE LA RÊVERIE','QUILOMBO — FUEGUIA 1833','THAYS — FUEGUIA 1833','IMAGINATION — LOUIS VUITTON','OUD SATIN MOOD — MAISON FRANCIS KURKDJIAN','DELINA — PARFUMS DE MARLY','NAXOS — XERJOFF']
const cards=perfumes.map((name,index)=>`<article><div><strong>${name}</strong><span>${index+3} vendas · ${index+8} ml · R$ ${(149.7*(index+1)).toLocaleString('pt-BR',{minimumFractionDigits:2})}</span></div><span>${index%3===0?'✓ Estoque correspondente':'Precisa selecionar item do estoque'}</span></article>`).join('')
const markup=`<div class="ai-batch-layer"><section class="ai-batch-assistant"><header><div><span>RUAH · ASSISTENTE OPERACIONAL</span><h2>Importar lista com IA</h2><p>A IA interpreta. Você revisa. O CRM só grava depois da confirmação.</p></div><button aria-label="Fechar">×</button></header><div class="ai-batch-preview"><section class="batch-overview"><div><span>IMPORTAÇÃO COM VÁRIOS LOTES</span><h3>10 perfumes encontrados</h3><p>82 vendas · 340 ml · R$ 18.458,00</p></div><div><strong>10</strong><span>lotes</span><strong>82</strong><span>vendas</span><strong>340 ml</strong><span>volume</span></div></section><section class="batch-match"><h4>PERFUMES</h4><div class="batch-group-list">${cards}</div><small>Análise sem escrita. Cada perfume será vinculado separadamente a um item real do estoque.</small></section><section class="batch-dates"><label><span>DATA DAS VENDAS</span><input type="date" value="2026-08-13"></label><label><span>DISPONÍVEL PARA ENVIO</span><input type="date" value="2026-09-04"><small>Prazo extraído da lista.</small></label></section><section><h4>CLIENTES E VENDAS</h4><div class="batch-quality"><span>64 encontrados</span><span>18 novos</span><span>70 prontos para envio</span><span>12 incompletos</span></div><article class="batch-sale"><b>01</b><div><strong>Tatiana Carvalho</strong><small>Pagamento: aguardando confirmação</small></div><label><span>CLIENTE NO CRM</span><select><option>Tatiana Carvalho</option></select></label></article></section><footer><p>Serão criadas 82 vendas pendentes somente após confirmação.</p><button>VOLTAR</button><button class="primary">CRIAR 82 VENDAS</button></footer></div></section></div>`

for(const [width,columns] of [[390,1],[650,2],[768,3],[900,3],[960,3],[1024,4],[1280,5],[1440,5]] as const)test(`prévia IA editorial em ${width}px`,async({page})=>{
  await page.setViewportSize({width,height:1100});await page.goto('/login');await page.setContent(markup)
  for(const file of ['src/styles/tokens.css','src/styles.css','src/enhancements.css','src/styles/rebrand-v2.css'])await page.addStyleTag({path:file})
  await expect(page.getByText('Importar lista com IA',{exact:true})).toBeVisible();await expect(page.getByText('PERFUMES',{exact:true})).toBeVisible();await expect(page.getByText('CLIENTES E VENDAS',{exact:true})).toBeVisible()
  expect(await page.evaluate(()=>document.documentElement.scrollWidth-document.documentElement.clientWidth)).toBeLessThanOrEqual(1)
  const audit=await page.locator('.batch-group-list').evaluate(node=>{const cards=[...node.querySelectorAll<HTMLElement>('article')],style=getComputedStyle(node),rows=new Map<number,number[]>();for(const card of cards){const box=card.getBoundingClientRect(),top=Math.round(box.top),row=rows.get(top)??[];row.push(Math.round(box.height));rows.set(top,row)}return{columns:style.gridTemplateColumns.split(' ').length,rowSpread:Math.max(...[...rows.values()].map(heights=>Math.max(...heights)-Math.min(...heights))),outside:cards.filter(card=>{const box=card.getBoundingClientRect();return box.left<0||box.right>innerWidth}).length}})
  expect(audit.columns).toBe(columns);expect(audit.outside).toBe(0);expect(audit.rowSpread).toBeLessThanOrEqual(1)
  await page.screenshot({path:`tests/screenshots/ai-import-preview-${width}.png`,fullPage:true})
})
