import {expect,test} from '@playwright/test'

const widths=[390,768,1440]
const markup=`<main class="fixture-page">
  <section class="executive-hero" data-fixture="dashboard"><div class="executive-primary"><span>VENDAS NO PERÍODO</span><strong>R$ 12.345.678,90</strong><small>13 relações comerciais</small></div><div class="executive-secondary"><div><span>RECEBIDO</span><strong>R$ 1.234.567,89</strong></div><div><span>PENDENTE</span><strong>R$ 31.864,80</strong></div><div><span>ATENÇÃO OPERACIONAL</span><strong>9</strong></div></div></section>
  <section class="operations-activity card" data-fixture="atividade"><header><span>OPERAÇÃO</span><h3>Atividade e atenção</h3></header><div class="operations-columns"><div><h4>ATENÇÃO</h4><a><span>9 cadastros precisam completar dados para envio</span></a></div><div><h4>HOJE</h4><a><time>10:18</time><span>Davi registrou 13 vendas hoje</span></a></div></div></section>
  <header class="dossier-head surface-dark" data-fixture="cliente"><span class="dossier-eyebrow">CLIENTE</span><h1 class="dossier-name" data-surface-role="primary">TATIANA CARVALHO DE ALBUQUERQUE</h1><p class="dossier-since" data-surface-role="secondary">Cliente desde Março de 2026</p><div class="dossier-stats"><div><strong data-surface-role="metric">89</strong><span>compras</span></div><div><strong data-surface-role="metric">R$ 49.128,70</strong><span>comprados</span></div><div><strong data-surface-role="metric">1.430</strong><span>ml</span></div></div><div class="dossier-actions"><button class="ui-btn ui-btn--secondary"><span>Editar cadastro</span></button><span class="badge paid">ATIVO</span></div></header>
  <header class="ficha-head surface-dark" data-fixture="venda"><span class="ficha-eyebrow">VENDA</span><h1 class="ficha-client" data-surface-role="primary">DUDA LAZZARINI DE OLIVEIRA</h1><p class="ficha-product" data-surface-role="secondary">SISSA - MIND GAMES (FRASCO 2) · 50 ml · APC</p><div class="ficha-price-row"><strong data-surface-role="metric">R$ 1.395,00</strong><span class="badge pending">AGUARDANDO</span></div><div class="ficha-actions"><button class="ui-btn ui-btn--secondary"><span>Ver cliente</span></button><button class="ui-btn ui-btn--primary"><span>Confirmar produto</span></button></div></header>
  <section data-fixture="envio"><header class="shipment-premium-head surface-dark"><div class="ruah-brand"></div><div class="shipment-title"><span>ENVIO 360</span><h1 data-surface-role="primary">CLIENTE RUAH COM NOME OPERACIONAL LONGO</h1><p data-surface-role="secondary">Envio #90FBE65F · 13/08/2026</p></div><div class="shipment-status"><i></i><div><span>Status atual</span><strong>Pronto para calcular frete</strong></div></div></header><div class="next-action surface-accent"><div><span>PRÓXIMO PASSO</span><strong>Pronto para calcular frete</strong><small>Informe o destinatário e calcule as opções de frete.</small></div><button class="primary">CALCULAR FRETE</button></div><nav class="shipment-journey"><div class="shipment-journey-compact"><span>ETAPA 3 DE 8</span><strong>Conferência</strong><div class="shipment-journey-bar"><i style="width:37.5%"></i></div></div></nav></section>
  <section class="label-atelier surface-dark" data-fixture="etiqueta"><header class="label-atelier-head"><div></div><div><span>ETIQUETA DE ENVIO</span><p>Envio #90FBE65F</p><h2 data-surface-role="primary">CLIENTE RUAH COM NOME LONGO</h2></div><strong>ETIQUETA CRIADA</strong></header><div class="label-atelier-footer"><div class="label-premium-actions"><button class="label-primary">ATUALIZAR ETIQUETA</button><button class="label-disabled" disabled>IMPRIMIR ETIQUETA</button></div></div></section>
  <section class="ai-batch-assistant" data-fixture="ia"><header class="surface-dark"><div><span>RUAH · ASSISTENTE OPERACIONAL</span><h2 data-surface-role="primary">Importar lista com IA</h2><p data-surface-role="secondary">A IA interpreta. Você revisa.</p></div><button data-surface-role="action" aria-label="Fechar">×</button></header></section>
</main>`

for(const width of widths)test(`authenticated dark surfaces remain legible at ${width}px`,async({page})=>{
  await page.setViewportSize({width,height:1400});await page.goto('/login');await page.setContent(markup);await page.locator('.label-atelier-head').evaluate(node=>node.classList.add('surface-dark'))
  for(const file of ['src/styles/tokens.css','src/styles.css','src/components/ui/Button.css','src/pages/ClientDetailsPage.css','src/pages/SaleDetailsPage.css','src/enhancements.css','src/styles/rebrand-v2.css'])await page.addStyleTag({path:file})
  await page.addStyleTag({content:'.fixture-page{display:grid;gap:24px;padding:16px;max-width:1200px;margin:auto}.fixture-page>*{min-width:0}.fixture-page .dossier-head,.fixture-page .ficha-head{position:relative;top:auto;display:block;height:auto}.fixture-page .shipment-premium-head{position:relative;top:auto}.fixture-page .ai-batch-assistant{min-height:0}.fixture-page .ai-batch-assistant>header{position:relative;top:auto}body{background:#f7f3eb}'})
  const audit=await page.evaluate(()=>{const lum=(rgb:string)=>{const values=(rgb.match(/\d+/g)||[]).slice(0,3).map(Number).map(v=>{const c=v/255;return c<=.03928?c/12.92:((c+.055)/1.055)**2.4});return .2126*values[0]+.7152*values[1]+.0722*values[2]},ratio=(a:string,b:string)=>{const x=lum(a),y=lum(b);return(Math.max(x,y)+.05)/(Math.min(x,y)+.05)};return[...document.querySelectorAll<HTMLElement>('.surface-dark [data-surface-role="primary"],.surface-dark [data-surface-role="metric"],.surface-dark [data-surface-role="action"]')].map(node=>{const style=getComputedStyle(node),surface=node.closest<HTMLElement>('.surface-dark')!;return{text:node.textContent?.trim(),ratio:ratio(style.color,getComputedStyle(surface).backgroundColor)}})})
  expect(audit.length).toBeGreaterThanOrEqual(10);for(const item of audit)expect(item.ratio,item.text).toBeGreaterThanOrEqual(4.5)
  for(const text of ['TATIANA CARVALHO DE ALBUQUERQUE','Cliente desde Março de 2026','89','R$ 49.128,70','1.430','Editar cadastro','ATIVO','DUDA LAZZARINI DE OLIVEIRA','SISSA - MIND GAMES (FRASCO 2) · 50 ml · APC','R$ 1.395,00','Ver cliente','Confirmar produto','CLIENTE RUAH COM NOME OPERACIONAL LONGO','Pronto para calcular frete','Conferência'])await expect(page.getByText(text,{exact:true}).first()).toBeVisible()
  const clipped=await page.evaluate(()=>[...document.querySelectorAll<HTMLElement>('[data-surface-role="primary"],[data-surface-role="metric"],[data-surface-role="secondary"],.surface-dark .ui-btn')].filter(node=>{const style=getComputedStyle(node);return node.scrollWidth>node.clientWidth+1&&['hidden','clip'].includes(style.overflowX)}).map(node=>node.textContent?.trim()))
  expect(clipped).toEqual([])
  for(const name of ['dashboard','atividade','cliente','venda','envio','etiqueta','ia']){const target=page.locator(`[data-fixture="${name}"]`);await expect(target).toBeVisible();await target.screenshot({path:`tests/screenshots/${name}-${width}.png`})}
  for(const value of ['R$ 12.345.678,90','R$ 1.234.567,89','R$ 31.864,80']){const node=page.getByText(value,{exact:true});await expect(node).toBeVisible();expect(await node.evaluate(el=>el.scrollWidth-el.clientWidth),value).toBeLessThanOrEqual(1)}
  expect(await page.evaluate(()=>document.documentElement.scrollWidth-document.documentElement.clientWidth)).toBeLessThanOrEqual(1)
})
