import{expect,test}from'@playwright/test'

const widths=[320,360,375,390,430,768,1024,1440]
const states={
  indisponivel:`<h1>Estamos finalizando a segurança do seu acesso.</h1><p>O segundo fator de autenticação ainda não está disponível para sua conta. Tente novamente em alguns instantes ou fale com a equipe RUAH.</p><button class="portal-submit">Tentar novamente</button><button class="portal-link">Voltar para entrar</button>`,
  telefone:`<h1>Proteja seu espaço privado.</h1><p>Para manter seus dados seguros, confirme seu celular.</p><form class="portal-form"><label><span>Celular</span><div><input value="(11) 99999-9999"></div></label><button class="portal-submit">Enviar código</button></form>`,
  codigo:`<h1>Confirme que é você.</h1><p>Enviamos um código de segurança para •••••-1234.</p><form class="portal-form"><label><span>Código de segurança</span><input class="portal-code-input" value="123"></label><button class="portal-submit">Confirmar acesso</button></form><button class="portal-link" disabled>Reenviar código em 42s</button><button class="portal-link">Alterar telefone</button>`,
  erro:`<h1>Confirme que é você.</h1><p>Enviamos um código de segurança para •••••-1234.</p><form class="portal-form"><label><span>Código de segurança</span><input class="portal-code-input" value="123456"></label><div class="portal-error">Esse código não confere. Verifique e tente novamente.</div><button class="portal-submit">Confirmar acesso</button></form>`,
  confirmacao:`<h1>Confirmando seu acesso</h1><p>Aguarde um instante.</p><div class="portal-mfa-loading"><span aria-label="Carregando">◌</span></div>`,
}
for(const width of widths)test(`Minha RUAH MFA states @ ${width}px`,async({page})=>{await page.setViewportSize({width,height:900});await page.goto('/minha-ruah/login');for(const[name,body]of Object.entries(states)){await page.setContent(`<main class="portal-auth"><div class="portal-auth-brand"><img src="/ruah-logo.jpg"><strong>RUAH</strong><span>Minha RUAH</span></div><div class="portal-auth-card">${body}</div><small class="portal-auth-safe">Seu espaço privado permanece bloqueado e seguro</small></main>`);await page.addStyleTag({path:'src/styles.css'});await page.addStyleTag({path:'src/portal/customer-portal.css'});const audit=await page.evaluate(()=>({overflow:document.documentElement.scrollWidth-document.documentElement.clientWidth,small:[...document.querySelectorAll<HTMLElement>('button,input')].filter(node=>{const box=node.getBoundingClientRect();return box.width>0&&box.height>0&&(box.width<44||box.height<44)}).length,technical:document.body.innerText.includes('MFA_PROVIDER_NOT_CONFIGURED')}));expect(audit).toEqual({overflow:0,small:0,technical:false});await page.screenshot({path:`tests/screenshots/minha-ruah-mfa-${name}-${width}.png`,fullPage:true})}})
