import{expect,test}from'@playwright/test'

const widths=[320,360,375,390,430,768,1024,1440]
const nav=`<nav class="portal-bottom-nav"><button class="active"><span>⌂</span><span>Início</span></button><button><span>◇</span><span>Perfumes</span></button><button><span>▱</span><span>Envios</span></button><button><span>?</span><span>Ajuda</span></button><button><span>○</span><span>Conta</span></button></nav>`
const pages={
  home:`<div class="portal-page portal-home"><section class="portal-welcome"><span>BEM-VINDA À SUA ÁREA PRIVADA</span><h1>Olá, Cliente.</h1><p>Aqui está a sua história com a RUAH, com a clareza e o cuidado que ela merece.</p></section><section class="portal-collection"><span>MEU ACERVO</span><strong>2 perfumes na RUAH</strong><p>35 ml sob seus cuidados</p><button>Ver meus perfumes</button></section><h2>Agora na RUAH</h2><div class="portal-summary"><div><strong>20 ml</strong><span>Disponível para envio</span></div><div><strong>10 ml</strong><span>Em preparação</span></div><div><strong>5 ml</strong><span>Em transporte</span></div></div><div class="portal-home-links"><button><strong>Meus envios</strong><span>Acompanhe cada etapa</span></button><button><strong>Preciso de ajuda</strong><span>Fale diretamente com a RUAH</span></button></div></div>`,
  perfumes:`<div class="portal-page"><h2>Meus perfumes</h2><div class="portal-card"><strong>Oud Wood</strong><span>Total meu na RUAH: 20 ml</span><span>Disponível para solicitar: 20 ml</span><button>Solicitar envio</button></div><div class="portal-card"><strong>Delina Exclusif</strong><span>Total meu na RUAH: 15 ml</span><span>Já solicitado: 15 ml</span></div></div>`,
  envios:`<div class="portal-page"><h2>Meus envios</h2><button class="portal-link">Ver histórico completo</button><div class="portal-card portal-request-card"><strong>Delina Exclusif (15ml)</strong><div class="portal-progress"><span class="done">✓ Solicitação recebida</span><span class="done">✓ Frete cotado</span><span>○ Envio confirmado</span><span>○ Postado</span></div></div></div>`,
  historico:`<div class="portal-page"><h2>Histórico</h2><h3>Compras</h3><div class="portal-card"><strong>Oud Wood</strong><span>12/08/2026 · 20 ml · R$ 980,00</span></div><h3>Envios recebidos</h3><p class="portal-empty">Nenhum envio recebido ainda.</p></div>`,
  ajuda:`<div class="portal-page"><h2>Preciso de ajuda</h2><button class="portal-submit">Abrir novo chamado</button><p class="portal-empty">Você ainda não abriu nenhum chamado.</p></div>`,
  conta:`<div class="portal-page"><h2>Minha conta</h2><div class="portal-card"><strong>Cliente RUAH</strong><span>cliente@exemplo.com</span><span>(11) 99999-9999</span><span>CPF •••.•••.•••-12</span><span>São Paulo, SP</span></div><button class="portal-account-action">Alterar senha</button><button class="portal-submit portal-danger">Sair</button></div>`,
}

for(const width of widths)test(`Minha RUAH private surfaces @ ${width}px`,async({page})=>{await page.setViewportSize({width,height:900});await page.goto('/minha-ruah/login');for(const[name,content]of Object.entries(pages)){await page.setContent(`<div class="portal-app"><header class="portal-header"><div><span>RUAH</span><strong>Minha RUAH</strong></div><em>Olá, Cliente</em></header><main class="portal-main">${content}</main>${nav}</div>`);await page.addStyleTag({path:'src/styles.css'});await page.addStyleTag({path:'src/portal/customer-portal.css'});const audit=await page.evaluate(()=>({overflow:document.documentElement.scrollWidth-document.documentElement.clientWidth,small:[...document.querySelectorAll<HTMLElement>('button,input')].filter(node=>{const box=node.getBoundingClientRect();return box.width>0&&box.height>0&&(box.width<44||box.height<44)}).length}));expect(audit).toEqual({overflow:0,small:0});await page.screenshot({path:`tests/screenshots/minha-ruah-auth-${name}-${width}.png`,fullPage:true})}})
