import{expect,test}from'@playwright/test'
import{navigation}from'../src/routing'

for(const width of [320,360,375,390,430])test(`mobile drawer renders the complete navigation and closes safely @ ${width}px`,async({page})=>{
  await page.setViewportSize({width,height:844});await page.goto('/')
  const labels=navigation.map(({label})=>label==='Visão Geral'?'Visão 360':label==='Torre de Controle'?'Tarefas':label)
  await page.setContent(`<div class="app-shell"><main><header><button id="menu" class="icon-button mobile-menu" aria-label="Abrir menu">☰</button><div><p>CRM RUAH</p><h1>Visão 360</h1></div></header><section class="page"><div class="page-lead"><div><h2>Visão geral</h2><p>Acompanhe os resultados do período.</p></div><div class="period-filter stacking-regression"><button class="date-filter">Últimos 30 dias</button></div></div><div class="metrics"><article class="metric card"><strong>R$ 12.450,00</strong><small>Vendas no período</small></article></div></section></main><div class="ui-drawer-layer" hidden><button class="ui-drawer-scrim" aria-label="Fechar menu"></button><div class="ui-drawer-panel ui-drawer-panel--left" role="dialog" aria-modal="true" aria-label="Menu de navegação"><div class="sidebar sidebar--drawer" data-mobile-sidebar-content><div class="brand"><img src="/ruah-logo.jpg" alt="RUAH Parfums"><div><strong>RUAH</strong><span>INTELLIGENCE</span></div></div><nav>${labels.map((label,index)=>`<button ${index===0?'class="active" aria-current="page"':''}><svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="7" fill="none" stroke="currentColor"/></svg><span>${label}</span></button>`).join('')}</nav><div class="sidebar-foot"><div class="workspace-mark">RP</div><div><strong>RUAH Parfums</strong><span>Administrador</span></div><span>•••</span></div></div></div></div></div>`)
  for(const file of ['src/styles/tokens.css','src/styles.css','src/styles/rebrand-v2.css','src/components/ui/Drawer.css','src/components/Sidebar.css'])await page.addStyleTag({path:file})
  await page.addStyleTag({content:'[hidden]{display:none!important}.stacking-regression{position:fixed!important;z-index:30!important;top:170px!important;left:20px!important;width:360px!important}.stacking-regression .date-filter{width:100%!important;background:#fff!important}'})
  await page.evaluate(()=>{const layer=document.querySelector<HTMLElement>('.ui-drawer-layer')!,menu=document.querySelector<HTMLButtonElement>('#menu')!,close=()=>{layer.hidden=true;document.body.style.overflow='';menu.focus()},open=()=>{layer.hidden=false;document.body.style.overflow='hidden';document.querySelector<HTMLButtonElement>('.sidebar--drawer nav button')?.focus()};menu.onclick=open;document.querySelector<HTMLButtonElement>('.ui-drawer-scrim')!.onclick=close;document.querySelectorAll<HTMLButtonElement>('.sidebar--drawer nav button').forEach(button=>button.onclick=close);document.addEventListener('keydown',event=>{if(event.key==='Escape'&&!layer.hidden)close()})})
  if(width===390)await page.screenshot({path:'tests/screenshots/mobile-menu-390-closed.png'})
  await page.getByRole('button',{name:'Abrir menu'}).click();await expect(page.getByRole('dialog',{name:'Menu de navegação'})).toBeVisible();await expect(page.getByRole('button',{name:'Clientes'})).toBeVisible();await expect(page.locator('body')).toHaveCSS('overflow','hidden');await page.waitForTimeout(250)
  const audit=await page.evaluate(()=>{const panel=document.querySelector<HTMLElement>('.ui-drawer-panel')!.getBoundingClientRect(),sidebarNode=document.querySelector<HTMLElement>('.sidebar--drawer')!,sidebar=sidebarNode.getBoundingClientRect(),nav=document.querySelector<HTMLElement>('.sidebar--drawer nav')!,styles=[sidebarNode,sidebarNode.querySelector<HTMLElement>('.brand')!,nav,sidebarNode.querySelector<HTMLElement>('.sidebar-foot')!].map(node=>{const s=getComputedStyle(node);return{display:s.display,visibility:s.visibility,opacity:s.opacity,transform:s.transform,translate:s.translate,position:s.position,zIndex:s.zIndex,width:s.width,height:s.height,overflow:s.overflow,color:s.color,pointerEvents:s.pointerEvents}});return{panel:[panel.left,panel.right,panel.top,panel.bottom,panel.width],sidebar:[sidebar.left,sidebar.right,sidebar.width],navOverflow:nav.scrollHeight>=nav.clientHeight,bodyOverflow:document.body.style.overflow,styles}})
  expect(audit.panel[0]).toBe(0);expect(audit.panel[2]).toBe(0);expect(audit.panel[3]).toBe(844);expect(audit.panel[4]).toBeLessThanOrEqual(320);expect(audit.sidebar[0]).toBe(0);expect(audit.sidebar[1]).toBe(audit.panel[1]);expect(audit.bodyOverflow).toBe('hidden')
  for(const style of audit.styles){expect(style.display).not.toBe('none');expect(style.visibility).toBe('visible');expect(style.opacity).toBe('1');expect(style.transform).toBe('none');expect(style.pointerEvents).toBe('auto')}
  expect(await page.evaluate(()=>document.elementFromPoint(160,190)?.closest('.ui-drawer-panel')!==null)).toBe(true)
  expect(await page.evaluate(()=>document.elementFromPoint(innerWidth-5,190)?.classList.contains('ui-drawer-scrim'))).toBe(true)
  if(width===390)await page.screenshot({path:'tests/screenshots/mobile-menu-390-open-final.png'})
  await page.keyboard.press('Escape');await expect(page.locator('.ui-drawer-layer')).toBeHidden();await expect(page.locator('body')).not.toHaveCSS('overflow','hidden')
  await page.getByRole('button',{name:'Abrir menu'}).click();await page.getByRole('button',{name:'Clientes'}).click();await expect(page.locator('.ui-drawer-layer')).toBeHidden()
  await page.getByRole('button',{name:'Abrir menu'}).click();await page.mouse.click(width-5,400);await expect(page.locator('.ui-drawer-layer')).toBeHidden()
})
