import{expect,test}from'@playwright/test'

const widths=[320,360,375,390,430,768,1024,1440]
const weekdays=['dom','seg','ter','qua','qui','sex','sáb']
const month=(label:string,offset=0)=>`<div class="rdp-month"><div class="rdp-month_caption"><span class="rdp-caption_label">${label}</span></div><table class="rdp-month_grid"><thead><tr>${weekdays.map(day=>`<th class="rdp-weekday">${day}</th>`).join('')}</tr></thead><tbody>${Array.from({length:5},(_,week)=>`<tr class="rdp-week">${Array.from({length:7},(_,day)=>{const value=week*7+day+1+offset;return`<td class="rdp-day"><button class="rdp-day_button" data-day="${value}">${value>31?value-31:value}</button></td>`}).join('')}</tr>`).join('')}</tbody></table></div>`
const presets=['Hoje','Ontem','Últimos 7 dias','Últimos 30 dias','Este mês','Mês anterior','Este trimestre','Este ano','Todo o período','Período personalizado']

for(const width of widths)test(`period filter responsive flow @ ${width}px`,async({page})=>{
  await page.setViewportSize({width,height:900});await page.goto('/');
  const months=month('agosto de 2026')
  await page.setContent(`<main class="period-fixture"><section class="page"><div class="page-lead"><div><h2>Visão geral</h2><p>Acompanhe os resultados do período.</p></div><div class="period-filter"><button class="date-filter" id="trigger"><span>Últimos 30 dias</span></button><div class="period-popover" role="dialog"><div class="period-mobile-head"><strong>Selecionar período</strong><button id="close" aria-label="Fechar filtro">×</button></div><div class="period-panel-body"><div class="period-presets">${presets.map((name,index)=>`<button aria-label="${name}" ${index===3?'aria-pressed="true"':''} class="${index===9?'period-preset-custom':''}"><span class="period-label-full">${name}</span><span class="period-label-mobile">${name.replace('Últimos ','').replace('Período personalizado','Personalizado').replace('Todo o período','Todo período')}</span></button>`).join('')}</div><div class="period-calendar"><div class="period-inputs"><label>Data inicial<input value="22/07/2026"></label><span>até</span><label>Data final<input value="20/08/2026"></label></div><div class="rdp-root"><nav class="rdp-nav"><button class="rdp-button_previous" aria-label="Mês anterior">‹</button><button class="rdp-button_next" aria-label="Próximo mês">›</button></nav><div class="rdp-months">${months}</div></div></div></div><div class="period-actions"><button id="clear">Limpar</button><button class="primary" id="apply">Aplicar</button></div></div></div><div class="metrics"><article class="metric card"><strong>R$ 12.450,00</strong></article><article class="metric card"><strong>32 vendas</strong></article></div></section></main>`)
  for(const file of ['node_modules/react-day-picker/src/style.css','src/styles/tokens.css','src/styles.css','src/enhancements.css','src/styles/rebrand-v2.css'])await page.addStyleTag({path:file})
  await page.addStyleTag({content:'[hidden]{display:none!important}.period-fixture{width:100%!important;min-height:100vh;margin:0!important}.period-fixture .page{max-width:1180px}.period-fixture .period-filter{margin-left:auto}.period-fixture .metrics{margin-top:40px}.period-fixture .rdp-nav{z-index:3;position:absolute;inset-block-start:0;inset-inline-end:0;display:flex;align-items:center;height:var(--rdp-nav-height)}@media(min-width:768px){.period-fixture .period-filter{position:absolute;right:24px;top:32px}}'})
  await page.evaluate(()=>{const pop=document.querySelector<HTMLElement>('.period-popover')!,show=(visible:boolean)=>{pop.hidden=!visible},trigger=document.querySelector<HTMLButtonElement>('#trigger')!,inputs=[...document.querySelectorAll<HTMLInputElement>('.period-inputs input')],caption=document.querySelector<HTMLElement>('.rdp-caption_label')!;trigger.onclick=()=>show(pop.hidden);document.querySelector<HTMLButtonElement>('#close')!.onclick=()=>show(false);document.querySelector<HTMLButtonElement>('.rdp-button_previous')!.onclick=()=>{caption.textContent='julho de 2026'};document.querySelector<HTMLButtonElement>('.rdp-button_next')!.onclick=()=>{caption.textContent='setembro de 2026'};document.querySelectorAll<HTMLButtonElement>('.period-presets button').forEach(button=>button.onclick=()=>{document.querySelectorAll('.period-presets button').forEach(item=>item.removeAttribute('aria-pressed'));button.setAttribute('aria-pressed','true')});let selected=0;document.querySelectorAll<HTMLButtonElement>('.rdp-day_button').forEach(button=>button.onclick=()=>{button.classList.add(selected++?'range-end':'range-start');inputs[Math.min(selected-1,1)].value=`${String(button.dataset.day).padStart(2,'0')}/08/2026`});document.querySelector<HTMLButtonElement>('#clear')!.onclick=()=>{inputs.forEach(input=>input.value='');document.querySelectorAll('.rdp-day_button').forEach(item=>item.classList.remove('range-start','range-end'))};document.querySelector<HTMLButtonElement>('#apply')!.onclick=()=>show(false)})
  await page.getByRole('button',{name:'Hoje',exact:true}).click();await expect(page.getByRole('button',{name:'Hoje',exact:true})).toHaveAttribute('aria-pressed','true')
  await page.getByRole('button',{name:'Período personalizado'}).click();await page.getByRole('button',{name:'Mês anterior',exact:true}).last().click();await expect(page.locator('.rdp-caption_label').first()).toContainText('julho')
  await page.getByRole('button',{name:'Próximo mês'}).click();await expect(page.locator('.rdp-caption_label').first()).toContainText('setembro')
  await page.locator('.rdp-day_button').nth(10).click();await page.locator('.rdp-day_button').nth(16).click();await page.getByRole('button',{name:'Limpar'}).click();await expect(page.locator('.period-inputs input').first()).toHaveValue('')
  await page.locator('.period-inputs input').first().fill('01/08/2026');await page.locator('.period-inputs input').last().fill('20/08/2026')
  const audit=await page.evaluate(()=>{const panel=document.querySelector<HTMLElement>('.period-popover')!,rect=panel.getBoundingClientRect(),controls=[...panel.querySelectorAll<HTMLElement>('.period-presets button,.period-inputs input,.period-actions button,.period-mobile-head button')].filter(node=>{const box=node.getBoundingClientRect();return box.width>0&&box.height>0}),days=[...panel.querySelectorAll<HTMLElement>('.rdp-day_button')];return{overflow:document.documentElement.scrollWidth-document.documentElement.clientWidth,panelInside:rect.left>=0&&rect.right<=innerWidth+1,centerDelta:innerWidth<=767?Math.abs((rect.left+rect.right)/2-innerWidth/2):0,weekdays:[...panel.querySelectorAll('.rdp-month_grid')].map(grid=>grid.querySelectorAll('.rdp-weekday').length),daysVisible:days.every(node=>{const box=node.getBoundingClientRect();return box.left>=rect.left&&box.right<=rect.right+1&&box.width>0}),small:controls.filter(node=>node.getBoundingClientRect().height<(innerWidth<=767?40:36)).map(node=>node.textContent),clipped:controls.filter(node=>node.scrollWidth>node.clientWidth+2).map(node=>node.textContent)}})
  expect(audit.overflow).toBe(0);expect(audit.panelInside).toBe(true);expect(audit.centerDelta).toBeLessThanOrEqual(1);expect(audit.weekdays.every(count=>count===7)).toBe(true);expect(audit.daysVisible).toBe(true);expect(audit.small).toEqual([]);expect(audit.clipped).toEqual([])
  await page.evaluate(()=>{scrollTo(0,0);const calendar=document.querySelector<HTMLElement>('.period-calendar');if(calendar)calendar.scrollTop=0});await page.screenshot({path:`tests/screenshots/period-filter-${width}.png`,fullPage:false})
  await page.getByRole('button',{name:'Aplicar'}).click();await expect(page.locator('.period-popover')).toBeHidden();await page.locator('#trigger').click();await expect(page.locator('.period-popover')).toBeVisible();if(width<=767){await page.getByRole('button',{name:'Fechar filtro'}).click();await expect(page.locator('.period-popover')).toBeHidden();await page.locator('#trigger').click()}
})
