import{expect,test}from'@playwright/test'

const markup=`<main class="shipment-document-page"><article class="shipment-document"><header class="shipment-document-header"><div class="shipment-document-brand"><strong>RUAH</strong><span>PARFUMS</span></div><div><span>DOCUMENTO OPERACIONAL</span><h1>NOTA DE ENVIO</h1><dl><div><dt>Referência</dt><dd>ENVIO 12D3F0A6</dd></div><div><dt>Preparação / impressão</dt><dd>23/08/2026</dd></div><div><dt>Status</dt><dd>Aguardando aprovação da cliente</dd></div></dl></div></header><section class="shipment-document-destination"><h2>Cliente e destino</h2><div class="shipment-document-grid"><div><small>CLIENTE</small><strong>Ilde mae</strong><span>(11) 99999-0000</span></div><div><small>DESTINATÁRIO</small><strong>Ilde mae</strong></div><address><small>ENDEREÇO DO ENVIO</small><strong>Rua correta, 199</strong><span>Bairro: Centro</span><span>Centro · São Paulo / SP</span><span>CEP 05616-080</span></address></div></section><section class="shipment-document-logistics"><h2>Status e logística</h2><dl><div><dt>Status</dt><dd>Aguardando aprovação da cliente</dd></div><div><dt>Transportadora</dt><dd>loggi</dd></div><div><dt>Serviço</dt><dd>LOGGI</dd></div><div><dt>Frete</dt><dd>R$ 9,36</dd></div><div><dt>Rastreio</dt><dd>Ainda não emitido</dd></div></dl></section><section class="shipment-document-items"><h2>Itens para conferência</h2><table><thead><tr><th>Conferência</th><th>Perfume</th><th>ML</th></tr></thead><tbody><tr><td><span class="shipment-check-box"></span></td><td>ambre crush</td><td>100 ml</td></tr></tbody></table></section><section class="shipment-document-summary"><div><h2>Resumo</h2><dl><div><dt>Itens</dt><dd>1</dd></div><div><dt>Total</dt><dd>100 ml</dd></div><div><dt>Frete</dt><dd>R$ 9,36</dd></div></dl></div><div><h2>Conferência final</h2><ul><li><span class="shipment-check-box"></span>Todos os perfumes conferidos</li><li><span class="shipment-check-box"></span>Embalagem conferida</li></ul></div></section></article></main>`

test('nota P0 realista cabe em uma A4 sem overlap nem segunda página',async({page})=>{
 await page.goto('/login');await page.setContent(markup);await page.addStyleTag({path:'src/pages/ShipmentPrintPage.css'});await page.emulateMedia({media:'print'})
 const boxes=await page.locator('.shipment-document>header,.shipment-document>section').evaluateAll(nodes=>nodes.map(node=>{const box=node.getBoundingClientRect();return{top:box.top,bottom:box.bottom}}))
 for(let index=1;index<boxes.length;index++)expect(boxes[index].top).toBeGreaterThanOrEqual(boxes[index-1].bottom-1)
 expect(await page.locator('.shipment-document').evaluate(node=>node.getBoundingClientRect().height)).toBeLessThan(1040)
 expect(await page.locator('.shipment-document').innerText()).not.toContain('Julia')
})
