import { expect, test, type Page } from '@playwright/test'
import { readFileSync } from 'node:fs'

const css='src/pages/ShipmentPrintPage.css'
const item=(name:string)=>`<tr><td><span class="shipment-check-box"></span></td><td>${name}</td><td>10 ml</td></tr>`
const document=(items:string,freight=true,client='Maria de Lourdes Albuquerque')=>`<main class="shipment-document-page"><nav class="shipment-document-actions"><button>VOLTAR</button><button>IMPRIMIR NOTA DE ENVIO</button></nav><article class="shipment-document"><header class="shipment-document-header"><div class="shipment-document-brand"><strong>RUAH</strong><span>PARFUMS</span></div><div><span>DOCUMENTO OPERACIONAL</span><h1>NOTA DE ENVIO</h1><dl><div><dt>Referência</dt><dd>ENVIO 7AD91BE2</dd></div><div><dt>Preparação / impressão</dt><dd>22/08/2026</dd></div><div><dt>Status</dt><dd>Preparando envio</dd></div></dl></div></header><section class="shipment-document-client"><h2>Destinatário</h2><div><strong>${client}</strong><span>(11) 99999-9999</span></div><address><span>Rua das Flores, 10</span><span>Centro · São Paulo / SP</span><span>CEP 01234-567</span></address></section><section class="shipment-document-items"><h2>Itens para conferência</h2><table><thead><tr><th>Conferência</th><th>Perfume</th><th>ML</th></tr></thead><tbody>${items}</tbody></table></section><section class="shipment-document-summary"><div><h2>Resumo operacional</h2><dl><div><dt>Itens</dt><dd>1</dd></div><div><dt>Total</dt><dd>10 ml</dd></div>${freight?'<div><dt>Frete</dt><dd>R$ 25,90</dd></div>':''}<div><dt>Transportadora</dt><dd>Correios</dd></div></dl></div><div><h2>Conferência final</h2><ul><li><span class="shipment-check-box"></span>Todos os perfumes conferidos</li><li><span class="shipment-check-box"></span>Embalagem conferida</li><li><span class="shipment-check-box"></span>Etiqueta de transporte conferida</li><li><span class="shipment-check-box"></span>Pronto para postagem</li></ul></div></section><section class="shipment-document-notes"><h2>Observações do envio</h2><p>Manter caixa na vertical.</p></section><section class="shipment-document-signature"><div><span>Responsável pela preparação</span></div><div><span>Data / hora</span></div></section><footer><span>RUAH Parfums</span><small>Documento operacional para separação e conferência. Não é documento fiscal.</small></footer></article></main>`
async function setup(page:Page,markup:string){await page.goto('/login');await page.setContent(`<aside class="sidebar">CRM</aside><header class="topbar">Admin</header>${markup}`);await page.addStyleTag({path:css})}

test.describe('nota de envio operacional',()=>{
  test('1 item e nome grande permanecem legíveis',async({page})=>{await setup(page,document(item('Oud for Greatness Edição Especial Extraordinariamente Longa')));await expect(page.locator('.shipment-document')).toBeVisible();expect(await page.locator('.shipment-document').evaluate(el=>el.scrollWidth<=el.clientWidth+1)).toBe(true)})
  test('2 e 10 itens preservam exatamente as linhas do snapshot',async({page})=>{for(const count of [2,10]){await setup(page,document(Array.from({length:count},(_,i)=>item(`Perfume ${i+1}`)).join('')));expect(await page.locator('tbody tr').count()).toBe(count)}})
  test('vários itens podem paginar somente entre linhas',async({page})=>{await setup(page,document(Array.from({length:35},(_,i)=>item(`Perfume ${i+1}`)).join('')));expect(await page.locator('tbody tr').count()).toBe(35);expect(await page.locator('tbody tr').first().evaluate(el=>getComputedStyle(el).breakInside)).toBe('avoid')})
  test('frete aparece apenas quando existe',async({page})=>{await setup(page,document(item('Balenciaga'),false));await expect(page.getByText('Frete')).toHaveCount(0);await setup(page,document(item('Balenciaga'),true));await expect(page.getByText('Frete')).toHaveCount(1)})
  test('tem conferência, observação e assinatura sem valores comerciais',async({page})=>{await setup(page,document(item('Balenciaga')));await expect(page.getByText('Todos os perfumes conferidos')).toBeVisible();await expect(page.getByText('Observações do envio')).toBeVisible();await expect(page.getByText('Responsável pela preparação')).toBeVisible();await expect(page.getByText('Valor')).toHaveCount(0);await expect(page.getByText('Subtotal')).toHaveCount(0)})
  test('print remove ações e não contém chrome do CRM',async({page})=>{await setup(page,document(item('Balenciaga')));await page.emulateMedia({media:'print'});await expect(page.locator('.shipment-document-actions')).toBeHidden();await expect(page.locator('.shipment-document')).toBeVisible();await expect(page.locator('.shipment-document .sidebar,.shipment-document .topbar')).toHaveCount(0)})
  test('não exibe UUID nem status bruto e usa português humano',async({page})=>{await setup(page,document(item('Balenciaga')));const text=await page.locator('.shipment-document').innerText();expect(text).not.toMatch(/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f-]{23}/i);expect(text).not.toMatch(/\b(shipping|reserved|allocation)\b/i);expect(text).toContain('NOTA DE ENVIO');expect(text).toContain('Não é documento fiscal')})
  test('implementação real é A4, deriva só de shipment_items e não imprime UUID ou financeiro',()=>{const source=readFileSync('src/pages/ShipmentPrintPage.tsx','utf8'),styles=readFileSync(css,'utf8');expect(source).toContain('@page { size: A4 portrait; margin: 12mm; }');expect(source).toContain('shipment?.shipment_items');expect(source).not.toContain("from('sales')");expect(source).not.toContain('shipmentControlDeepLink');expect(source).not.toContain('<BarcodeImage');expect(source).not.toContain('item.sales?.amount');expect(source).toContain('IMPRIMIR NOTA DE ENVIO');expect(styles).not.toContain('min-height:270mm');expect(styles).toContain('page-break-inside:avoid')})
})
