import { expect, test, type Page } from '@playwright/test'
import { readFileSync } from 'node:fs'

const css='src/pages/ShipmentPrintPage.css'
const item=(name:string,value='R$ 1.250,00')=>`<tr><td>${name}</td><td>Fracionado</td><td>10 ml</td><td>${value}</td></tr>`
const document=(items:string,freight=true,client='Maria de Lourdes Albuquerque')=>`<main class="shipment-document-page"><nav class="shipment-document-actions"><button>VOLTAR</button><button>IMPRIMIR</button></nav><article class="shipment-document"><header class="shipment-document-header"><div><strong>RUAH</strong><span>PARFUMS</span></div><div><span>DOCUMENTO OPERACIONAL</span><h1>Folha do envio</h1><dl><div><dt>Data</dt><dd>22/08/2026</dd></div><div><dt>Status</dt><dd>Preparando envio</dd></div></dl></div></header><section class="shipment-document-client"><h2>Cliente</h2><strong>${client}</strong><span>(11) 99999-9999</span><p>Rua das Flores · 10 · São Paulo · SP</p></section><section class="shipment-document-items"><h2>Itens</h2><table><thead><tr><th>Perfume</th><th>Tipo</th><th>ML</th><th>Valor</th></tr></thead><tbody>${items}</tbody></table></section><section class="shipment-document-bottom"><div class="shipment-document-control"><img class="qr-code-image"><div><svg class="barcode-image"></svg><span>Bipe para abrir este envio no CRM</span></div></div><dl class="shipment-document-totals"><div><dt>Perfumes</dt><dd>1</dd></div><div><dt>Total em ml</dt><dd>10 ml</dd></div><div><dt>Subtotal</dt><dd>R$ 1.250,00</dd></div>${freight?'<div><dt>Frete</dt><dd>R$ 25,90</dd></div>':''}<div class="total"><dt>Total</dt><dd>R$ 1.275,90</dd></div></dl></section><footer><span>RUAH Parfums</span><small>Documento operacional para separação e conferência. Não é documento fiscal.</small></footer></article></main>`
async function setup(page:Page,markup:string){await page.goto('/login');await page.setContent(`<aside class="sidebar">CRM</aside><header class="topbar">Admin</header>${markup}`);await page.addStyleTag({path:css})}

test.describe('folha do envio operacional',()=>{
  test('1 item, nomes e valores grandes permanecem legíveis',async({page})=>{await setup(page,document(item('Oud for Greatness Edição Especial Extraordinariamente Longa','R$ 987.654,32')));await expect(page.locator('.shipment-document')).toBeVisible();expect(await page.locator('.shipment-document').evaluate(el=>el.scrollWidth<=el.clientWidth+1)).toBe(true)})
  test('vários itens podem paginar somente entre linhas',async({page})=>{await setup(page,document(Array.from({length:35},(_,i)=>item(`Perfume ${i+1}`)).join('')));expect(await page.locator('tbody tr').count()).toBe(35);const breakInside=await page.locator('tbody tr').first().evaluate(el=>getComputedStyle(el).breakInside);expect(breakInside).toBe('avoid')})
  test('frete aparece apenas quando existe',async({page})=>{await setup(page,document(item('Balenciaga'),false));await expect(page.getByText('Frete')).toHaveCount(0);await setup(page,document(item('Balenciaga'),true));await expect(page.getByText('Frete')).toHaveCount(1)})
  test('print remove ações e não contém chrome do CRM',async({page})=>{await setup(page,document(item('Balenciaga')));await page.emulateMedia({media:'print'});await expect(page.locator('.shipment-document-actions')).toBeHidden();await expect(page.locator('.shipment-document')).toBeVisible();await expect(page.locator('.shipment-document .sidebar,.shipment-document .topbar')).toHaveCount(0)})
  test('não exibe UUID nem status bruto e usa português humano',async({page})=>{await setup(page,document(item('Balenciaga')));const text=await page.locator('.shipment-document').innerText();expect(text).not.toMatch(/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f-]{23}/i);expect(text).not.toMatch(/\b(shipping|reserved|allocation)\b/i);expect(text).toContain('Documento operacional');expect(text).toContain('Não é documento fiscal')})
  test('fonte real preserva A4, QR/Code128 sem UUID visível e ações claras',()=>{const source=readFileSync('src/pages/ShipmentPrintPage.tsx','utf8'),styles=readFileSync(css,'utf8');expect(source).toContain('@page { size: A4; margin: 12mm; }');expect(source).toContain('displayValue={false}');expect(source).toContain('IMPRIMIR');expect(source).toContain('VOLTAR');expect(styles).toContain('break-inside:avoid')})
})
