// LEGADO ISOLADO — não faz parte do Core do Mugô One (ver ../README.md).
// Fora da navegação/roteamento ativos desde o hotfix "zero split".
import{useEffect,useState}from'react'
import{Barcode,CheckCircle2,Printer,ScanLine}from'lucide-react'
import{QrCameraScanner}from'../../../components/bottles/QrCameraScanner'
import{PrimaryButton,SecondaryButton}from'../../../components/ui'
import{PreparationBottle,PreparationCandidate,PreparationPerfume,confirmPreparationBatch,createPreparationBatch,fetchPreparationBottles,fetchPreparationCandidates,fetchPreparationPerfumes,identifyPreparationBatch,printPerfumeLabel}from'../../../lib/preparation'
import'./PreparationPage.css'

type DraftItem=PreparationCandidate&{selected:boolean;prepare_ml:number;source_bottle_id:string}
export function PreparationPage(){
 const initialPerfumeId=new URLSearchParams(location.search).get('perfume')??''
 const[perfumes,setPerfumes]=useState<PreparationPerfume[]>([]),[perfumeId,setPerfumeIdState]=useState(initialPerfumeId),[items,setItems]=useState<DraftItem[]>([]),[bottles,setBottles]=useState<PreparationBottle[]>([]),[batchId,setBatchId]=useState(''),[identified,setIdentified]=useState(false),[scanner,setScanner]=useState(false),[manual,setManual]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[done,setDone]=useState(false)
 const setPerfumeId=async(id:string)=>{setPerfumeIdState(id);setItems([]);setBottles([]);if(!id)return;try{const[rows,source]=await Promise.all([fetchPreparationCandidates(id),fetchPreparationBottles(id)]);setBottles(source);setItems(rows.map(row=>({...row,selected:true,prepare_ml:Number(row.remaining_ml),source_bottle_id:source.length===1?source[0].id:''})))}catch(e){setMessage(e instanceof Error?e.message:'Não foi possível carregar as custódias.')}}
 useEffect(()=>{fetchPreparationPerfumes().then(setPerfumes).catch(e=>setMessage(e.message));if(initialPerfumeId)Promise.all([fetchPreparationCandidates(initialPerfumeId),fetchPreparationBottles(initialPerfumeId)]).then(([rows,source])=>{setBottles(source);setItems(rows.map(row=>({...row,selected:true,prepare_ml:Number(row.remaining_ml),source_bottle_id:source.length===1?source[0].id:''})))}).catch(e=>setMessage(e instanceof Error?e.message:'Não foi possível carregar as custódias.'))},[]) // eslint-disable-line react-hooks/exhaustive-deps
 const perfume=perfumes.find(row=>row.id===perfumeId),selected=items.filter(item=>item.selected),splitItems=items.filter(item=>item.sale_type==='SPLIT'),apcItems=items.filter(item=>item.sale_type==='APC')
 const totalSplit=selected.filter(item=>item.sale_type==='SPLIT').reduce((sum,item)=>sum+Number(item.prepare_ml||0),0)
 const invalid=selected.some(item=>item.prepare_ml<=0||item.prepare_ml>item.remaining_ml||(item.bottle_tracking_status==='active'&&!item.source_bottle_id))
 const patch=(index:number,next:Partial<DraftItem>)=>setItems(current=>current.map((row,i)=>i===index?{...row,...next}:row))
 const start=async()=>{if(!perfume||!selected.length||invalid)return;setBusy(true);setMessage('');try{setBatchId(await createPreparationBatch(perfume.id,selected.map(item=>({allocation_id:item.allocation_id,quantity_ml:item.prepare_ml,source_bottle_id:item.source_bottle_id||null}))))}catch(e){setMessage(e instanceof Error?e.message:'Não foi possível iniciar.')}finally{setBusy(false)}}
 const scan=async(code:string)=>{if(!batchId)return;setBusy(true);setMessage('');try{const result=await identifyPreparationBatch(batchId,code);if(!result.ok){setMessage(result.reason==='wrong_perfume'?`Perfume incorreto. Esperado: ${result.expected}. Bipado: ${result.scanned}.`:'Código de perfume não encontrado.');return}setIdentified(true);setScanner(false);setMessage(`✓ ${result.perfume} identificado`)}catch(e){setMessage(e instanceof Error?e.message:'Não foi possível identificar.')}finally{setBusy(false)}}
 const confirm=async()=>{setBusy(true);try{const result=await confirmPreparationBatch(batchId);setDone(true);setMessage(result.already_confirmed?(result.message??'Esta preparação já foi concluída.'):`✓ Preparação concluída para ${result.item_count} clientes.`)}catch(e){setMessage(e instanceof Error?e.message:'Não foi possível confirmar.')}finally{setBusy(false)}}
 const card=(item:DraftItem)=>{const index=items.indexOf(item),apc=item.sale_type==='APC';return <article key={item.allocation_id} data-sale-type={apc?'APC':'SPLIT'}><label><input type="checkbox" checked={item.selected} onChange={e=>patch(index,{selected:e.target.checked})}/><span><small>{apc?'APC':'SPLIT'}</small><strong>{item.client_name}</strong></span></label><span>{apc?'Perfume inteiro · não entra no total SPLIT':`${item.remaining_ml} ml ainda aguardando`}</span><label>{apc?'Quantidade registrada':'Quantidade a preparar'}<input type="number" min="0.001" max={item.remaining_ml} step="0.001" value={item.prepare_ml} onChange={e=>patch(index,{prepare_ml:Number(e.target.value)})}/></label>{item.bottle_tracking_status==='active'&&<label>Frasco de origem<select value={item.source_bottle_id} onChange={e=>patch(index,{source_bottle_id:e.target.value})}><option value="">Escolha o frasco…</option>{bottles.map(b=><option key={b.id} value={b.id}>{b.bottle_code} · {b.bottle_label} · {b.physical_ml} ml</option>)}</select></label>}</article>}
 if(done)return <div className="page preparation-page"><section className="preparation-success"><CheckCircle2/><h1>PREPARAÇÃO CONCLUÍDA</h1><strong>TOTAL SPLIT: {totalSplit} ml</strong><span>{selected.filter(item=>item.sale_type==='SPLIT').length} SPLIT · {selected.filter(item=>item.sale_type==='APC').length} APC</span><p>Os itens preparados já seguem a regra de disponibilidade da Minha RUAH.</p><PrimaryButton onClick={()=>location.reload()}>NOVA PREPARAÇÃO</PrimaryButton></section></div>
 return <div className="page preparation-page"><header><span>ESTOQUE</span><h1>Preparação</h1><p>Prepare os perfumes das clientes e confirme com o código único do perfume.</p></header>{message&&<div className="notice">{message}</div>}
 {!batchId?<><label className="field"><span>Perfume</span><select value={perfumeId} onChange={e=>setPerfumeId(e.target.value)}><option value="">Selecione…</option>{perfumes.map(p=><option value={p.id} key={p.id}>{p.full_name_raw} · {p.operational_code}</option>)}</select></label>{perfume&&<section className="preparation-identity"><div><span>IDENTIFICAÇÃO OPERACIONAL</span><strong>{perfume.full_name_raw}</strong><code>{perfume.operational_code}</code></div><SecondaryButton icon={<Printer/>} onClick={()=>printPerfumeLabel(perfume)}>IMPRIMIR ETIQUETA DO PERFUME</SecondaryButton></section>}<section><h2>A PREPARAR</h2>{splitItems.length>0&&<><h3>SPLIT</h3><div className="preparation-items">{splitItems.map(card)}</div></>}{apcItems.length>0&&<><h3>APC</h3><p>APC é tratado como perfume inteiro e não compõe o total de fracionamento.</p><div className="preparation-items">{apcItems.map(card)}</div></>}{items.length===0&&perfume&&<p>Nenhuma custódia aguardando preparação.</p>}</section><footer><strong>TOTAL SPLIT: {totalSplit} ml · {selected.filter(item=>item.sale_type==='APC').length} APC</strong><PrimaryButton loading={busy} disabled={!selected.length||invalid} onClick={start}>INICIAR PREPARAÇÃO</PrimaryButton></footer></>:<section className="preparation-scan"><Barcode/><h2>{perfume?.full_name_raw}</h2><strong>TOTAL SPLIT: {totalSplit} ml · {selected.filter(item=>item.sale_type==='APC').length} APC</strong>{!identified?<><p>Depois de concluir o preparo físico, bipe novamente o código do perfume.</p><PrimaryButton icon={<ScanLine/>} onClick={()=>setScanner(true)}>BIPAR PERFUME PARA CONFERIR</PrimaryButton><form onSubmit={e=>{e.preventDefault();void scan(manual)}}><input value={manual} onChange={e=>setManual(e.target.value)} placeholder="RUAH-P000123"/><button>VALIDAR CÓDIGO</button></form>{scanner&&<QrCameraScanner onScan={scan} onClose={()=>setScanner(false)}/>}</>:<><CheckCircle2/><h3>CONFIRMAR PREPARAÇÃO?</h3>{selected.map(item=><span key={item.allocation_id}>{item.client_name} — {item.sale_type==='APC'?'APC':`${item.prepare_ml} ml`}</span>)}<div><SecondaryButton onClick={()=>setIdentified(false)}>CANCELAR</SecondaryButton><PrimaryButton loading={busy} onClick={confirm}>CONFIRMAR PREPARAÇÃO</PrimaryButton></div></>}</section>}</div>
}
