import { useEffect, useState } from 'react'
import { AlertTriangle, Boxes, Check, Clock3, FileText, Search, ShoppingBag, X } from 'lucide-react'
import { brl, shortDate, integer } from '../lib/format'
import { ClientModal } from '../components/RecordModals'
import { operationalLabel, statusLabel } from '../lib/presentation'
import { createDraftShipment, fetchClient360 } from '../lib/records'
import { Metric } from '../components/shared/Metric'

export function ClientDetailsPage({clientId}:{clientId:string}) {
  const [data,setData]=useState<Awaited<ReturnType<typeof fetchClient360>>|null>(null)
  const [selected,setSelected]=useState<string[]>([]),[error,setError]=useState(''),[preparing,setPreparing]=useState(false),[editing,setEditing]=useState(false)
  const [historySearch,setHistorySearch]=useState(''),[historyPayment,setHistoryPayment]=useState(''),[historyType,setHistoryType]=useState(''),[historyShipping,setHistoryShipping]=useState(''),[historyStart,setHistoryStart]=useState(''),[historyEnd,setHistoryEnd]=useState('')
  const [purchase,setPurchase]=useState<Record<string,unknown>|null>(null)
  useEffect(()=>{fetchClient360(clientId).then(setData).catch((reason)=>setError(reason instanceof Error?reason.message:'Não foi possível carregar o cliente.'))},[clientId])
  if(error)return <div className="page"><div className="notice"><AlertTriangle/><span>{error}</span></div></div>
  if(!data)return <div className="page"><div className="empty card"><h3>Carregando Cliente 360°…</h3></div></div>
  const {client}=data.profile,commercial=data.profile.commercial,waiting=data.profile.waiting
  const visibleHistory=data.history.filter((sale)=>
    (!historySearch||String(sale.perfume_name_raw??'').toLowerCase().includes(historySearch.toLowerCase()))&&
    (!historyPayment||sale.payment_status===historyPayment)&&(!historyType||sale.sale_type===historyType)&&
    (!historyShipping||(historyShipping==='shipped'?Boolean(sale.shipped_at):!sale.shipped_at))&&
    (!historyStart||String(sale.sale_date??'')>=historyStart)&&(!historyEnd||String(sale.sale_date??'')<=historyEnd))
  const editInitial={name:client.name,phone:client.phone??'',whatsappPhone:client.whatsapp_phone??'',email:client.email??'',instagram:client.instagram??'',cpf:client.cpf??'',cnpj:client.cnpj??'',birthDate:client.birth_date??'',postalCode:client.postal_code??'',address:client.address_line??'',addressNumber:client.address_number??'',complement:client.complement??'',district:client.district??'',city:client.city??'',state:client.state??'',notes:client.notes??'',status:client.status}
  const prepare=async()=>{if(!selected.length)return;setPreparing(true);setError('');try{const shipmentId=await createDraftShipment(clientId,selected);setSelected([]);const refreshed=await fetchClient360(clientId);setData(refreshed);alert(`Envio preparado: ${shipmentId.slice(0,8)}`)}catch(reason){setError(reason instanceof Error?reason.message:'Não foi possível preparar o envio.')}finally{setPreparing(false)}}
  return <div className="page client-360">
    {purchase&&<div className="modal-layer"><button className="modal-scrim" aria-label="Fechar" onClick={()=>setPurchase(null)}/><div className="modal-panel"><div className="modal-title"><div><span>DETALHES DA COMPRA</span><h2>{String(purchase.perfume_name_raw??'Venda')}</h2></div><button onClick={()=>setPurchase(null)}><X/></button></div><div className="client-panel"><dl><dt>Data</dt><dd>{purchase.sale_date?shortDate(String(purchase.sale_date)):'—'}</dd><dt>Valor</dt><dd>{brl(Number(purchase.amount))}</dd><dt>Pagamento</dt><dd>{statusLabel[String(purchase.payment_status)]}</dd><dt>Prazo</dt><dd>{purchase.shipping_deadline_date?shortDate(String(purchase.shipping_deadline_date)):String(purchase.shipping_deadline_raw??'—')}</dd><dt>Envio</dt><dd>{purchase.shipped_at?shortDate(String(purchase.shipped_at)):'—'}</dd><dt>Observação</dt><dd>{String(purchase.notes??'—')}</dd></dl></div></div></div>}
    {editing&&<ClientModal clientId={clientId} initial={editInitial} close={()=>setEditing(false)} onSaved={()=>fetchClient360(clientId).then(setData)}/>}
    <button className="back-link" onClick={()=>{history.pushState({},'','/clientes');dispatchEvent(new PopStateEvent('popstate'))}}>← Voltar para clientes</button>
    <div className="page-lead"><div><span className="eyebrow">CLIENTE 360°</span><h2>{client.name}</h2><p>{client.phone||'Sem telefone'} · {client.email||'Sem e-mail'}</p></div><div className="page-actions"><button onClick={()=>setEditing(true)}>Editar dados</button><span className="badge paid">{client.status}</span></div></div>
    <section className="metrics"><Metric label="Total comprado" value={brl(Number(commercial.total_purchased))} detail={`${integer(Number(commercial.purchases))} compras`} icon={ShoppingBag}/><Metric label="Valor pago" value={brl(Number(commercial.paid))} detail={`Ticket médio ${brl(Number(commercial.average_ticket))}`} icon={Check}/><Metric label="Aguardando pagamento" value={brl(Number(commercial.pending))} detail={`${Number(commercial.total_ml).toLocaleString('pt-BR')} ML comprados`} icon={Clock3}/><Metric label="Crédito" value={brl(Number(commercial.credit))} detail="Crédito registrado nas vendas" icon={FileText}/><Metric label="Aguardando envio" value={`${Number(waiting.waiting_ml).toLocaleString('pt-BR')} ML`} detail={`${integer(Number(waiting.waiting_products))} allocations reservadas`} icon={Boxes}/></section>
    <section className="client-grid"><article className="card client-panel"><h3>Dados cadastrais</h3><dl><dt>Nome</dt><dd>{client.name}</dd><dt>Telefone</dt><dd>{client.phone||'—'}</dd><dt>WhatsApp</dt><dd>{client.whatsapp_phone||'—'}</dd><dt>E-mail</dt><dd>{client.email||'—'}</dd><dt>CPF</dt><dd>{client.cpf||'—'}</dd><dt>Instagram</dt><dd>{client.instagram||'—'}</dd><dt>Data de nascimento</dt><dd>{client.birth_date?shortDate(client.birth_date):'—'}</dd><dt>CEP</dt><dd>{client.postal_code||'—'}</dd><dt>Endereço</dt><dd>{client.address_line||'—'}</dd><dt>Número</dt><dd>{client.address_number||'—'}</dd><dt>Complemento</dt><dd>{client.complement||'—'}</dd><dt>Bairro</dt><dd>{client.district||'—'}</dd><dt>Cidade</dt><dd>{client.city||'—'}</dd><dt>UF</dt><dd>{client.state||'—'}</dd><dt>Observações</dt><dd>{client.notes||'—'}</dd></dl></article>
      <article className="card client-panel"><h3>Resumo comercial</h3><dl><dt>Total comprado</dt><dd>{brl(Number(commercial.total_purchased))}</dd><dt>Quantidade de compras</dt><dd>{integer(Number(commercial.purchases))}</dd><dt>Ticket médio</dt><dd>{brl(Number(commercial.average_ticket))}</dd><dt>Total pago</dt><dd>{brl(Number(commercial.paid))}</dd><dt>Total pendente</dt><dd>{brl(Number(commercial.pending))}</dd><dt>Crédito</dt><dd>{brl(Number(commercial.credit))}</dd><dt>Total ML</dt><dd>{Number(commercial.total_ml).toLocaleString('pt-BR')} ML</dd><dt>Primeira compra</dt><dd>{commercial.first_purchase?shortDate(commercial.first_purchase):'—'}</dd><dt>Última compra</dt><dd>{commercial.last_purchase?shortDate(commercial.last_purchase):'—'}</dd><dt>Perfume mais comprado</dt><dd>{commercial.top_perfume||'—'}</dd></dl></article></section>
    {error&&<div className="notice"><AlertTriangle/><span>{error}</span></div>}
    <div className="card clients-table"><div className="clients-caption"><div><strong>Produtos aguardando envio</strong><span>Selecione várias compras para um único Shipment</span></div><button className="primary" disabled={!selected.length||preparing} onClick={prepare}>{preparing?'Preparando…':`Preparar envio (${selected.length})`}</button></div><div className="table-wrap"><table><thead><tr><th></th><th>Venda</th><th>Perfume</th><th>Tipo</th><th>ML</th><th>Valor</th><th>Origem</th><th>Guardado há</th></tr></thead><tbody>{data.waiting.map((item)=><tr key={item.allocation_id}><td><input type="checkbox" checked={selected.includes(item.allocation_id)} onChange={(event)=>setSelected((current)=>event.target.checked?[...current,item.allocation_id]:current.filter((id)=>id!==item.allocation_id))}/></td><td>{shortDate(item.sale_date)}</td><td><strong>{item.perfume}</strong></td><td>{item.sale_type}</td><td>{Number(item.quantity_ml).toLocaleString('pt-BR')} ML</td><td>{brl(Number(item.amount))}</td><td><span className={`badge ${item.stock_managed?'paid':'pending'}`}>{item.stock_managed?'ESTOQUE OPERACIONAL':'CONFERIDO MANUALMENTE'}</span>{item.storage_location&&<small>{item.storage_location}</small>}</td><td>{item.days_waiting} dias</td></tr>)}</tbody></table>{data.waiting.length===0&&<div className="inline-empty">Nenhum produto alocado aguardando envio.</div>}</div></div>
    <div className="card clients-table"><div className="clients-caption"><strong>Histórico completo de compras</strong><span>{integer(visibleHistory.length)} de {integer(data.history.length)} registros</span></div><div className="toolbar history-toolbar"><div className="search"><Search/><input value={historySearch} onChange={(event)=>setHistorySearch(event.target.value)} placeholder="Filtrar perfume…"/></div><input type="date" aria-label="Início" value={historyStart} onChange={(event)=>setHistoryStart(event.target.value)}/><input type="date" aria-label="Fim" value={historyEnd} onChange={(event)=>setHistoryEnd(event.target.value)}/><select value={historyPayment} onChange={(event)=>setHistoryPayment(event.target.value)}><option value="">Todos os pagamentos</option><option value="paid">Pago</option><option value="pending">Aguardando</option><option value="cancelled">Cancelado</option><option value="unknown">Revisão</option></select><select value={historyType} onChange={(event)=>setHistoryType(event.target.value)}><option value="">APC e SPLIT</option><option>APC</option><option>SPLIT</option></select><select value={historyShipping} onChange={(event)=>setHistoryShipping(event.target.value)}><option value="">Enviado e guardado</option><option value="shipped">Enviado</option><option value="waiting">Não enviado</option></select></div><div className="table-wrap"><table><thead><tr><th>Data</th><th>Perfume</th><th>Tipo</th><th>ML</th><th>Valor</th><th>Pagamento</th><th>Forma</th><th>Pago em</th><th>Origem</th><th>Envio</th><th>Rastreio</th></tr></thead><tbody>{visibleHistory.map((sale)=>{const shipment=(sale.shipment_items as {shipments?:{status?:string;tracking_code?:string}}[]|undefined)?.[0]?.shipments;return <tr key={String(sale.id)}><td>{sale.sale_date?shortDate(String(sale.sale_date)):'—'}</td><td><strong>{String(sale.perfume_name_raw??'—')}</strong></td><td>{String(sale.sale_type??'—')}</td><td>{sale.volume_ml===null?'—':`${Number(sale.volume_ml).toLocaleString('pt-BR')} ML`}</td><td>{brl(Number(sale.amount))}</td><td><span className={`badge ${sale.payment_status}`}>{statusLabel[String(sale.payment_status)]}</span></td><td>{String(sale.payment_method??'—')}</td><td>{sale.paid_at?shortDate(String(sale.paid_at)):'—'}</td><td>{sale.source==='spreadsheet'?'Planilha':'Manual'}</td><td>{shipment?.status?operationalLabel(shipment.status):(sale.shipped_at?shortDate(String(sale.shipped_at)):'Sem registro')}</td><td>{shipment?.tracking_code??'—'}</td></tr>})}</tbody></table></div></div>
    <div className="card clients-table"><div className="clients-caption"><strong>Logística das compras</strong><span>Histórico legado; não representa allocations operacionais.</span></div><div className="table-wrap"><table><thead><tr><th>Compra</th><th>Perfume</th><th>Prazo previsto</th><th>Data de envio</th><th>Status histórico</th><th>Dias até envio</th><th>Prazo</th><th>Observação</th><th>Ação</th></tr></thead><tbody>{visibleHistory.map((sale)=>{const days=sale.sale_date&&sale.shipped_at?Math.round((new Date(String(sale.shipped_at)).valueOf()-new Date(String(sale.sale_date)).valueOf())/86400000):null,deadline=sale.shipping_deadline_date?String(sale.shipping_deadline_date):null;return <tr key={`log-${String(sale.id)}`}><td>{sale.sale_date?shortDate(String(sale.sale_date)):'—'}</td><td><strong>{String(sale.perfume_name_raw??'—')}</strong></td><td>{deadline?shortDate(deadline):String(sale.shipping_deadline_raw??'—')}</td><td>{sale.shipped_at?shortDate(String(sale.shipped_at)):'—'}</td><td>{String(sale.shipping_operational_status??(sale.shipped_at?'Enviado':'Sem status'))}</td><td>{days===null?'—':`${days} dias`}</td><td>{deadline&&sale.shipped_at?(String(sale.shipped_at)<=deadline?'Dentro do prazo':'Atrasado'):'—'}</td><td>{String(sale.notes??'—')}</td><td><button onClick={()=>setPurchase(sale as Record<string,unknown>)}>Ver venda</button></td></tr>})}</tbody></table></div></div>
    <div className="card clients-table"><div className="clients-caption"><strong>Envios da nova operação</strong><span>Várias compras podem compartilhar uma única etiqueta.</span></div><div className="table-wrap"><table><thead><tr><th>Criado</th><th>Compras juntas</th><th>Status</th><th>Transportadora</th><th>Serviço</th><th>Frete</th><th>Rastreio</th><th>Postado</th><th>Entregue</th></tr></thead><tbody>{data.shipments.map((shipment)=>{const items=shipment.shipment_items as unknown[]|undefined;return <tr key={String(shipment.id)}><td>{new Date(String(shipment.created_at)).toLocaleDateString('pt-BR')}</td><td>{integer(items?.length??0)}</td><td>{operationalLabel(shipment.status)}</td><td>{String(shipment.carrier??'—')}</td><td>{String(shipment.service??'—')}</td><td>{shipment.shipping_price?brl(Number(shipment.shipping_price)):'—'}</td><td>{String(shipment.tracking_code??'—')}</td><td>{shipment.posted_at?new Date(String(shipment.posted_at)).toLocaleDateString('pt-BR'):'—'}</td><td>{shipment.delivered_at?new Date(String(shipment.delivered_at)).toLocaleDateString('pt-BR'):'—'}</td></tr>})}</tbody></table>{data.shipments.length===0&&<div className="inline-empty">Nenhum envio operacional para esta cliente.</div>}</div></div>
  </div>
}
