import {useEffect,useMemo,useState} from 'react'
import {AlertTriangle,ArrowDownRight,ArrowRight,ArrowUpRight,Boxes,CalendarDays,CircleDollarSign,Clock3,PackageCheck,RefreshCw,ShoppingBag,Sparkles,Truck,UsersRound} from 'lucide-react'
import {brl,integer} from '../lib/format'
import {buildDashboardNarrative,DashboardPeriodKey,fetchIntelligentDashboard,IntelligentDashboard,percentChange} from '../lib/intelligent-dashboard'
import {statusLabel} from '../lib/presentation'
import './Dashboard.css'

const periodOptions:[DashboardPeriodKey,string][]=[['last_hour','Última hora'],['today','Hoje'],['24h','Últimas 24h'],['7d','7 dias'],['30d','30 dias'],['custom','Personalizado']]
const profileTitle:Record<IntelligentDashboard['viewer']['profile'],string>={management:'Gestão',finance:'Financeiro',operations:'Operação',commercial:'Comercial',marketing:'Marketing',viewer:'Visão geral'}

export function Dashboard(){
  const [period,setPeriod]=useState<DashboardPeriodKey>('today'),[start,setStart]=useState(''),[end,setEnd]=useState('')
  const [data,setData]=useState<IntelligentDashboard|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[reload,setReload]=useState(0)
  useEffect(()=>{let active=true;if(period==='custom'&&(!start||!end))return;fetchIntelligentDashboard(period,start,end).then(x=>{if(active){setData(x);setError('')}}).catch(e=>{if(active)setError(e instanceof Error?e.message:'Não foi possível carregar o painel.')}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[period,start,end,reload])
  const metrics=data?.metrics,previous=data?.previous_metrics
  const top=useMemo(()=>[...(data?.top_products??[])],[data])
  return <div className="page intelligent-home">
    <header className="home-header"><div className="home-header-copy"><span className="home-kicker">VISÃO 360</span><h2>{data?`${profileTitle[data.viewer.profile]} em foco`:'Sua operação, agora'}</h2><p>Uma leitura clara do que aconteceu, do que exige atenção e da próxima ação.</p></div><div className="home-period"><CalendarDays size={17}/><select aria-label="Período" value={period} onChange={e=>{setLoading(true);setPeriod(e.target.value as DashboardPeriodKey)}}>{periodOptions.map(([key,label])=><option key={key} value={key}>{label}</option>)}</select>{period==='custom'&&<><input aria-label="Data inicial" type="date" value={start} onChange={e=>setStart(e.target.value)}/><input aria-label="Data final" type="date" value={end} min={start} onChange={e=>{setLoading(true);setEnd(e.target.value)}}/></>}<button aria-label="Atualizar painel" onClick={()=>{setLoading(true);setReload(x=>x+1)}}><RefreshCw size={16}/></button></div></header>
    {error&&<div className="home-error"><AlertTriangle/><span>{error}</span><button onClick={()=>{setLoading(true);setReload(x=>x+1)}}>Tentar novamente</button></div>}
    {loading&&!data?<DashboardSkeleton/>:data&&metrics&&previous&&<>
      <section className="home-summary"><div><div className="home-summary-label"><Sparkles/><span>LEITURA DO PERÍODO</span></div><p>{buildDashboardNarrative(data)}</p></div><small>Atualizado {new Date(data.generated_at).toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit',timeZone:data.timezone})}</small></section>
      <section className="home-metrics" aria-label="Indicadores do período">
        <Metric icon={ShoppingBag} label="Vendas" value={integer(metrics.sales_count)} change={percentChange(metrics.sales_count,Number(previous.sales_count))}/>
        {data.viewer.finance_allowed&&metrics.revenue!=null&&<Metric icon={CircleDollarSign} label="Receita" value={brl(metrics.revenue)} change={percentChange(metrics.revenue,Number(previous.revenue))}/>}
        <Metric icon={Boxes} label="ML vendidos" value={`${integer(metrics.ml_sold)} ML`} change={percentChange(metrics.ml_sold,Number(previous.ml_sold))}/>
        <Metric icon={PackageCheck} label="Perfumes únicos" value={integer(metrics.unique_perfumes)} detail={`${integer(metrics.items_sold)} itens`}/>
        <Metric icon={UsersRound} label="Compradores" value={integer(metrics.buyers)} detail={`${integer(metrics.new_buyers)} novos · ${integer(metrics.returning_buyers)} recorrentes`}/>
        {data.viewer.finance_allowed&&metrics.average_ticket!=null&&<Metric icon={ArrowUpRight} label="Ticket médio" value={brl(metrics.average_ticket)} change={percentChange(metrics.average_ticket,Number(previous.average_ticket))}/>}
      </section>
      <section className="home-day-strip"><Day label="Ontem" value={data.day_summary.yesterday} finance={data.viewer.finance_allowed}/><ArrowRight/><Day label="Hoje" value={data.day_summary.today} finance={data.viewer.finance_allowed}/><div className="home-pending"><span>Pendências agora</span><strong>{integer(data.operations.pending_collection)} cobranças · {integer(data.operations.shipments_open)} envios</strong></div></section>
      {(data.viewer.operations_allowed||data.viewer.management_allowed)&&<section className="home-section"><SectionHead eyebrow="PRIORIDADES" title="O que precisa de ação"/><div className="priority-grid"><Priority icon={PackageCheck} value={data.operations.awaiting_separation} label="Pagas aguardando separação" href="/falta-splitar"/><Priority icon={Boxes} value={data.operations.missing_allocations} label="Pagas sem reserva de estoque" href="/vendas?filtro=bloqueadas" critical/><Priority icon={Truck} value={data.operations.labels_pending} label="Etiquetas para emitir" href="/entregas"/><Priority icon={Clock3} value={data.operations.awaiting_tracking} label="Envios sem rastreio" href="/entregas"/></div></section>}
      <section className="home-two-columns"><div className="home-section"><SectionHead eyebrow="ALERTAS CENTRALIZADOS" title="Atenção operacional"/>{data.alerts.length?<div className="alert-list">{data.alerts.map((a,i)=><div className={`home-alert ${a.severity}`} key={`${a.type}-${i}`}><AlertTriangle/><div><strong>{a.title}</strong><p>{a.description}</p></div></div>)}</div>:<Empty text="Nenhum alerta operacional neste momento."/>}</div><div className="home-section"><SectionHead eyebrow="RANKING" title="Perfumes do período"/><ProductRanking rows={top} finance={data.viewer.finance_allowed}/></div></section>
      <section className="home-section"><SectionHead eyebrow="MOVIMENTO RECENTE" title="Últimas vendas"/><div className="recent-table-wrap"><table className="recent-table"><thead><tr><th>Cliente</th><th>Perfume</th><th>ML</th>{data.viewer.finance_allowed&&<th>Valor</th>}<th>Pagamento</th><th>Operação</th></tr></thead><tbody>{data.recent_sales.map(s=><tr key={s.id}><td><strong>{s.client_name}</strong><small>{new Date(s.created_at).toLocaleString('pt-BR',{timeZone:data.timezone,dateStyle:'short',timeStyle:'short'})}</small></td><td>{s.perfume_name}{s.bottle_identifier&&<small>{s.bottle_identifier}</small>}</td><td>{s.volume_ml==null?'—':`${integer(s.volume_ml)} ML`}</td>{data.viewer.finance_allowed&&<td>{s.amount==null?'—':brl(s.amount)}</td>}<td><Status value={s.payment_status}/></td><td>{s.shipment_status?<Status value={s.shipment_status}/>:s.separation_status?<Status value={s.separation_status}/>:<span className="status-pill neutral">Sem envio</span>}</td></tr>)}</tbody></table>{!data.recent_sales.length&&<Empty text="Nenhuma venda registrada neste período."/>}</div></section>
      {data.viewer.profile==='marketing'&&!data.recent_sales.length&&<section className="home-section"><Empty text="Ainda não há dados de campanha ou origem comercial suficientes para um painel de marketing confiável."/></section>}
      <p className="home-definition">Vendas e itens representam linhas comerciais, pois o modelo atual não possui uma entidade agregadora de pedido. Janelas horárias usam o momento de cadastro; demais períodos usam a data comercial.</p>
    </>}
  </div>
}

function Metric({icon:Icon,label,value,detail,change}:{icon:typeof ShoppingBag;label:string;value:string;detail?:string;change?:number|null}){return <article className="home-metric"><div><Icon/><span>{label}</span></div><strong>{value}</strong>{change==null?<small>{detail??'Sem base comparável'}</small>:<small className={change>=0?'positive':'negative'}>{change>=0?<ArrowUpRight/>:<ArrowDownRight/>}{Math.abs(change).toFixed(1)}% vs. período anterior</small>}</article>}
function Day({label,value,finance}:{label:string;value:{sales_count:number;revenue:number|null;ml:number};finance:boolean}){return <div><span>{label}</span><strong>{integer(value.sales_count)} vendas</strong><small>{finance&&value.revenue!=null?`${brl(value.revenue)} · `:''}{integer(value.ml)} ML</small></div>}
function Priority({icon:Icon,value,label,href,critical=false}:{icon:typeof Truck;value:number;label:string;href:string;critical?:boolean}){return <a className={`priority-card ${critical&&value?'critical':''}`} href={href}><Icon/><strong>{integer(value)}</strong><span>{label}</span><ArrowUpRight className="priority-arrow"/></a>}
function SectionHead({eyebrow,title}:{eyebrow:string;title:string}){return <div className="home-section-head"><span>{eyebrow}</span><h3>{title}</h3></div>}
function ProductRanking({rows,finance}:{rows:IntelligentDashboard['top_products'];finance:boolean}){const[sort,setSort]=useState<'ml'|'items'|'revenue'>('ml'),effectiveSort=finance?sort:sort==='revenue'?'ml':sort,ordered=[...rows].sort((a,b)=>Number(b[effectiveSort])-Number(a[effectiveSort]));return <><div className="ranking-sort"><button className={effectiveSort==='ml'?'active':''} onClick={()=>setSort('ml')}>ML</button><button className={effectiveSort==='items'?'active':''} onClick={()=>setSort('items')}>Itens</button>{finance&&<button className={effectiveSort==='revenue'?'active':''} onClick={()=>setSort('revenue')}>Receita</button>}</div><ol className="product-ranking">{ordered.slice(0,8).map((p,i)=><li key={p.perfume_id??p.name}><b>{i+1}</b><div><strong>{p.name}</strong><small>{integer(p.buyers)} compradores</small></div><span>{effectiveSort==='revenue'&&p.revenue!=null?brl(p.revenue):effectiveSort==='ml'?`${integer(p.ml)} ML`:integer(p.items)}</span></li>)}</ol>{!rows.length&&<Empty text="Sem perfumes vendidos no período."/>}</>}
function Status({value}:{value:string}){return <span className={`status-pill status-${value}`}>{statusLabel[value]??value.replaceAll('_',' ')}</span>}
function Empty({text}:{text:string}){return <div className="home-empty">{text}</div>}
function DashboardSkeleton(){return <div className="dashboard-skeleton" aria-label="Carregando painel">{Array.from({length:8},(_,i)=><i key={i}/>)}</div>}
