import {useCallback,useEffect,useState} from 'react'
import {Download,ExternalLink,Search} from 'lucide-react'
import {exportCsv} from '../lib/csv'
import {DaviExcelFilters,DaviExcelRow,fetchDaviExcel,updateDaviExcelSale} from '../lib/records'
import {useHasPermission} from '../lib/PermissionsContext'
import {useToast} from '../components/ui'
import './DaviExcelPage.css'

const columns=['CLIENTE','DATA','PRAZO DE ENVIO','DATA DE ENVIO','TIPO','ML','PERFUME','VALOR','PAGAMENTO','FORMA DE PAGAMENTO','DATA PAGMT','CRÉDITO','OBSERVAÇÃO'] as const
const date=(value:string|null)=>value?new Date(`${value.slice(0,10)}T12:00:00`).toLocaleDateString('pt-BR'):'—'
const money=(value:number|null)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(value??0))
const shortcuts=[['','TODOS'],['PENDÊNCIAS','PENDÊNCIAS'],['AGUARDANDO PAGAMENTO','AGUARDANDO PAGAMENTO'],['AGUARDANDO PERFUME','AGUARDANDO PERFUME'],['AGUARDANDO PREPARAÇÃO','AGUARDANDO PREPARAÇÃO'],['PRONTO PARA ENVIO','PRONTO PARA ENVIO'],['ENVIO EM ANDAMENTO','ENVIO EM ANDAMENTO'],['ENVIADO','ENVIADOS'],['PAGOS','PAGOS'],['CANCELADO','CANCELADOS']] as const
const sortKey:Record<string,string>={CLIENTE:'client',DATA:'sale_date','PRAZO DE ENVIO':'deadline','DATA DE ENVIO':'shipped_at',TIPO:'type',ML:'volume',PERFUME:'perfume',VALOR:'amount',PAGAMENTO:'payment','DATA PAGMT':'paid_at'}

function Inline({row,field,type='text',options,onSaved}:{row:DaviExcelRow;field:'sale_date'|'sale_type'|'amount'|'payment_status'|'payment_method'|'paid_at'|'notes';type?:string;options?:string[];onSaved:(row:DaviExcelRow)=>void}){
 const toast=useToast(),[value,setValue]=useState(String(row[field]??'')),[saving,setSaving]=useState(false)
 const save=async()=>{const previous=String(row[field]??'');if(value===previous)return;setSaving(true);try{const parsed=field==='amount'?Number(value):value||null;await updateDaviExcelSale(row.id,{[field]:parsed});onSaved({...row,[field]:parsed} as DaviExcelRow);toast.push('Alteração salva.',{tone:'success'})}catch{setValue(previous);toast.push('Não foi possível salvar. A célula foi restaurada.',{tone:'error'})}finally{setSaving(false)}}
 if(options)return <select aria-label={field} disabled={saving} value={value} onChange={e=>setValue(e.target.value)} onBlur={save}>{options.map(option=><option key={option} value={option}>{option||'—'}</option>)}</select>
 return <input aria-label={field} disabled={saving} type={type} value={value} onChange={e=>setValue(e.target.value)} onBlur={save} onKeyDown={e=>{if(e.key==='Enter')e.currentTarget.blur();if(e.key==='Escape'){setValue(String(row[field]??''));e.currentTarget.blur()}}}/>
}

export function DaviExcelPage(){
 const canEdit=useHasPermission('sales.edit'),[rows,setRows]=useState<DaviExcelRow[]>([]),[total,setTotal]=useState(0),[page,setPage]=useState(0),[loading,setLoading]=useState(true),[filters,setFilters]=useState<DaviExcelFilters>({}),[search,setSearch]=useState(''),[sort,setSort]=useState('sale_date_desc')
 useEffect(()=>{const timer=setTimeout(()=>{setPage(0);setFilters(current=>({...current,search:search||undefined}))},300);return()=>clearTimeout(timer)},[search])
 const load=useCallback(()=>fetchDaviExcel(filters,page,100,sort).then(result=>{setRows(result.rows);setTotal(result.total)}).finally(()=>setLoading(false)),[filters,page,sort])
 useEffect(()=>{void load()},[load])
 const patchRow=(next:DaviExcelRow)=>setRows(current=>current.map(row=>row.id===next.id?next:row))
 const shortcut=(value:string)=>{setPage(0);if(value==='PENDÊNCIAS')setFilters(current=>({...current,operational_status:undefined,payment:'pending'}));else if(value==='AGUARDANDO PAGAMENTO')setFilters(current=>({...current,payment:'pending',operational_status:undefined}));else if(value==='PAGOS')setFilters(current=>({...current,payment:'paid',operational_status:undefined}));else setFilters(current=>({...current,payment:undefined,operational_status:value||undefined}))}
 const reorder=(label:string)=>{const key=sortKey[label];if(key)setSort(current=>current===`${key}_asc`?`${key}_desc`:`${key}_asc`)}
 const exportAll=async()=>{const all:DaviExcelRow[]=[];for(let index=0;;index++){const result=await fetchDaviExcel(filters,index,500,sort);all.push(...result.rows);if(all.length>=result.total)break}exportCsv('davi-excel.csv',all.map(row=>({'CLIENTE':row.client_name,'DATA':date(row.sale_date),'PRAZO DE ENVIO':row.shipping_deadline_display??row.operational_status,'DATA DE ENVIO':date(row.shipped_at),'TIPO':row.sale_type,'ML':row.volume_ml,'PERFUME':row.perfume_name,'VALOR':row.amount,'PAGAMENTO':row.payment_status,'FORMA DE PAGAMENTO':row.payment_method,'DATA PAGMT':date(row.paid_at),'CRÉDITO':row.credit_reference_amount,'OBSERVAÇÃO':row.notes})))}
 return <div className="page davi-excel"><header className="davi-title"><div><span>VISÃO COMERCIAL CANÔNICA</span><h1>Davi Excel</h1><p>{total.toLocaleString('pt-BR')} vendas reais · edição direta no CRM</p></div><button onClick={exportAll}><Download size={16}/>EXPORTAR</button></header>
  <div className="davi-shortcuts">{shortcuts.map(([value,label])=><button key={label} onClick={()=>shortcut(value)}>{label}</button>)}</div>
  <section className="davi-filters"><label><Search size={15}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar cliente, perfume ou observação"/></label><input aria-label="Cliente" placeholder="Cliente" onChange={e=>setFilters({...filters,client:e.target.value||undefined})}/><input aria-label="Perfume" placeholder="Perfume" onChange={e=>setFilters({...filters,perfume:e.target.value||undefined})}/><input type="date" aria-label="Venda a partir de" onChange={e=>setFilters({...filters,sale_from:e.target.value||undefined})}/><input type="date" aria-label="Venda até" onChange={e=>setFilters({...filters,sale_to:e.target.value||undefined})}/><input type="date" aria-label="Envio a partir de" onChange={e=>setFilters({...filters,shipped_from:e.target.value||undefined})}/><input type="date" aria-label="Envio até" onChange={e=>setFilters({...filters,shipped_to:e.target.value||undefined})}/><select aria-label="Tipo" onChange={e=>setFilters({...filters,type:e.target.value||undefined})}><option value="">Todos os tipos</option><option>APC</option><option>SPLIT</option></select><select aria-label="Pagamento" onChange={e=>setFilters({...filters,payment:e.target.value||undefined})}><option value="">Todos os pagamentos</option><option value="paid">Pago</option><option value="pending">Aguardando</option><option value="cancelled">Cancelado</option><option value="unknown">Revisão</option></select><select aria-label="Forma de pagamento" onChange={e=>setFilters({...filters,method:e.target.value||undefined})}><option value="">Todas as formas</option><option>PIX</option><option>CARTÃO</option><option>CRÉDITO</option></select><select aria-label="Crédito" onChange={e=>setFilters({...filters,credit:(e.target.value||undefined) as DaviExcelFilters['credit']})}><option value="">Com ou sem crédito</option><option value="with">Com crédito</option><option value="without">Sem crédito</option></select></section>
  <div className="davi-grid" aria-busy={loading}><table><thead><tr>{columns.map(label=><th key={label}><button onClick={()=>reorder(label)} disabled={!sortKey[label]}>{label}</button></th>)}<th>AÇÃO</th></tr></thead><tbody>{rows.map(row=><tr key={row.id}><td><strong>{row.client_name}</strong></td><td>{canEdit?<Inline row={row} field="sale_date" type="date" onSaved={patchRow}/>:date(row.sale_date)}</td><td><span className="davi-status">{row.shipping_deadline_display??row.operational_status}</span></td><td>{date(row.shipped_at)}</td><td>{canEdit?<Inline row={row} field="sale_type" options={['','APC','SPLIT']} onSaved={patchRow}/>:row.sale_type}</td><td>{row.volume_ml??'—'}</td><td>{row.perfume_name??'—'}</td><td>{canEdit?<Inline row={row} field="amount" type="number" onSaved={patchRow}/>:money(row.amount)}</td><td>{canEdit?<Inline row={row} field="payment_status" options={['paid','pending','cancelled','unknown']} onSaved={patchRow}/>:row.payment_status}</td><td>{canEdit?<Inline row={row} field="payment_method" onSaved={patchRow}/>:row.payment_method??'—'}</td><td>{canEdit?<Inline row={row} field="paid_at" type="date" onSaved={patchRow}/>:date(row.paid_at)}</td><td>{money(row.credit_reference_amount)}</td><td>{canEdit?<Inline row={row} field="notes" onSaved={patchRow}/>:row.notes??'—'}</td><td><button className="davi-open" onClick={()=>{history.pushState({},'',`/vendas/${row.id}`);dispatchEvent(new PopStateEvent('popstate'))}}><ExternalLink size={14}/>ABRIR VENDA</button></td></tr>)}</tbody></table>{!loading&&rows.length===0&&<p className="davi-empty">Nenhuma venda encontrada.</p>}</div>
  <footer className="davi-pages"><button disabled={page===0} onClick={()=>setPage(page-1)}>Anterior</button><span>Página {page+1} de {Math.max(1,Math.ceil(total/100))}</span><button disabled={(page+1)*100>=total} onClick={()=>setPage(page+1)}>Próxima</button></footer>
 </div>
}
