import{useCallback,useEffect,useRef,useState}from'react'
import{ChevronDown,Download,ExternalLink,Filter,Maximize2,Minimize2,Search}from'lucide-react'
import{exportCsv}from'../lib/csv'
import{DaviColumnFilter,DaviDistinctValue,DaviExcelFilters,DaviExcelRow,DaviFilterKind,fetchDaviExcel,fetchDaviExcelDistinct,updateDaviExcelSale}from'../lib/records'
import{useHasPermission}from'../lib/PermissionsContext'
import{useToast}from'../components/ui'
import{DaviExcelNewRows}from'../components/DaviExcelNewRows'
import'./DaviExcelPage.css'

type ColumnKey='client'|'sale_date'|'deadline'|'shipped_at'|'type'|'volume'|'perfume'|'amount'|'payment'|'method'|'paid_at'|'credit'|'notes'
type Column={key:ColumnKey;label:string;kind:DaviFilterKind;sort:string}
const columns:Column[]=[{key:'client',label:'CLIENTE',kind:'text',sort:'client'},{key:'sale_date',label:'DATA',kind:'date',sort:'sale_date'},{key:'deadline',label:'PRAZO DE ENVIO',kind:'date',sort:'deadline'},{key:'shipped_at',label:'DATA DE ENVIO',kind:'date',sort:'shipped_at'},{key:'type',label:'TIPO',kind:'text',sort:'type'},{key:'volume',label:'ML',kind:'number',sort:'volume'},{key:'perfume',label:'PERFUME',kind:'text',sort:'perfume'},{key:'amount',label:'VALOR',kind:'number',sort:'amount'},{key:'payment',label:'PAGAMENTO',kind:'text',sort:'payment'},{key:'method',label:'FORMA DE PAGAMENTO',kind:'text',sort:'method'},{key:'paid_at',label:'DATA PAGMT',kind:'date',sort:'paid_at'},{key:'credit',label:'CRÉDITO',kind:'number',sort:'credit'},{key:'notes',label:'OBSERVAÇÃO',kind:'text',sort:'notes'}]
const date=(value:string|null)=>value?new Date(`${value.slice(0,10)}T12:00:00`).toLocaleDateString('pt-BR'):'—'
const money=(value:number|null)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(value??0))
const valueLabel=(column:ColumnKey,value:string)=>value==='__BLANK__'?'Em branco':column==='payment'?({paid:'PAGO',pending:'AGUARDANDO',cancelled:'CANCELADO',unknown:'REVISÃO'}[value]??value):value
const conditionOptions:Record<DaviFilterKind,[string,string][]>=
 {text:[['contains','Contém'],['not_contains','Não contém'],['starts_with','Começa com'],['ends_with','Termina com'],['equals','É exatamente']],date:[['eq','É igual a'],['before','Antes de'],['after','Depois de'],['between','Entre']],number:[['eq','Igual a'],['gt','Maior que'],['gte','Maior ou igual'],['lt','Menor que'],['lte','Menor ou igual'],['between','Entre']]}
const saved=()=>{try{return JSON.parse(sessionStorage.getItem('davi_excel_state')??'{}')as{filters?:DaviExcelFilters;sort?:string}}catch{return{}}}

function Inline({row,field,type='text',options,onSaved}:{row:DaviExcelRow;field:'sale_date'|'sale_type'|'amount'|'payment_status'|'payment_method'|'paid_at'|'notes';type?:string;options?:string[];onSaved:(row:DaviExcelRow)=>void}){
 const toast=useToast(),[value,setValue]=useState(String(row[field]??'')),[saving,setSaving]=useState(false)
 const save=async()=>{const previous=String(row[field]??'');if(value===previous)return;setSaving(true);try{const parsed=field==='amount'?Number(value):value||null;await updateDaviExcelSale(row.id,{[field]:parsed});onSaved({...row,[field]:parsed}as DaviExcelRow);toast.push('Alteração salva.',{tone:'success'})}catch{setValue(previous);toast.push('Não foi possível salvar. A célula foi restaurada.',{tone:'error'})}finally{setSaving(false)}}
 if(options)return <select aria-label={field} disabled={saving} value={value} onChange={e=>setValue(e.target.value)} onBlur={save}>{options.map(option=><option key={option} value={option}>{option||'—'}</option>)}</select>
 return <input aria-label={field} disabled={saving} type={type} value={value} onChange={e=>setValue(e.target.value)} onBlur={save} onKeyDown={e=>{if(e.key==='Enter')e.currentTarget.blur();if(e.key==='Escape'){setValue(String(row[field]??''));e.currentTarget.blur()}}}/>
}

function ColumnFilterMenu({column,filters,active,sort,onSort,onApply,onClose}:{column:Column;filters:DaviExcelFilters;active?:DaviColumnFilter;sort:string;onSort:(sort:string)=>void;onApply:(filter?:DaviColumnFilter)=>void;onClose:()=>void}){
 const ref=useRef<HTMLDivElement>(null),[draft,setDraft]=useState<DaviColumnFilter>(()=>structuredClone(active??{})),[query,setQuery]=useState(''),[values,setValues]=useState<DaviDistinctValue[]>([]),[total,setTotal]=useState(0),[hasMore,setHasMore]=useState(false),[loading,setLoading]=useState(true)
 const attach=(node:HTMLDivElement|null)=>{ref.current=node;if(node){const rect=node.parentElement?.getBoundingClientRect();if(rect){node.style.top=`${Math.min(rect.bottom,window.innerHeight-90)}px`;node.style.left=`${Math.max(12,Math.min(rect.left,window.innerWidth-352))}px`}}}
 useEffect(()=>{const close=(event:MouseEvent)=>{if(!ref.current?.contains(event.target as Node))onClose()},key=(event:KeyboardEvent)=>{if(event.key==='Escape')onClose()};document.addEventListener('mousedown',close);document.addEventListener('keydown',key);return()=>{document.removeEventListener('mousedown',close);document.removeEventListener('keydown',key)}},[onClose])
 useEffect(()=>{let live=true;const timer=setTimeout(()=>{setLoading(true);fetchDaviExcelDistinct(column.key,filters,query).then(result=>{if(live){setValues(result.values);setTotal(result.total);setHasMore(result.has_more)}}).finally(()=>{if(live)setLoading(false)})},250);return()=>{live=false;clearTimeout(timer)}},[column.key,filters,query])
 const selected=draft.values,allSelected=selected===undefined
 const toggle=(value:string)=>setDraft(current=>{const base=current.values??values.map(item=>item.value),next=base.includes(value)?base.filter(item=>item!==value):[...base,value];return{...current,values:next}})
 const condition=draft.condition??{operator:'',value:'',value2:''},between=condition.operator==='between'
 const setCondition=(patch:Partial<NonNullable<DaviColumnFilter['condition']>>)=>setDraft(current=>({...current,condition:{...condition,...patch}}))
 const apply=()=>{const normalized:DaviColumnFilter={};if(draft.values!==undefined)normalized.values=draft.values;if(draft.condition?.operator&&draft.condition.value)normalized.condition=draft.condition;onApply(Object.keys(normalized).length?normalized:undefined)}
 const sortActive=sort===`${column.sort}_asc`||sort===`${column.sort}_desc`
 return <div className="davi-filter-menu" ref={attach} role="dialog" aria-label={`Filtro de ${column.label}`}>
  <div className="davi-filter-sort"><button className={sort===`${column.sort}_asc`?'selected':''} onClick={()=>onSort(`${column.sort}_asc`)}>{column.kind==='text'?'Classificar A → Z':column.kind==='date'?'Mais antigo → mais recente':'Menor → maior'}</button><button className={sort===`${column.sort}_desc`?'selected':''} onClick={()=>onSort(`${column.sort}_desc`)}>{column.kind==='text'?'Classificar Z → A':column.kind==='date'?'Mais recente → mais antigo':'Maior → menor'}</button>{sortActive&&<small>Ordenação ativa</small>}</div>
  <fieldset><legend>FILTRAR POR CONDIÇÃO</legend><select aria-label="Condição" value={condition.operator} onChange={e=>setCondition({operator:e.target.value})}><option value="">Nenhuma condição</option>{conditionOptions[column.kind].map(([value,label])=><option key={value} value={value}>{label}</option>)}</select>{condition.operator&&<div className="davi-condition-values"><input aria-label="Valor da condição" type={column.kind==='date'?'date':column.kind==='number'?'number':'text'} value={condition.value??''} onChange={e=>setCondition({value:e.target.value})}/>{between&&<input aria-label="Segundo valor da condição" type={column.kind==='date'?'date':column.kind==='number'?'number':'text'} value={condition.value2??''} onChange={e=>setCondition({value2:e.target.value})}/>}</div>}</fieldset>
  <fieldset><legend>FILTRAR POR VALORES</legend><label className="davi-value-search"><Search size={14}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={`Buscar ${column.label.toLowerCase()}…`}/></label><label className="davi-check"><input type="checkbox" checked={allSelected} onChange={e=>setDraft(current=>({...current,values:e.target.checked?undefined:[]}))}/><span>Selecionar todos</span></label><div className="davi-values" aria-busy={loading}>{values.map(item=><label className="davi-check" key={item.value}><input type="checkbox" checked={allSelected||Boolean(selected?.includes(item.value))} onChange={()=>toggle(item.value)}/><span>{valueLabel(column.key,item.value)}</span><small>{item.count}</small></label>)}{!loading&&!values.length&&<p>Nenhum valor encontrado.</p>}</div>{hasMore&&<small className="davi-more">Mostrando {values.length} de {total}. Use a busca para localizar outros valores.</small>}</fieldset>
  <footer><button onClick={()=>onApply(undefined)}>LIMPAR FILTRO DESTA COLUNA</button><button className="apply" onClick={apply}>APLICAR</button></footer>
 </div>
}

export function DaviExcelPage(){
 const[initial]=useState(saved),canEdit=useHasPermission('sales.edit'),[rows,setRows]=useState<DaviExcelRow[]>([]),[total,setTotal]=useState(0),[page,setPage]=useState(0),[loading,setLoading]=useState(true),[filters,setFilters]=useState<DaviExcelFilters>(initial.filters??{}),[search,setSearch]=useState(initial.filters?.search??''),[sort,setSort]=useState(initial.sort??'sale_date_desc'),[open,setOpen]=useState<ColumnKey|null>(null),[expanded,setExpanded]=useState(false)
 useEffect(()=>{const timer=setTimeout(()=>{setPage(0);setFilters(current=>({...current,search:search||undefined}))},300);return()=>clearTimeout(timer)},[search])
 useEffect(()=>{sessionStorage.setItem('davi_excel_state',JSON.stringify({filters,sort}))},[filters,sort])
 useEffect(()=>{document.documentElement.classList.toggle('davi-sheet-mode',expanded);return()=>document.documentElement.classList.remove('davi-sheet-mode')},[expanded])
 const load=useCallback(()=>fetchDaviExcel(filters,page,100,sort).then(result=>{setRows(result.rows);setTotal(result.total)}).finally(()=>setLoading(false)),[filters,page,sort])
 useEffect(()=>{void load()},[load])
 const activeCount=Object.keys(filters.columns??{}).length+(filters.search?1:0)
 const applyColumn=(key:ColumnKey,filter?:DaviColumnFilter)=>{setPage(0);setFilters(current=>{const next={...(current.columns??{})};if(filter)next[key]=filter;else delete next[key];return{...current,columns:Object.keys(next).length?next:undefined}});setOpen(null)}
 const clearAll=()=>{setSearch('');setFilters({});setSort('sale_date_desc');setPage(0);setOpen(null)}
 const patchRow=(next:DaviExcelRow)=>setRows(current=>current.map(row=>row.id===next.id?next:row))
 const exportAll=async()=>{const all:DaviExcelRow[]=[];for(let index=0;;index++){const result=await fetchDaviExcel(filters,index,500,sort);all.push(...result.rows);if(all.length>=result.total)break}exportCsv('davi-excel.csv',all.map(row=>({'CLIENTE':row.client_name,'DATA':date(row.sale_date),'PRAZO DE ENVIO':row.shipping_deadline_display??row.operational_status,'DATA DE ENVIO':date(row.shipped_at),'TIPO':row.sale_type,'ML':row.volume_ml,'PERFUME':row.perfume_name,'VALOR':row.amount,'PAGAMENTO':row.payment_status,'FORMA DE PAGAMENTO':row.payment_method,'DATA PAGMT':date(row.paid_at),'CRÉDITO':row.credit_reference_amount,'OBSERVAÇÃO':row.notes})))}
 return <div className={`page davi-excel ${expanded?'expanded':''}`}><header className="davi-title"><div><span>VISÃO COMERCIAL CANÔNICA</span><h1>Davi Excel</h1><p>{total.toLocaleString('pt-BR')} vendas encontradas</p></div><div className="davi-actions"><button onClick={()=>setExpanded(value=>!value)}>{expanded?<Minimize2 size={16}/>:<Maximize2 size={16}/>} {expanded?'SAIR DA TELA CHEIA':'EXPANDIR PLANILHA'}</button><button onClick={exportAll}><Download size={16}/>EXPORTAR</button></div></header>
  <section className="davi-toolbar"><label><Search size={15}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar cliente, perfume ou referência"/></label><span>{total.toLocaleString('pt-BR')} resultados · Página {page+1} de {Math.max(1,Math.ceil(total/100))}</span><button disabled={!activeCount&&sort==='sale_date_desc'} onClick={clearAll}>LIMPAR TODOS OS FILTROS {activeCount?`(${activeCount})`:''}</button></section>
  {canEdit&&<div className="davi-new-rows-shell"><DaviExcelNewRows onCreated={load}/></div>}
  <div className="davi-grid" aria-busy={loading}><table><thead><tr>{columns.map(column=>{const active=filters.columns?.[column.key];return <th key={column.key} data-column={column.key}><button className={`davi-filter-trigger ${active?'active':''}`} title={active?'Filtro ativo':`Filtrar ${column.label}`} aria-label={`${column.label}${active?' — filtro ativo':''}`} aria-expanded={open===column.key} onClick={()=>setOpen(current=>current===column.key?null:column.key)}><span>{column.label}</span>{active?<Filter size={13} fill="currentColor"/>:<ChevronDown size={13}/>}</button>{open===column.key&&<ColumnFilterMenu column={column} filters={filters} active={active} sort={sort} onSort={value=>{setSort(value);setOpen(null)}} onApply={filter=>applyColumn(column.key,filter)} onClose={()=>setOpen(null)}/>}</th>})}<th>AÇÃO</th></tr></thead><tbody>{rows.map(row=><tr key={row.id}><td><strong>{row.client_name}</strong></td><td>{canEdit?<Inline row={row} field="sale_date" type="date" onSaved={patchRow}/>:date(row.sale_date)}</td><td><span className="davi-status">{row.shipping_deadline_display??row.operational_status}</span></td><td>{date(row.shipped_at)}</td><td>{canEdit?<Inline row={row} field="sale_type" onSaved={patchRow}/>:row.sale_type}</td><td>{row.volume_ml??'—'}</td><td>{row.perfume_name??'—'}</td><td>{canEdit?<Inline row={row} field="amount" type="number" onSaved={patchRow}/>:money(row.amount)}</td><td>{canEdit?<Inline row={row} field="payment_status" options={['paid','pending','cancelled','unknown']} onSaved={patchRow}/>:valueLabel('payment',row.payment_status)}</td><td>{canEdit?<Inline row={row} field="payment_method" onSaved={patchRow}/>:row.payment_method??'—'}</td><td>{canEdit?<Inline row={row} field="paid_at" type="date" onSaved={patchRow}/>:date(row.paid_at)}</td><td>{money(row.credit_reference_amount)}</td><td>{canEdit?<Inline row={row} field="notes" onSaved={patchRow}/>:row.notes??'—'}</td><td><button className="davi-open" onClick={()=>{history.pushState({},'',`/vendas/${row.id}`);dispatchEvent(new PopStateEvent('popstate'))}}><ExternalLink size={14}/>ABRIR VENDA</button></td></tr>)}</tbody></table>{!loading&&!rows.length&&<p className="davi-empty">Nenhuma venda encontrada.</p>}</div>
  <footer className="davi-pages"><span>{total.toLocaleString('pt-BR')} resultados</span><button disabled={page===0} onClick={()=>setPage(page-1)}>Anterior</button><span>Página {page+1} de {Math.max(1,Math.ceil(total/100))}</span><button disabled={(page+1)*100>=total} onClick={()=>setPage(page+1)}>Próxima</button></footer>
 </div>
}
