import { useEffect, useState } from 'react'
import { AlertTriangle, Plus, Search, Truck, X } from 'lucide-react'
import { brl, integer, shortDate } from '../lib/format'
import { PeriodFilter } from '../components/PeriodFilter'
import { PeriodValue } from '../lib/period'
import { todayIso, deliveryState, deliveryLabels, deliveryLabel } from '../lib/delivery'
import { NewShipmentModal, OperationalShipments } from '../components/ShipmentOperations'
import {
  CommercialSale, LogisticsSummary, fetchDeliveryRows, fetchLogisticsSummary, updateShipment,
} from '../lib/records'
import { Metric } from '../components/shared/Metric'

export function DeliveriesPage({period,setPeriod}:{period:PeriodValue;setPeriod:(value:PeriodValue)=>void}) {
  const [rows,setRows]=useState<CommercialSale[]>([]),[filter,setFilter]=useState(''),[search,setSearch]=useState(''),[error,setError]=useState(''),[loading,setLoading]=useState(true)
  const [newShipment,setNewShipment]=useState(false),[historical,setHistorical]=useState<CommercialSale|null>(null),[historicalDate,setHistoricalDate]=useState(todayIso())
  const [summary,setSummary]=useState<LogisticsSummary|null>(null)
  const reload=()=>{Promise.all([fetchDeliveryRows(period),fetchLogisticsSummary(period)]).then(([sales,metrics])=>{setRows(sales);setSummary(metrics)}).catch(()=>setError('Não foi possível consultar as entregas.')).finally(()=>setLoading(false))}
  useEffect(reload,[period])
  const counts=rows.reduce((acc,row)=>{const key=deliveryState(row);acc[key]=(acc[key]??0)+1;return acc},{} as Record<string,number>)
  const visible=rows.filter((row)=>(!filter||deliveryState(row)===filter)&&(!search||`${row.original_client} ${row.perfume_name_raw}`.toLowerCase().includes(search.toLowerCase())))
  const register=async(row:CommercialSale,value:string|null)=>{try{await updateShipment(row.id,value);setHistorical(null);reload()}catch(err){setError(err instanceof Error?err.message:'Falha ao atualizar envio.')}}
  return <div className="page">{newShipment&&<NewShipmentModal close={()=>setNewShipment(false)}/>} {historical&&<div className="modal-layer"><button className="modal-scrim" aria-label="Fechar" onClick={()=>setHistorical(null)}/><div className="modal-panel"><div className="modal-title"><div><span>LOGÍSTICA HISTÓRICA</span><h2>Registrar envio histórico</h2></div><button onClick={()=>setHistorical(null)}><X/></button></div><div className="record-form"><p>Atualiza somente a data histórica da venda; não cria reserva nem envio operacional.</p><label className="field"><span>Data do envio</span><input type="date" value={historicalDate} onChange={event=>setHistoricalDate(event.target.value)}/></label><div className="form-actions">{historical.shipped_at&&<button onClick={()=>register(historical,null)}>Remover data</button>}<button onClick={()=>setHistorical(null)}>Cancelar</button><button className="primary" disabled={!historicalDate} onClick={()=>register(historical,historicalDate)}>Salvar envio histórico</button></div></div></div></div>}<div className="page-lead"><div><h2>Entregas</h2><p>Envios operacionais e registros históricos claramente separados.</p></div><div className="page-actions"><PeriodFilter value={period} onApply={setPeriod}/><button className="primary" onClick={()=>setNewShipment(true)}><Plus/> Novo envio</button></div></div>
    <OperationalShipments/>
    {summary&&<section className="coverage card"><div><span>Envios identificados</span><strong>{integer(summary.identified_shipments)}</strong></div><div><span>Enviados no período</span><strong>{integer(summary.shipped_in_period)}</strong></div><div><span>Média até envio</span><strong>{summary.average_days_to_ship==null?'—':`${summary.average_days_to_ship} dias`}</strong></div><div><span>Backlog operacional</span><strong>{integer(summary.operational_backlog)}</strong></div><div><span>Dentro do prazo real</span><strong>{integer(summary.historical_on_time)}</strong></div><div><span>Atrasados com prazo real</span><strong>{integer(summary.historical_late)}</strong></div></section>}
    <section className="metrics">{[['awaiting_shipment','Aguardando envio'],['overdue','Envio atrasado'],['shipped_on_time','Enviados no prazo'],['shipped_late','Enviados com atraso'],['shipped','Enviados'],['no_deadline','Sem prazo']].map(([key,label])=><Metric key={key} label={label} value={integer(counts[key]??0)} detail={period.label} icon={Truck}/>)}</section>
    <div className="toolbar card"><div className="search"><Search size={18}/><input value={search} onChange={(event)=>setSearch(event.target.value)} placeholder="Cliente ou perfume…"/></div><select value={filter} onChange={(event)=>setFilter(event.target.value)}><option value="">Todos os status</option>{Object.entries(deliveryLabels).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></div>
    {loading?<div className="empty card"><h3>Carregando entregas…</h3></div>:error?<div className="notice"><AlertTriangle/><span>{error}</span></div>:<div className="card clients-table"><div className="clients-caption"><strong>{integer(visible.length)} registros históricos</strong><span className="live-dot">SUPABASE</span></div><div className="table-wrap"><table><thead><tr><th>Cliente</th><th>Perfume</th><th>Tipo</th><th>ML</th><th>Venda</th><th>Prazo</th><th>Envio</th><th>Status</th><th>Valor</th><th>Observação</th><th>Ações</th></tr></thead><tbody>{visible.slice(0,500).map((row)=><tr key={row.id}><td><strong>{row.clients?.name??row.original_client}</strong></td><td>{row.perfume_name_raw}</td><td>{row.sale_type}</td><td>{row.volume_ml??'—'}</td><td>{row.sale_date?shortDate(row.sale_date):'—'}</td><td>{row.shipping_deadline_date?shortDate(row.shipping_deadline_date):row.shipping_deadline_raw||'—'}</td><td>{row.shipped_at?shortDate(row.shipped_at):'—'}</td><td><span className={`badge ${deliveryState(row)==='overdue'?'cancelled':'pending'}`}>{deliveryLabel(row)}</span></td><td>{brl(Number(row.amount))}</td><td>{row.notes??'—'}</td><td><button onClick={()=>{setHistorical(row);setHistoricalDate(row.shipped_at?.slice(0,10)||todayIso())}}>{row.shipped_at?'Editar envio histórico':'Registrar envio histórico'}</button></td></tr>)}</tbody></table></div></div>}
  </div>
}
