import { useEffect, useState } from 'react'
import { format } from 'date-fns'
import { AlertTriangle, Boxes, Check, Download, Plus, TrendingUp, UserRound, X } from 'lucide-react'
import { integer } from '../lib/format'
import { PeriodFilter } from '../components/PeriodFilter'
import { PeriodValue } from '../lib/period'
import { exportCsv } from '../lib/csv'
import {
  InventoryRow, InventorySummary, OperationalInventoryRow,
  adjustInventory, createInventoryItem, fetchInventory, fetchOperationalInventory, inventoryPerfumes,
} from '../lib/records'
import { Metric } from '../components/shared/Metric'

export function InventoryPage({period,setPeriod}:{period:PeriodValue;setPeriod:(value:PeriodValue)=>void}) {
  const [summary,setSummary]=useState<InventorySummary|null>(null),[rows,setRows]=useState<InventoryRow[]>([])
  const [operational,setOperational]=useState<OperationalInventoryRow[]>([])
  const [loading,setLoading]=useState(true),[error,setError]=useState(''),[showCreate,setShowCreate]=useState(false)
  const reload=()=>{setLoading(true);Promise.all([fetchInventory(period),fetchOperationalInventory()]).then(([result,balances])=>{setSummary(result.summary);setRows(result.rows);setOperational(balances);setError('')}).catch((reason)=>setError(reason instanceof Error?reason.message:'Não foi possível carregar o estoque.')).finally(()=>setLoading(false))}
  useEffect(()=>{Promise.all([fetchInventory(period),fetchOperationalInventory()]).then(([result,balances])=>{setSummary(result.summary);setRows(result.rows);setOperational(balances);setError('')}).catch((reason)=>setError(reason instanceof Error?reason.message:'Não foi possível carregar o estoque.')).finally(()=>setLoading(false))},[period])
  const adjust=async(row:InventoryRow,positive:boolean)=>{const raw=prompt(`${positive?'Entrada':'Ajuste negativo'} em ML para ${row.perfume}:`);if(!raw)return;const amount=Number(raw.replace(',','.'));if(!Number.isFinite(amount)||amount<=0)return alert('Informe uma quantidade válida.');const reason=prompt('Motivo obrigatório:')?.trim();if(!reason)return;if(!positive&&!confirm(`Confirma retirar ${amount} ML de ${row.perfume}?`))return;try{await adjustInventory(row.item_id,positive?amount:-amount,reason);reload()}catch(reason){alert(reason instanceof Error?reason.message:'Não foi possível registrar o movimento.')}}
  return <div className="page">
    {showCreate&&<InventoryCreate close={()=>setShowCreate(false)} saved={()=>{setShowCreate(false);reload()}}/>}
    <div className="page-lead"><div><h2>Estoque</h2><p>Saldo em ML e movimentações integradas às novas vendas.</p></div><div className="page-actions"><PeriodFilter value={period} onApply={setPeriod}/><button className="primary" onClick={()=>setShowCreate(true)}><Plus/> Cadastrar perfume</button></div></div>
    {summary&&<section className="metrics"><Metric label="Estoque físico" value={`${operational.reduce((sum,row)=>sum+Number(row.physical_ml),0).toLocaleString('pt-BR')} ML`} detail={`${integer(summary.items)} perfumes`} icon={Boxes}/><Metric label="Reservado para clientes" value={`${operational.reduce((sum,row)=>sum+Number(row.reserved_ml)+Number(row.shipping_ml),0).toLocaleString('pt-BR')} ML`} detail="Pago e ainda guardado" icon={UserRound}/><Metric label="Disponível para venda" value={`${operational.reduce((sum,row)=>sum+Number(row.available_ml),0).toLocaleString('pt-BR')} ML`} detail={`${operational.filter((row)=>row.reconciliation_status==='review_required').length} para reconciliar`} icon={Check}/><Metric label="Consumo no período" value={`${Number(summary.consumed_ml).toLocaleString('pt-BR')} ML`} detail={`${integer(summary.movements)} movimentações`} icon={TrendingUp}/></section>}
    {error?<div className="notice"><AlertTriangle/><span>{error}</span></div>:loading?<div className="empty card"><h3>Carregando estoque…</h3></div>:rows.length===0?<div className="empty card"><Boxes/><h3>Estoque pronto para começar</h3><p>Cadastre o saldo físico inicial de um perfume.</p><button className="primary" onClick={()=>setShowCreate(true)}>Cadastrar primeiro perfume</button></div>:<div className="card clients-table"><div className="clients-caption"><strong>{integer(rows.length)} perfumes controlados</strong><button onClick={()=>exportCsv('estoque-ruah.csv',operational as unknown as Record<string,unknown>[])}><Download/> Exportar</button></div><div className="table-wrap"><table><thead><tr><th>Perfume</th><th>Físico</th><th>Reservado</th><th>Em preparação</th><th>Disponível</th><th>Limite mínimo</th><th>Reconciliação</th><th>Ações</th></tr></thead><tbody>{operational.map((balance)=><tr key={balance.item_id}><td><strong>{balance.perfume}</strong></td><td>{Number(balance.physical_ml).toLocaleString('pt-BR')} ML</td><td>{Number(balance.reserved_ml).toLocaleString('pt-BR')} ML</td><td>{Number(balance.shipping_ml).toLocaleString('pt-BR')} ML</td><td>{Number(balance.available_ml).toLocaleString('pt-BR')} ML</td><td>{Number(balance.minimum_ml).toLocaleString('pt-BR')} ML</td><td><span className={`badge ${balance.reconciliation_status==='reconciled'?'paid':'pending'}`}>{balance.reconciliation_status==='reconciled'?'Reconciliado':'Revisão necessária'}</span></td><td><button onClick={()=>adjust(rows.find((row)=>row.item_id===balance.item_id)!,true)}>Entrada</button><button onClick={()=>adjust(rows.find((row)=>row.item_id===balance.item_id)!,false)}>Ajustar</button></td></tr>)}</tbody></table></div></div>}
  </div>
}


function InventoryCreate({close,saved}:{close:()=>void;saved:()=>void}) {
  const [perfumes,setPerfumes]=useState<{id:string;full_name_raw:string}[]>([]),[perfumeId,setPerfumeId]=useState('')
  const [opening,setOpening]=useState(''),[minimum,setMinimum]=useState(''),[reference,setReference]=useState(format(new Date(),'yyyy-MM-dd')),[notes,setNotes]=useState(''),[error,setError]=useState(''),[saving,setSaving]=useState(false)
  useEffect(()=>{inventoryPerfumes().then((data)=>setPerfumes(data))},[])
  const submit=async()=>{const openingMl=Number(opening.replace(',','.')),minimumMl=Number(minimum.replace(',','.'));if(!perfumeId||!Number.isFinite(openingMl)||openingMl<0||!Number.isFinite(minimumMl)||minimumMl<0||!reference)return setError('Preencha perfume, saldos e data corretamente.');setSaving(true);try{await createInventoryItem({perfumeId,openingMl,minimumMl,referenceDate:reference,notes});saved()}catch(reason){setError(reason instanceof Error?reason.message:'Não foi possível cadastrar o estoque.')}finally{setSaving(false)}}
  return <div className="modal-layer"><button className="modal-scrim" aria-label="Fechar" onClick={close}/><div className="modal-panel inventory-modal"><div className="modal-title"><div><span>CONTROLE DE ESTOQUE</span><h2>Cadastrar perfume</h2></div><button onClick={close}><X/></button></div><div className="record-form"><div className="form-grid"><label className="field wide"><span>Perfume existente</span><select value={perfumeId} onChange={(event)=>setPerfumeId(event.target.value)}><option value="">Selecione…</option>{perfumes.map((perfume)=><option key={perfume.id} value={perfume.id}>{perfume.full_name_raw}</option>)}</select></label><label className="field"><span>Saldo inicial em ML</span><input inputMode="decimal" value={opening} onChange={(event)=>setOpening(event.target.value)}/></label><label className="field"><span>Limite mínimo em ML</span><input inputMode="decimal" value={minimum} onChange={(event)=>setMinimum(event.target.value)}/></label><label className="field"><span>Data de referência</span><input type="date" value={reference} onChange={(event)=>setReference(event.target.value)}/></label><label className="field wide"><span>Observação</span><textarea value={notes} onChange={(event)=>setNotes(event.target.value)}/></label></div>{error&&<div className="form-error">{error}</div>}<div className="form-actions"><button onClick={close}>Cancelar</button><button className="primary" disabled={saving} onClick={submit}>{saving?'Salvando…':'Cadastrar estoque'}</button></div></div></div></div>
}
