import {useEffect,useState} from 'react'
import {Barcode,CheckCircle2,Printer,ScanLine} from 'lucide-react'
import {QrCameraScanner} from '../components/bottles/QrCameraScanner'
import {PrimaryButton,SecondaryButton} from '../components/ui'
import {PreparationBottle,PreparationCandidate,PreparationPerfume,confirmPreparationBatch,createPreparationBatch,fetchPreparationBottles,fetchPreparationCandidates,fetchPreparationPerfumes,identifyPreparationBatch,printPerfumeLabel} from '../lib/preparation'
import './PreparationPage.css'

type DraftItem=PreparationCandidate&{selected:boolean;prepare_ml:number;source_bottle_id:string}
export function PreparationPage(){
 const [perfumes,setPerfumes]=useState<PreparationPerfume[]>([]),[perfumeId,setPerfumeIdState]=useState(''),[items,setItems]=useState<DraftItem[]>([]),[bottles,setBottles]=useState<PreparationBottle[]>([]),[batchId,setBatchId]=useState(''),[identified,setIdentified]=useState(false),[scanner,setScanner]=useState(false),[manual,setManual]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[done,setDone]=useState(false)
 useEffect(()=>{fetchPreparationPerfumes().then(setPerfumes).catch(e=>setMessage(e.message))},[])
 const setPerfumeId=async(id:string)=>{setPerfumeIdState(id);setItems([]);setBottles([]);if(!id)return;try{const[rows,source]=await Promise.all([fetchPreparationCandidates(id),fetchPreparationBottles(id)]);setBottles(source);setItems(rows.map(row=>({...row,selected:true,prepare_ml:Number(row.remaining_ml),source_bottle_id:source.length===1?source[0].id:''})))}catch(e){setMessage(e instanceof Error?e.message:'Não foi possível carregar as custódias.')}}
 const perfume=perfumes.find(row=>row.id===perfumeId),selected=items.filter(item=>item.selected),total=selected.reduce((sum,item)=>sum+Number(item.prepare_ml||0),0)
 const invalid=selected.some(item=>item.prepare_ml<=0||item.prepare_ml>item.remaining_ml||(item.bottle_tracking_status==='active'&&!item.source_bottle_id))
 const start=async()=>{if(!perfume||!selected.length||invalid)return;setBusy(true);setMessage('');try{setBatchId(await createPreparationBatch(perfume.id,selected.map(item=>({allocation_id:item.allocation_id,quantity_ml:item.prepare_ml,source_bottle_id:item.source_bottle_id||null}))))}catch(e){setMessage(e instanceof Error?e.message:'Não foi possível iniciar.')}finally{setBusy(false)}}
 const scan=async(code:string)=>{if(!batchId)return;setBusy(true);setMessage('');try{const result=await identifyPreparationBatch(batchId,code);if(!result.ok){setMessage(result.reason==='wrong_perfume'?`Perfume incorreto. Esperado: ${result.expected}. Bipado: ${result.scanned}.`:'Código de perfume não encontrado.');return}setIdentified(true);setScanner(false);setMessage(`✓ ${result.perfume} identificado`)}catch(e){setMessage(e instanceof Error?e.message:'Não foi possível identificar.')}finally{setBusy(false)}}
 const confirm=async()=>{setBusy(true);try{const result=await confirmPreparationBatch(batchId);setDone(true);setMessage(result.already_confirmed?(result.message??'Este fracionamento já foi concluído.'):`✓ Fracionamento concluído — ${result.total_ml} ml para ${result.item_count} clientes.`)}catch(e){setMessage(e instanceof Error?e.message:'Não foi possível confirmar.')}finally{setBusy(false)}}
 if(done)return <div className="page preparation-page"><section className="preparation-success"><CheckCircle2/><h1>FRACIONAMENTO CONCLUÍDO</h1><strong>{total} ml</strong><span>{selected.length} clientes</span><p>Os perfumes já estão disponíveis para solicitação na Minha RUAH.</p><PrimaryButton onClick={()=>location.reload()}>NOVO FRACIONAMENTO</PrimaryButton></section></div>
 return <div className="page preparation-page"><header><span>ESTOQUE</span><h1>Fracionamento</h1><p>Prepare os perfumes das clientes e confirme com o código único do perfume.</p></header>{message&&<div className="notice">{message}</div>}
 {!batchId?<><label className="field"><span>Perfume</span><select value={perfumeId} onChange={e=>setPerfumeId(e.target.value)}><option value="">Selecione…</option>{perfumes.map(p=><option value={p.id} key={p.id}>{p.full_name_raw} · {p.operational_code}</option>)}</select></label>{perfume&&<section className="preparation-identity"><div><span>IDENTIFICAÇÃO OPERACIONAL</span><strong>{perfume.full_name_raw}</strong><code>{perfume.operational_code}</code></div><SecondaryButton icon={<Printer/>} onClick={()=>printPerfumeLabel(perfume)}>IMPRIMIR ETIQUETA DO PERFUME</SecondaryButton></section>}<section><h2>A PREPARAR</h2><div className="preparation-items">{items.map((item,index)=><article key={item.allocation_id}><label><input type="checkbox" checked={item.selected} onChange={e=>setItems(current=>current.map((row,i)=>i===index?{...row,selected:e.target.checked}:row))}/><strong>{item.client_name}</strong></label><span>{item.remaining_ml} ml ainda aguardando</span><label>Quantidade<input type="number" min="0.001" max={item.remaining_ml} step="0.001" value={item.prepare_ml} onChange={e=>setItems(current=>current.map((row,i)=>i===index?{...row,prepare_ml:Number(e.target.value)}:row))}/></label>{item.bottle_tracking_status==='active'&&<label>Frasco de origem<select value={item.source_bottle_id} onChange={e=>setItems(current=>current.map((row,i)=>i===index?{...row,source_bottle_id:e.target.value}:row))}><option value="">Escolha o frasco…</option>{bottles.map(b=><option key={b.id} value={b.id}>{b.bottle_code} · {b.bottle_label} · {b.physical_ml} ml</option>)}</select></label>}</article>)}</div>{items.length===0&&perfume&&<p>Nenhuma custódia aguardando preparação.</p>}</section><footer><strong>{selected.length} clientes · {total} ml</strong><PrimaryButton loading={busy} disabled={!selected.length||invalid} onClick={start}>INICIAR FRACIONAMENTO</PrimaryButton></footer></>:<section className="preparation-scan"><Barcode/><h2>{perfume?.full_name_raw}</h2><strong>{selected.length} clientes · {total} ml</strong>{!identified?<><p>Depois de concluir o preparo físico, bipe o código do perfume.</p><PrimaryButton icon={<ScanLine/>} onClick={()=>setScanner(true)}>BIPAR PERFUME PARA CONFERIR</PrimaryButton><form onSubmit={e=>{e.preventDefault();scan(manual)}}><input value={manual} onChange={e=>setManual(e.target.value)} placeholder="RUAH-P000123"/><button>VALIDAR CÓDIGO</button></form>{scanner&&<QrCameraScanner onScan={scan} onClose={()=>setScanner(false)}/>}</>:<><CheckCircle2/><h3>CONFIRMAR FRACIONAMENTO?</h3>{selected.map(item=><span key={item.allocation_id}>{item.client_name} — {item.prepare_ml} ml</span>)}<div><SecondaryButton onClick={()=>setIdentified(false)}>CANCELAR</SecondaryButton><PrimaryButton loading={busy} onClick={confirm}>CONFIRMAR {total} ML</PrimaryButton></div></>}</section>}</div>
}
