import {useMemo,useRef,useState} from 'react'
import {AlertTriangle,Check,Loader2,Plus,Sparkles,X} from 'lucide-react'
import {brl,countedLabel,integer,shortDate} from '../lib/format'
import {normalizeInventoryPerfumeName,reconcileInventoryGroup} from '../lib/ai-inventory'
import {AiImportSummary,buildAiImportSummarySentences} from '../lib/ai-import-summary'
import {buildAiImportPreviewSummary} from '../lib/ai-import-preview-summary'
import {AiSalesBatchGroup,AiSalesBatchMultiResult,AiSalesBatchPreview,bootstrapAiBatchInventory,confirmAiSalesBatch,confirmAiSalesBatchMulti,fetchOperationalInventory,OperationalInventoryRow,parseSalesBatch,PerfumeResolutionCandidate,summarizeAiBatchImport} from '../lib/records'

const today=()=>new Date().toISOString().slice(0,10)
const missingFields=['CPF','telefone','CEP','endereço','número','bairro','cidade','UF']
const formatMl=(value:number)=>`${value.toLocaleString('pt-BR',{maximumFractionDigits:3})} ml`
const groupKey=(group:Pick<AiSalesBatchGroup,'normalized_perfume_name'|'bottle_number'>)=>`${group.normalized_perfume_name}::${group.bottle_number??''}`
const saleGroupKey=(perfumeName?:string)=>{const bottle=String(perfumeName??'').match(/\(\s*frasco\s+(\d+)\s*\)\s*$/i)?.[1]??'';return`${normalizeInventoryPerfumeName(perfumeName??'')}::${bottle}`}

type Blocker={text:string;target?:string}
type Summary=AiImportSummary

function toSummary(preview:AiSalesBatchPreview,multi:AiSalesBatchMultiResult|null,single:{sales_created:number;clients_created:number;shipping_incomplete:number;inventory_remaining_ml?:number;idempotent?:boolean}|null):Summary{
  if(multi)return multi
  const created=single?.sales_created??0,clientsCreated=single?.clients_created??0
  const bootstrapped=preview.inventory?.reconciliation_status==='review_required'?1:0
  return{
    sales_created:created,clients_created:clientsCreated,clients_existing:Math.max(0,preview.sales.length-clientsCreated),
    perfumes_processed:1,perfumes_matched:bootstrapped?0:1,inventory_items_bootstrapped:bootstrapped,
    total_ml_sold:preview.totals.volume_ml,total_amount_sold:preview.totals.amount,
    commercial_remaining_ml:preview.remaining_available_ml??0,commercial_remaining_amount:0,
    inventory_remaining_ml:single?.inventory_remaining_ml??0,
    shipping_incomplete:single?.shipping_incomplete??0,
    paid_source_count:0,awaiting_source_count:0,unstated_payment_count:preview.sales.length,
    idempotent:single?.idempotent??false,
  }
}

export function AiSalesBatchImport({close,completed}:{close:()=>void;completed:()=>void}){
  const [text,setText]=useState(''),[date,setDate]=useState(today()),[preview,setPreview]=useState<AiSalesBatchPreview|null>(null),[inventory,setInventory]=useState<OperationalInventoryRow[]>([]),[busy,setBusy]=useState(''),[error,setError]=useState(''),[bootstrap,setBootstrap]=useState<AiSalesBatchGroup|null>(null)
  const [ambiguousCandidates,setAmbiguousCandidates]=useState<PerfumeResolutionCandidate[]|null>(null)
  const openBootstrap=(group:AiSalesBatchGroup)=>{setAmbiguousCandidates(null);setBootstrap(group)}
  const closeBootstrap=()=>{setBootstrap(null);setAmbiguousCandidates(null)}
  const [phase,setPhase]=useState<'input'|'preview'|'processing'|'summary'|'failed'>('input')
  const [summary,setSummary]=useState<Summary|null>(null),[aiText,setAiText]=useState<string|null>(null),[aiPending,setAiPending]=useState(false),[confirmError,setConfirmError]=useState('')
  const scrollRef=useRef<HTMLDivElement|null>(null)

  const blockers=useMemo<Blocker[]>(()=>{
    if(!preview)return[]
    const list:Blocker[]=[]
    // Importação de venda é comercial, não recebimento de estoque: o volume
    // vendido nunca precisa igualar o volume físico do perfume/frasco/lote —
    // uma venda pode existir sem inventory_item, sem RUAH-P e sem saldo
    // físico algum. volume_consistent só compara dois números que Davi
    // digitou no próprio texto ("Frasco original com Xml" vs "Xmls
    // disponíveis") — é uma checagem de digitação, nunca um gate comercial;
    // por isso segue disponível como contexto visual (ver .warning no
    // overview), mas nunca bloqueia a criação das vendas.
    if(preview.source_format==='tsv'){
      for(const group of preview.groups??[])if(!group.perfume_id)list.push({text:`Perfume "${group.display_name||group.perfume}" precisa de resolução no catálogo`,target:`group-${groupKey(group)}`})
    }else if(!preview.perfume_id)list.push({text:'Resolva o perfume no catálogo da RUAH',target:'single-perfume'})
    if(preview.pricing_consistent===false)list.push({text:'Os valores publicados não conferem com a cotação, a recravação e o adicional do APC',target:'pricing-validation'})
    preview.sales.forEach((sale,index)=>{if(sale.volume_ml<=0)list.push({text:`Volume inválido para ${sale.client_name}`,target:`sale-${index}`})})
    preview.sales.forEach((sale,index)=>{if(sale.client_match_status==='review'||(!sale.client_id&&sale.client_match_status!=='new'))list.push({text:`Confirme quem é ${sale.client_name}`,target:`sale-${index}`})})
    preview.sales.forEach((sale,index)=>{if(sale.possible_duplicate)list.push({text:`Possível venda repetida para ${sale.client_name}`,target:`sale-${index}`})})
    if(preview.duplicate_batch)list.push({text:'Esta lista parece já ter sido importada'})
    if(preview.shipping_availability_text&&!preview.shipping_availability_human_confirmed)list.push({text:'Confirme a disponibilidade para envio identificada',target:'shipping-availability'})
    return list
  },[preview])
  const perfumePendingCount=useMemo(()=>!preview?0:preview.source_format==='tsv'?(preview.groups??[]).filter(group=>!group.perfume_id).length:preview.perfume_id?0:1,[preview])
  const clientPendingCount=useMemo(()=>blockers.filter(b=>b.target?.startsWith('sale-')).length,[blockers])
  const previewSummary=useMemo(()=>preview?buildAiImportPreviewSummary(preview):null,[preview])

  const goToFirstPending=()=>{const target=blockers.find(b=>b.target)?.target;if(!target)return;document.getElementById(target)?.scrollIntoView({behavior:'smooth',block:'center'})}

  const analyze=async()=>{setBusy('analyze');setError('');try{const [parsed,items]=await Promise.all([parseSalesBatch(text,date),fetchOperationalInventory()]),sorted=[...items].sort((a,b)=>a.perfume.localeCompare(b.perfume,'pt-BR',{sensitivity:'base'})),groups=parsed.groups?.map(group=>reconcileInventoryGroup(group,sorted)),exact=sorted.filter(item=>item.perfume_id===parsed.perfume_id);setInventory(sorted);setPreview({...parsed,groups,inventory_item_id:exact.length===1?exact[0].item_id:parsed.inventory_item_id,inventory:exact.length===1?exact[0]:parsed.inventory,perfume_match_status:exact.length===1?'found':parsed.perfume_match_status});setPhase('preview')}catch(reason){setError(reason instanceof Error?reason.message:'Não foi possível analisar.')}finally{setBusy('')}}
  const chooseInventory=(itemId:string)=>{const item=inventory.find(row=>row.item_id===itemId);setPreview(current=>current?{...current,inventory_item_id:item?.item_id??null,perfume_id:item?.perfume_id??null,perfume:item?.perfume??current.perfume,inventory:item??null,perfume_match_status:item?'found':'review'}:current)}
  const chooseGroupInventory=(key:string,itemId:string)=>{const item=inventory.find(row=>row.item_id===itemId);setPreview(current=>current?{...current,groups:current.groups?.map(group=>groupKey(group)===key?{...group,inventory_item_id:item?.item_id??null,perfume_id:item?.perfume_id??null,inventory:item??null,perfume_match_status:item?'found':'review'}:group)}:current)}
  const chooseClient=(index:number,id:string)=>setPreview(current=>current?{...current,sales:current.sales.map((sale,i)=>i===index?{...sale,client_id:id||null,client_match_status:id?'found':'new',missing_shipping_fields:id?sale.suggestions.find(x=>x.id===id)?.missing_shipping_fields??[]:missingFields}:sale)}:current)
  const editSale=(index:number,field:'sale_type'|'volume_ml'|'amount',value:string)=>setPreview(current=>{if(!current)return current;const sales=current.sales.map((sale,i)=>i===index?{...sale,[field]:field==='sale_type'?value:Number(value),possible_duplicate:false}:sale),volume_ml=sales.reduce((sum,s)=>sum+s.volume_ml,0),amount=Math.round(sales.reduce((sum,s)=>sum+s.amount,0)*100)/100,calculated_balance_ml=current.original_volume_ml==null?null:current.original_volume_ml-volume_ml,volume_consistent=calculated_balance_ml==null||current.announced_balance_ml==null?true:Math.abs(calculated_balance_ml-current.announced_balance_ml)<.001;return{...current,sales,groups:current.groups?.map(group=>{const groupSales=sales.filter(sale=>saleGroupKey(sale.perfume_name)===groupKey(group));return{...group,sales:groupSales,totals:{sales:groupSales.length,volume_ml:groupSales.reduce((sum,sale)=>sum+sale.volume_ml,0),amount:Math.round(groupSales.reduce((sum,sale)=>sum+sale.amount,0)*100)/100}}}),totals:{...current.totals,volume_ml,amount,calculated_balance_ml,volume_consistent}}})

  const confirm=async()=>{
    if(!preview||blockers.length||busy)return
    setBusy('confirm');setConfirmError('');setPhase('processing')
    try{
      const multi=preview.source_format==='tsv'&&(preview.groups?.length??0)>0
      const outcome=multi?await confirmAiSalesBatchMulti(preview):await confirmAiSalesBatch(preview)
      const built=multi?toSummary(preview,outcome as AiSalesBatchMultiResult,null):toSummary(preview,null,outcome as {sales_created:number;clients_created:number;shipping_incomplete:number;inventory_remaining_ml?:number;idempotent?:boolean})
      setSummary(built);setPhase('summary');completed()
      setAiPending(true)
      summarizeAiBatchImport(buildAiImportSummarySentences(built)).then(text=>setAiText(text)).finally(()=>setAiPending(false))
    }catch(reason){setConfirmError(reason instanceof Error?reason.message:'Não foi possível concluir a importação.');setPhase('failed')}
    finally{setBusy('')}
  }
  const retry=()=>{setPhase('preview');setConfirmError('')}

  const createFromSales=async(selectedPerfumeId?:string)=>{if(!preview||!bootstrap)return;setBusy('bootstrap');setError('');try{
    const resolved=await bootstrapAiBatchInventory({fingerprint:preview.fingerprint,rawPerfumeName:bootstrap.raw_perfume_name,brand:bootstrap.brand,bottleNumber:bootstrap.bottle_number,referenceDate:preview.sale_date,sales:bootstrap.sales,selectedPerfumeId})
    if(resolved.resolution_status==='ambiguous'){setAmbiguousCandidates(resolved.candidates??[]);return}
    setAmbiguousCandidates(null)
    if(!resolved.perfume_id)throw new Error('O perfume não pôde ser resolvido no catálogo.')
    const row=inventory.find(item=>item.item_id===resolved.inventory_item_id)??null
    setPreview(current=>current?{...current,groups:current.groups?.map(group=>groupKey(group)===groupKey(bootstrap)?{...group,inventory_item_id:row?.item_id??null,perfume_id:resolved.perfume_id,inventory:row,perfume_match_status:'found'}:group),...(current.source_format==='tsv'?{}:{inventory_item_id:row?.item_id??null,perfume_id:resolved.perfume_id,inventory:row,perfume_match_status:'found'})}:current);setBootstrap(null)
  }catch(reason){setError(reason instanceof Error?reason.message:'Não foi possível resolver o perfume no catálogo.')}finally{setBusy('')}}

  const saleCard=(sale:AiSalesBatchPreview['sales'][number],index:number)=><article className="batch-sale" id={`sale-${index}`} key={`${sale.client_name}-${index}`}><b>{String(index+1).padStart(2,'0')}</b><div><strong>{sale.client_name}</strong><div className="batch-sale-fields"><select aria-label={`Tipo de ${sale.client_name}`} value={sale.sale_type} onChange={e=>editSale(index,'sale_type',e.target.value)}><option>APC</option><option>SPLIT</option></select><input aria-label={`Volume de ${sale.client_name}`} type="number" min="0.001" step="0.001" value={sale.volume_ml} onChange={e=>editSale(index,'volume_ml',e.target.value)}/><input aria-label={`Valor de ${sale.client_name}`} type="number" min="0" step="0.01" value={sale.amount} onChange={e=>editSale(index,'amount',e.target.value)}/></div><small>Pagamento: aguardando confirmação{sale.possible_duplicate?' · ⚠ possível duplicidade':''}</small></div><label><span>CLIENTE NO CRM</span><select value={sale.client_id??''} onChange={e=>chooseClient(index,e.target.value)}><option value="">Criar novo cliente mínimo</option>{sale.suggestions.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><small>{sale.missing_shipping_fields.length?`Falta para envio: ${sale.missing_shipping_fields.join(', ')}`:'✓ Cadastro pronto para envio'}</small></label></article>
  const groupCard=(group:AiSalesBatchGroup)=><article key={groupKey(group)} id={`group-${groupKey(group)}`} className={`batch-perfume-card ${group.perfume_id?'found':group.perfume_match_status==='review'?'review':'missing'}`}><div><strong>{group.display_name||group.perfume}</strong><span>{group.totals.sales} vendas · {group.totals.volume_ml} ml · {brl(group.totals.amount)}</span>{group.bottle_number&&<small>Frasco {group.bottle_number}</small>}</div>{group.perfume_id?<div className="batch-perfume-state"><b>✓ PERFUME RESOLVIDO</b><span>{String(group.inventory?.perfume??group.display_name)}</span><small>{group.inventory_item_id?`${Number(group.inventory?.available_ml??0).toLocaleString('pt-BR')} ml físicos registrados`:'Aguardando chegada física à RUAH'}</small></div>:group.perfume_match_status==='review'?<div className="batch-perfume-state"><b>⚠ CONFIRMAR CORRESPONDÊNCIA</b><select aria-label={`Selecionar ${group.display_name}`} value="" onChange={e=>chooseGroupInventory(groupKey(group),e.target.value)}><option value="">Selecionar perfume…</option>{inventory.map(item=><option key={item.item_id} value={item.item_id}>{item.perfume}</option>)}</select></div>:<div className="batch-perfume-state"><b>+ NOVO PERFUME DE CATÁLOGO</b><small>Nenhum estoque físico será criado</small><button type="button" onClick={()=>openBootstrap(group)}><Plus/> RESOLVER PERFUME</button></div>}</article>

  const grossTotal=summary?Math.round((summary.total_amount_sold+summary.commercial_remaining_amount)*100)/100:0
  const anyBootstrapped=!!summary&&summary.inventory_items_bootstrapped>0

  return <div className="ai-batch-layer"><div className="ai-batch-scroll" ref={scrollRef}><section className="ai-batch-assistant"><header><div><span>RUAH · ASSISTENTE OPERACIONAL</span><h2><Sparkles/> Importar lista com IA</h2><p>A IA interpreta. Você revisa. O CRM só grava depois da confirmação.</p></div><button aria-label="Fechar" onClick={close}><X/></button></header>

  {phase==='summary'&&summary?<div className="ai-batch-result"><Check/><span>IMPORTAÇÃO CONCLUÍDA</span><h3>{countedLabel(summary.sales_created,'venda registrada','vendas registradas')}</h3><p>{brl(summary.total_amount_sold)} em vendas · {countedLabel(summary.total_ml_sold,'ml vendido','ml vendidos')}{summary.idempotent?' · lote já havia sido importado':''}</p>
    {summary.inventory_remaining_ml&&summary.inventory_remaining_ml>0?<p className="batch-summary-note"><strong>ESTOQUE REGISTRADO:</strong> {formatMl(summary.inventory_remaining_ml)} disponíveis no perfume confirmado.</p>:summary.commercial_remaining_ml>0&&<p className="batch-summary-note">{countedLabel(summary.commercial_remaining_ml,'ml permaneceu marcado','ml permaneceram marcados')} como disponíveis para venda, equivalentes a {brl(summary.commercial_remaining_amount)}. Total bruto da lista analisada: {brl(grossTotal)}.</p>}
    <dl className="batch-summary-grid">
      <div><dt>Clientes já existentes</dt><dd>{integer(summary.clients_existing)}</dd></div>
      <div><dt>Novos clientes criados</dt><dd>{integer(summary.clients_created)}</dd></div>
      <div><dt>Cadastros incompletos p/ envio</dt><dd>{integer(summary.shipping_incomplete)}</dd></div>
      <div><dt>Perfumes processados</dt><dd>{integer(summary.perfumes_processed)}</dd></div>
      <div><dt>Já existentes no estoque</dt><dd>{integer(summary.perfumes_matched)}</dd></div>
      <div><dt>Criados a partir das vendas</dt><dd>{integer(summary.inventory_items_bootstrapped)}</dd></div>
    </dl>
    {(summary.paid_source_count>0||summary.awaiting_source_count>0||summary.unstated_payment_count>0)&&<p className="batch-summary-note">Na lista original: {integer(summary.paid_source_count)} pagas · {integer(summary.awaiting_source_count)} aguardando · {integer(summary.unstated_payment_count)} sem status informado. Os status originais foram preservados para revisão. As vendas importadas entraram como pendentes conforme a regra atual do CRM.</p>}
    {anyBootstrapped&&<div className="batch-bootstrap-warning"><AlertTriangle/> {countedLabel(summary.inventory_items_bootstrapped,'perfume foi registrado','perfumes foram registrados')} a partir das vendas e precisam de conferência física antes de liberar estoque operacional.</div>}
    {aiPending?<p className="batch-summary-ai batch-summary-ai-loading"><Loader2 className="spin"/> Preparando resumo…</p>:<div className="batch-summary-ai"><span>RESUMO RUAH</span><p>{aiText??buildAiImportSummarySentences(summary).join(' ')}</p></div>}
    <div className="batch-summary-actions">
      <button className="primary" onClick={close}>VER VENDAS IMPORTADAS</button>
      {summary.shipping_incomplete>0&&<button onClick={()=>{history.pushState({},'','/clientes');dispatchEvent(new PopStateEvent('popstate'));close()}}>VER CLIENTES INCOMPLETOS</button>}
      {anyBootstrapped&&<button onClick={()=>{history.pushState({},'','/estoque');dispatchEvent(new PopStateEvent('popstate'));close()}}>VER ESTOQUE A CONFERIR</button>}
      <button onClick={close}>CONCLUIR</button>
    </div>
  </div>:phase==='processing'?<div className="ai-batch-result"><Loader2 className="spin"/><span>IMPORTANDO VENDAS</span><h3>Registrando clientes, perfumes e vendas.</h3><p>Não feche esta janela.</p></div>:phase==='failed'?<div className="ai-batch-result"><AlertTriangle/><span>NENHUMA VENDA FOI CRIADA</span><h3>Não foi possível concluir a importação</h3><p>Motivo: {confirmError}</p><p className="batch-summary-note">Como o write é atômico, nenhuma parte deste lote foi gravada.</p><button className="primary" onClick={retry}>TENTAR NOVAMENTE</button></div>:!preview?<div className="ai-batch-input"><label><span>DATA DAS VENDAS</span><input type="date" value={date} onChange={e=>setDate(e.target.value)}/><small>Pré-preenchida com hoje. Ajuste antes de analisar.</small></label><label><span>MENSAGEM DO DAVI</span><textarea value={text} onChange={e=>setText(e.target.value)} placeholder="Cole aqui a publicação completa…"/></label><div className="ai-batch-safety">Analisar não cria vendas, clientes, reservas, envios ou etiquetas.</div><button className="primary" disabled={!text.trim()||!!busy} onClick={analyze}>{busy?'ANALISANDO…':'ANALISAR LISTA'}</button></div>:<div className="ai-batch-preview">
    {previewSummary&&<section className="batch-review-summary" aria-labelledby="batch-review-summary-title"><h4 id="batch-review-summary-title">RESUMO DA IMPORTAÇÃO</h4><div className="batch-review-metrics"><article><strong>{integer(previewSummary.sales)}</strong><span>VENDAS RECONHECIDAS</span></article><article><strong>{formatMl(previewSummary.volumeMl)}</strong><span>VOLUME VENDIDO</span></article>{preview.remaining_available_ml!==null&&<article><strong>{formatMl(preview.remaining_available_ml)}</strong><span>SALDO DISPONÍVEL</span></article>}{preview.totals.total_operation_ml!==null&&<article><strong>{formatMl(preview.totals.total_operation_ml)}</strong><span>VOLUME TOTAL</span></article>}<article><strong>{brl(previewSummary.amount)}</strong><span>VALOR TOTAL</span></article></div>{preview.remaining_available_ml!==null&&<p className="batch-summary-note"><strong>ESTOQUE APÓS CONFIRMAÇÃO:</strong> {formatMl(preview.remaining_available_ml)} disponíveis</p>}</section>}
    <section className="batch-overview"><div><span>{preview.source_format==='tsv'?'IMPORTAÇÃO COM VÁRIOS LOTES':preview.perfume}</span><h3>{preview.source_format==='tsv'?`${preview.groups?.length??0} perfumes encontrados`:`FRASCO ${preview.bottle_number??'—'}`}</h3><p>{preview.totals.sales} vendas · {preview.totals.volume_ml} ml · {brl(preview.totals.amount)}{preview.availability_rows?` · ${preview.availability_rows} saldos comerciais`:''}</p></div><div className={preview.totals.volume_consistent?'ok':'warning'}><strong>{preview.groups?.length??1}</strong><span>lotes</span><strong>{preview.totals.sales}</strong><span>vendas</span><strong>{preview.totals.volume_ml} ml</strong><span>volume</span></div></section>
    {preview.source_format==='tsv'?<section className="batch-match"><h4>PERFUMES</h4><div className="batch-group-list">{preview.groups?.map(groupCard)}</div><small>Resolver um perfume para a venda não cria estoque físico.</small></section>:<section id="single-perfume" className="batch-match"><h4>PERFUME DE CATÁLOGO</h4><select aria-label="Buscar ou selecionar perfume" value={preview.inventory_item_id??''} onChange={e=>chooseInventory(e.target.value)}><option value="">Buscar ou selecionar perfume já recebido…</option>{inventory.map(item=><option key={item.item_id} value={item.item_id}>{item.perfume} — {Number(item.available_ml).toLocaleString('pt-BR')} ml físicos</option>)}</select><small>{preview.perfume_id?'✓ Perfume canônico selecionado.':'Selecione ou resolva o perfume de catálogo.'}</small>{!preview.perfume_id&&preview.perfume_match_status==='new'&&<button className="batch-create-single" type="button" onClick={()=>openBootstrap({perfume:preview.perfume,raw_perfume_name:preview.raw_perfume_name??preview.perfume,normalized_perfume_name:preview.normalized_perfume_name??normalizeInventoryPerfumeName(preview.perfume),display_name:preview.display_name??preview.perfume,brand:preview.brand??null,bottle_number:preview.bottle_number,inventory_item_id:null,perfume_id:preview.perfume_id,perfume_match_status:'new',perfume_matches:preview.perfume_matches,inventory:null,sales:preview.sales,availability_rows:preview.availability_rows??0,totals:{sales:preview.totals.sales,volume_ml:preview.totals.volume_ml,amount:preview.totals.amount}})}><Plus/> RESOLVER PERFUME NO CATÁLOGO</button>}</section>}
    <section className="batch-dates"><label><span>DATA DAS VENDAS</span><input type="date" value={preview.sale_date} onChange={e=>setPreview({...preview,sale_date:e.target.value})}/></label></section>
    {preview.source_format==='whatsapp'&&<section id="pricing-validation" className="batch-match"><h4>VALIDAÇÃO DOS VALORES</h4><p><strong>Cotação:</strong> {preview.quote_per_ml===null?'Não informada':`${brl(preview.quote_per_ml)}/ml`} · <strong>Recravação:</strong> {brl(preview.recrimping_fee??0)} · <strong>Adicional APC:</strong> {brl(preview.apc_extra??0)}</p>{preview.pricing_consistent===false?<div className="batch-bootstrap-warning"><AlertTriangle/> {preview.pricing_issues?.map(issue=>`${issue.sale_type} ${formatMl(issue.volume_ml)}: publicado ${brl(issue.announced_amount)}, cálculo ${brl(issue.expected_amount)}`).join(' · ')}</div>:<small>✓ Valores conferidos. SPLIT = ml × cotação + recravação; APC = ml × cotação + adicional APC.</small>}</section>}
    <section id="shipping-availability" className="batch-match"><h4>DISPONIBILIDADE PARA ENVIO</h4><p><strong>Texto identificado:</strong> {preview.shipping_availability_text??'Não informado'}</p>{preview.shipping_availability_text&&<><label><span>INTERPRETAÇÃO</span><select value={preview.shipping_availability_kind??'unknown'} onChange={e=>setPreview({...preview,shipping_availability_kind:e.target.value as AiSalesBatchPreview['shipping_availability_kind'],shipping_availability_human_confirmed:false})}><option value="available_now">Disponível agora</option><option value="available_from_date">Disponível a partir da data</option><option value="expected_by_date">Previsão até a data</option><option value="lead_time">Prazo em dias úteis</option><option value="unknown">Precisa revisar</option></select></label>{['available_from_date','expected_by_date','lead_time'].includes(preview.shipping_availability_kind??'')&&<label><span>DATA CALCULADA / INFORMADA</span><input type="date" value={preview.shipping_available_date??''} onChange={e=>setPreview({...preview,shipping_available_date:e.target.value||null,shipping_deadline_date:e.target.value||null,shipping_availability_human_confirmed:false})}/></label>}<small>{preview.shipping_available_date?`Data: ${shortDate(preview.shipping_available_date)}`:''}{preview.shipping_lead_business_days?` · ${preview.shipping_lead_business_days} dias úteis`:''}</small>{preview.shipping_availability_human_confirmed?<b>✓ DISPONIBILIDADE CONFIRMADA</b>:<button type="button" disabled={preview.shipping_availability_kind==='unknown'||(['available_from_date','expected_by_date','lead_time'].includes(preview.shipping_availability_kind??'')&&!preview.shipping_available_date)} onClick={()=>setPreview({...preview,shipping_availability_human_confirmed:true,shipping_deadline_date:preview.shipping_available_date??null})}>CONFIRMAR DISPONIBILIDADE</button>}</>}</section>
    <section><h4>CLIENTES E VENDAS</h4><div className="batch-quality"><span>{preview.summary.found} encontrados</span><span>{preview.summary.new} novos</span><span>{preview.summary.shipping_ready} prontos para envio</span><span>{preview.summary.shipping_incomplete} incompletos</span></div>{preview.source_format==='tsv'?preview.groups?.map((group,groupIndex)=><div className="batch-sales-group" key={group.normalized_perfume_name}><header><b>{String(groupIndex+1).padStart(2,'0')}</b><strong>{group.display_name}</strong><span>{group.totals.sales} vendas · {group.totals.volume_ml} ml</span></header>{preview.sales.map((sale,index)=>normalizeInventoryPerfumeName(sale.perfume_name)===group.normalized_perfume_name?saleCard(sale,index):null)}</div>):preview.sales.map(saleCard)}</section>
    {previewSummary&&<section className="batch-review-groups"><details><summary>PEDIDOS DESTA IMPORTAÇÃO <span>{countedLabel(previewSummary.sales,'venda','vendas')}</span></summary><div className="batch-review-card-list">{previewSummary.orders.map(order=><article key={order.index}><strong>{order.label}</strong><dl><div><dt>Cliente</dt><dd>{order.client}</dd></div><div><dt>Perfume</dt><dd>{order.perfume}</dd></div><div><dt>Tipo</dt><dd>{order.saleType}</dd></div><div><dt>Quantidade</dt><dd>{formatMl(order.volumeMl)}</dd></div><div><dt>Valor</dt><dd>{brl(order.amount)}</dd></div></dl></article>)}</div></details><details><summary>CLIENTES NESTE LOTE <span>{countedLabel(previewSummary.clients,'cliente','clientes')}</span></summary><div className="batch-aggregate-list">{previewSummary.byClient.map(client=><article key={client.key}><strong>{client.label}</strong><span>{countedLabel(client.sales,'venda','vendas')} · {formatMl(client.volumeMl)} · {brl(client.amount)}</span></article>)}</div></details><details><summary>PERFUMES DO LOTE <span>{countedLabel(previewSummary.byPerfume.length,'perfume resolvido','perfumes resolvidos')}</span></summary>{previewSummary.pendingPerfumes>0&&<p className="batch-review-pending">{countedLabel(previewSummary.pendingPerfumes,'perfume precisa','perfumes precisam')} de revisão.</p>}<div className="batch-aggregate-list">{previewSummary.byPerfume.map(perfume=><article key={perfume.key}><strong>{perfume.label}</strong><span>{countedLabel(perfume.sales,'venda','vendas')} · {formatMl(perfume.volumeMl)} · {brl(perfume.amount)}</span></article>)}</div></details></section>}
    {blockers.length>0&&<div className="batch-blockers"><AlertTriangle/><div><strong>IMPORTAÇÃO AINDA NÃO ESTÁ PRONTA</strong>{perfumePendingCount>0&&<span>{countedLabel(perfumePendingCount,'perfume precisa','perfumes precisam')} de revisão.</span>}{clientPendingCount>0&&<span>{clientPendingCount===1?'1 cliente precisa ser confirmado.':`${clientPendingCount} clientes precisam ser confirmados.`}</span>}{blockers.filter(b=>!b.target).map(x=><span key={x.text}>{x.text}</span>)}<button type="button" className="batch-blocker-goto" onClick={goToFirstPending}>IR PARA A PRIMEIRA PENDÊNCIA</button></div></div>}
    <footer>{previewSummary&&<div className="batch-confirm-summary"><strong>AO CONFIRMAR:</strong><span>{countedLabel(previewSummary.sales,'venda será criada','vendas serão criadas')}</span><span>{countedLabel(previewSummary.clients,'cliente envolvido','clientes envolvidos')}</span><span>{formatMl(previewSummary.volumeMl)} vendidos</span><span>{brl(previewSummary.amount)} em vendas</span>{preview.remaining_available_ml!==null&&<span>{formatMl(preview.remaining_available_ml)} entrarão no estoque canônico</span>}<small>Nenhuma remessa, etiqueta ou baixa física será criada.</small></div>}<div className="batch-confirm-actions"><button onClick={()=>{setPreview(null);setPhase('input')}}>VOLTAR</button><button className="primary" disabled={!!busy||blockers.length>0} onClick={confirm}>{busy==='confirm'?'CRIANDO…':`CRIAR ${previewSummary?.sales??preview.sales.length} VENDAS`}</button></div></footer></div>}
  {error&&<div className="form-error">{error}</div>}
  {bootstrap&&ambiguousCandidates&&<div className="batch-confirm-layer" role="dialog" aria-modal="true" aria-labelledby="ambiguous-title"><section><span>PRECISA CONFIRMAR O PERFUME</span><h3 id="ambiguous-title">{bootstrap.display_name}</h3><p>Encontramos mais de um cadastro deste perfume. Selecione qual registro corresponde a este lote:</p><div className="batch-candidate-list">{ambiguousCandidates.map(candidate=><label key={candidate.perfume_id} className="batch-candidate"><input type="radio" name="perfume-candidate" value={candidate.perfume_id} onChange={()=>createFromSales(candidate.perfume_id)} disabled={busy==='bootstrap'}/><div><strong>{candidate.name}</strong><span>{candidate.brand?`Marca: ${candidate.brand}`:'Marca não informada'}{candidate.bottle_identifier?` · ${candidate.bottle_identifier}`:''}</span><small>{candidate.inventory_item_id?`Já possui item de estoque${candidate.reconciliation_status==='review_required'?' (aguardando conferência)':''}`:'Sem item de estoque vinculado ainda'}</small></div></label>)}</div><footer><button onClick={closeBootstrap}>CANCELAR</button></footer></section></div>}
  {bootstrap&&!ambiguousCandidates&&<div className="batch-confirm-layer" role="dialog" aria-modal="true" aria-labelledby="bootstrap-title"><section><span>CATÁLOGO COMERCIAL</span><h3 id="bootstrap-title">RESOLVER PERFUME</h3><dl><dt>Perfume</dt><dd>{bootstrap.display_name}</dd><dt>Vendas reconhecidas</dt><dd>{bootstrap.totals.sales}</dd><dt>Volume vendido</dt><dd>{bootstrap.totals.volume_ml} ml</dd></dl><p>O CRM criará ou reutilizará somente o perfume de catálogo para vincular estas vendas.</p><div className="batch-bootstrap-warning"><AlertTriangle/> Nenhum estoque, saldo, movimento ou etiqueta será criado.</div><footer><button onClick={closeBootstrap}>CANCELAR</button><button className="primary" disabled={busy==='bootstrap'} onClick={()=>createFromSales()}>{busy==='bootstrap'?'RESOLVENDO…':'RESOLVER E VINCULAR'}</button></footer></section></div>}
  </section></div></div>
}
