import {useMemo,useRef,useState} from 'react'
import {AlertTriangle,Check,Loader2,Plus,Sparkles,X} from 'lucide-react'
import {brl,countedLabel,integer} from '../lib/format'
import {normalizeInventoryPerfumeName,reconcileInventoryGroup} from '../lib/ai-inventory'
import {AiImportSummary,buildAiImportSummarySentences} from '../lib/ai-import-summary'
import {buildAiImportPreviewSummary} from '../lib/ai-import-preview-summary'
import {AiSalesBatchGroup,AiSalesBatchMultiResult,AiSalesBatchPreview,bootstrapAiBatchInventory,confirmAiSalesBatch,confirmAiSalesBatchMulti,fetchOperationalInventory,OperationalInventoryRow,parseSalesBatch,PerfumeResolutionCandidate,summarizeAiBatchImport} from '../lib/records'

const today=()=>new Date().toISOString().slice(0,10)
const missingFields=['CPF','telefone','CEP','endereço','número','bairro','cidade','UF']
const formatMl=(value:number)=>`${value.toLocaleString('pt-BR',{maximumFractionDigits:3})} ml`

type Blocker={text:string;target?:string}
type Summary=AiImportSummary

function toSummary(preview:AiSalesBatchPreview,multi:AiSalesBatchMultiResult|null,single:{sales_created:number;clients_created:number;shipping_incomplete:number;idempotent?:boolean}|null):Summary{
  if(multi)return multi
  const created=single?.sales_created??0,clientsCreated=single?.clients_created??0
  const bootstrapped=preview.inventory?.reconciliation_status==='review_required'?1:0
  return{
    sales_created:created,clients_created:clientsCreated,clients_existing:Math.max(0,preview.sales.length-clientsCreated),
    perfumes_processed:1,perfumes_matched:bootstrapped?0:1,inventory_items_bootstrapped:bootstrapped,
    total_ml_sold:preview.totals.volume_ml,total_amount_sold:preview.totals.amount,
    commercial_remaining_ml:0,commercial_remaining_amount:0,
    shipping_incomplete:single?.shipping_incomplete??0,
    paid_source_count:0,awaiting_source_count:0,unstated_payment_count:preview.sales.length,
    idempotent:single?.idempotent??false,
  }
}

export function AiSalesBatchImport({close,completed}:{close:()=>void;completed:()=>void}){
  const [text,setText]=useState(''),[date,setDate]=useState(today()),[preview,setPreview]=useState<AiSalesBatchPreview|null>(null),[inventory,setInventory]=useState<OperationalInventoryRow[]>([]),[busy,setBusy]=useState(''),[error,setError]=useState(''),[bootstrap,setBootstrap]=useState<AiSalesBatchGroup|null>(null)
  const [ambiguousCandidates,setAmbiguousCandidates]=useState<PerfumeResolutionCandidate[]|null>(null)
  const openBootstrap=(group:AiSalesBatchGroup)=>{setAmbiguousCandidates(null);setBootstrap(group)}
  const closeBootstrap=()=>{setBootstrap(null);setAmbiguousCandidates(null)}
  const [phase,setPhase]=useState<'input'|'preview'|'processing'|'summary'|'failed'>('input')
  const [summary,setSummary]=useState<Summary|null>(null),[aiText,setAiText]=useState<string|null>(null),[aiPending,setAiPending]=useState(false),[confirmError,setConfirmError]=useState('')
  const scrollRef=useRef<HTMLDivElement|null>(null)

  const blockers=useMemo<Blocker[]>(()=>{
    if(!preview)return[]
    const list:Blocker[]=[]
    if(!preview.totals.volume_consistent)list.push({text:'Volumes do lote não conferem'})
    if(preview.source_format==='tsv'){
      for(const group of preview.groups??[])if(!group.inventory_item_id)list.push({text:`Perfume "${group.display_name||group.perfume}" precisa de resolução no estoque`,target:`group-${group.normalized_perfume_name}`})
    }else if(!preview.inventory_item_id)list.push({text:'Resolva o perfume no estoque da RUAH',target:'single-perfume'})
    preview.sales.forEach((sale,index)=>{if(sale.client_match_status==='review'||(!sale.client_id&&sale.client_match_status!=='new'))list.push({text:`Confirme quem é ${sale.client_name}`,target:`sale-${index}`})})
    preview.sales.forEach((sale,index)=>{if(sale.possible_duplicate)list.push({text:`Possível venda repetida para ${sale.client_name}`,target:`sale-${index}`})})
    if(preview.duplicate_batch)list.push({text:'Esta lista parece já ter sido importada'})
    return list
  },[preview])
  const perfumePendingCount=useMemo(()=>!preview?0:preview.source_format==='tsv'?(preview.groups??[]).filter(group=>!group.inventory_item_id).length:preview.inventory_item_id?0:1,[preview])
  const clientPendingCount=useMemo(()=>blockers.filter(b=>b.target?.startsWith('sale-')).length,[blockers])
  const previewSummary=useMemo(()=>preview?buildAiImportPreviewSummary(preview):null,[preview])

  const goToFirstPending=()=>{const target=blockers.find(b=>b.target)?.target;if(!target)return;document.getElementById(target)?.scrollIntoView({behavior:'smooth',block:'center'})}

  const analyze=async()=>{setBusy('analyze');setError('');try{const [parsed,items]=await Promise.all([parseSalesBatch(text,date),fetchOperationalInventory()]),sorted=[...items].sort((a,b)=>a.perfume.localeCompare(b.perfume,'pt-BR',{sensitivity:'base'})),groups=parsed.groups?.map(group=>reconcileInventoryGroup(group,sorted)),exact=sorted.filter(item=>item.perfume_id===parsed.perfume_id);setInventory(sorted);setPreview({...parsed,groups,inventory_item_id:exact.length===1?exact[0].item_id:parsed.inventory_item_id,inventory:exact.length===1?exact[0]:parsed.inventory,perfume_match_status:exact.length===1?'found':parsed.perfume_match_status});setPhase('preview')}catch(reason){setError(reason instanceof Error?reason.message:'Não foi possível analisar.')}finally{setBusy('')}}
  const chooseInventory=(itemId:string)=>{const item=inventory.find(row=>row.item_id===itemId);setPreview(current=>current?{...current,inventory_item_id:item?.item_id??null,perfume_id:item?.perfume_id??null,perfume:item?.perfume??current.perfume,inventory:item??null,perfume_match_status:item?'found':'review'}:current)}
  const chooseGroupInventory=(normalized:string,itemId:string)=>{const item=inventory.find(row=>row.item_id===itemId);setPreview(current=>current?{...current,groups:current.groups?.map(group=>group.normalized_perfume_name===normalized?{...group,inventory_item_id:item?.item_id??null,perfume_id:item?.perfume_id??null,inventory:item??null,perfume_match_status:item?'found':'review'}:group)}:current)}
  const chooseClient=(index:number,id:string)=>setPreview(current=>current?{...current,sales:current.sales.map((sale,i)=>i===index?{...sale,client_id:id||null,client_match_status:id?'found':'new',missing_shipping_fields:id?sale.suggestions.find(x=>x.id===id)?.missing_shipping_fields??[]:missingFields}:sale)}:current)
  const editSale=(index:number,field:'sale_type'|'volume_ml'|'amount',value:string)=>setPreview(current=>{if(!current)return current;const sales=current.sales.map((sale,i)=>i===index?{...sale,[field]:field==='sale_type'?value:Number(value),possible_duplicate:false}:sale),volume_ml=sales.reduce((sum,s)=>sum+s.volume_ml,0),amount=Math.round(sales.reduce((sum,s)=>sum+s.amount,0)*100)/100,calculated_balance_ml=current.original_volume_ml==null?null:current.original_volume_ml-volume_ml,volume_consistent=calculated_balance_ml==null||current.announced_balance_ml==null?true:Math.abs(calculated_balance_ml-current.announced_balance_ml)<.001;return{...current,sales,groups:current.groups?.map(group=>{const groupSales=sales.filter(sale=>normalizeInventoryPerfumeName(sale.perfume_name)===group.normalized_perfume_name);return{...group,sales:groupSales,totals:{sales:groupSales.length,volume_ml:groupSales.reduce((sum,sale)=>sum+sale.volume_ml,0),amount:Math.round(groupSales.reduce((sum,sale)=>sum+sale.amount,0)*100)/100}}}),totals:{...current.totals,volume_ml,amount,calculated_balance_ml,volume_consistent}}})

  const confirm=async()=>{
    if(!preview||blockers.length||busy)return
    setBusy('confirm');setConfirmError('');setPhase('processing')
    try{
      const multi=preview.source_format==='tsv'&&(preview.groups?.length??0)>0
      const outcome=multi?await confirmAiSalesBatchMulti(preview):await confirmAiSalesBatch(preview)
      const built=multi?toSummary(preview,outcome as AiSalesBatchMultiResult,null):toSummary(preview,null,outcome as {sales_created:number;clients_created:number;shipping_incomplete:number;idempotent?:boolean})
      setSummary(built);setPhase('summary');completed()
      setAiPending(true)
      summarizeAiBatchImport(buildAiImportSummarySentences(built)).then(text=>setAiText(text)).finally(()=>setAiPending(false))
    }catch(reason){setConfirmError(reason instanceof Error?reason.message:'Não foi possível concluir a importação.');setPhase('failed')}
    finally{setBusy('')}
  }
  const retry=()=>{setPhase('preview');setConfirmError('')}

  const createFromSales=async(selectedPerfumeId?:string)=>{if(!preview||!bootstrap)return;setBusy('bootstrap');setError('');try{
    const resolved=await bootstrapAiBatchInventory({fingerprint:preview.fingerprint,rawPerfumeName:bootstrap.raw_perfume_name,brand:bootstrap.brand,bottleNumber:bootstrap.bottle_number,referenceDate:preview.sale_date,sales:bootstrap.sales,selectedPerfumeId})
    if(resolved.resolution_status==='ambiguous'){setAmbiguousCandidates(resolved.candidates??[]);return}
    setAmbiguousCandidates(null)
    const fresh=await fetchOperationalInventory(),row=fresh.find(item=>item.item_id===resolved.inventory_item_id)
    if(!row)throw new Error('O item foi criado, mas não pôde ser recarregado. Atualize a análise.')
    setInventory(fresh);setPreview(current=>current?{...current,groups:current.groups?.map(group=>group.normalized_perfume_name===bootstrap.normalized_perfume_name?{...group,inventory_item_id:row.item_id,perfume_id:row.perfume_id,inventory:row,perfume_match_status:'found'}:group),...(current.source_format==='tsv'?{}:{inventory_item_id:row.item_id,perfume_id:row.perfume_id,inventory:row,perfume_match_status:'found'})}:current);setBootstrap(null)
  }catch(reason){setError(reason instanceof Error?reason.message:'Não foi possível criar o estoque provisório.')}finally{setBusy('')}}

  const saleCard=(sale:AiSalesBatchPreview['sales'][number],index:number)=><article className="batch-sale" id={`sale-${index}`} key={`${sale.client_name}-${index}`}><b>{String(index+1).padStart(2,'0')}</b><div><strong>{sale.client_name}</strong><div className="batch-sale-fields"><select aria-label={`Tipo de ${sale.client_name}`} value={sale.sale_type} onChange={e=>editSale(index,'sale_type',e.target.value)}><option>APC</option><option>SPLIT</option></select><input aria-label={`Volume de ${sale.client_name}`} type="number" min="0.001" step="0.001" value={sale.volume_ml} onChange={e=>editSale(index,'volume_ml',e.target.value)}/><input aria-label={`Valor de ${sale.client_name}`} type="number" min="0" step="0.01" value={sale.amount} onChange={e=>editSale(index,'amount',e.target.value)}/></div><small>Pagamento: aguardando confirmação{sale.possible_duplicate?' · ⚠ possível duplicidade':''}</small></div><label><span>CLIENTE NO CRM</span><select value={sale.client_id??''} onChange={e=>chooseClient(index,e.target.value)}><option value="">Criar novo cliente mínimo</option>{sale.suggestions.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><small>{sale.missing_shipping_fields.length?`Falta para envio: ${sale.missing_shipping_fields.join(', ')}`:'✓ Cadastro pronto para envio'}</small></label></article>
  const groupCard=(group:AiSalesBatchGroup)=><article key={group.normalized_perfume_name} id={`group-${group.normalized_perfume_name}`} className={`batch-perfume-card ${group.inventory_item_id?'found':group.perfume_match_status==='review'?'review':'missing'}`}><div><strong>{group.display_name||group.perfume}</strong><span>{group.totals.sales} vendas · {group.totals.volume_ml} ml · {brl(group.totals.amount)}</span>{group.bottle_number&&<small>Frasco {group.bottle_number}</small>}</div>{group.inventory_item_id?<div className="batch-perfume-state"><b>✓ NO ESTOQUE</b><span>{String(group.inventory?.perfume??group.display_name)}</span><small>{Number(group.inventory?.available_ml??0).toLocaleString('pt-BR')} ml registrados</small></div>:group.perfume_match_status==='review'?<div className="batch-perfume-state"><b>⚠ CONFIRMAR CORRESPONDÊNCIA</b><select aria-label={`Selecionar ${group.display_name}`} value="" onChange={e=>chooseGroupInventory(group.normalized_perfume_name,e.target.value)}><option value="">Selecionar perfume…</option>{inventory.map(item=><option key={item.item_id} value={item.item_id}>{item.perfume}</option>)}</select></div>:<div className="batch-perfume-state"><b>+ NÃO ESTÁ NO ESTOQUE</b><small>{group.totals.volume_ml} ml vendidos identificados</small><button type="button" onClick={()=>openBootstrap(group)}><Plus/> CRIAR A PARTIR DAS VENDAS</button></div>}</article>

  const grossTotal=summary?Math.round((summary.total_amount_sold+summary.commercial_remaining_amount)*100)/100:0
  const anyBootstrapped=!!summary&&summary.inventory_items_bootstrapped>0

  return <div className="ai-batch-layer"><div className="ai-batch-scroll" ref={scrollRef}><section className="ai-batch-assistant"><header><div><span>RUAH · ASSISTENTE OPERACIONAL</span><h2><Sparkles/> Importar lista com IA</h2><p>A IA interpreta. Você revisa. O CRM só grava depois da confirmação.</p></div><button aria-label="Fechar" onClick={close}><X/></button></header>

  {phase==='summary'&&summary?<div className="ai-batch-result"><Check/><span>IMPORTAÇÃO CONCLUÍDA</span><h3>{countedLabel(summary.sales_created,'venda registrada','vendas registradas')}</h3><p>{brl(summary.total_amount_sold)} em vendas · {countedLabel(summary.total_ml_sold,'ml vendido','ml vendidos')}{summary.idempotent?' · lote já havia sido importado':''}</p>
    {summary.commercial_remaining_ml>0&&<p className="batch-summary-note">{countedLabel(summary.commercial_remaining_ml,'ml permaneceu marcado','ml permaneceram marcados')} como disponíveis para venda, equivalentes a {brl(summary.commercial_remaining_amount)}. Total bruto da lista analisada: {brl(grossTotal)}.</p>}
    <dl className="batch-summary-grid">
      <div><dt>Clientes já existentes</dt><dd>{integer(summary.clients_existing)}</dd></div>
      <div><dt>Novos clientes criados</dt><dd>{integer(summary.clients_created)}</dd></div>
      <div><dt>Cadastros incompletos p/ envio</dt><dd>{integer(summary.shipping_incomplete)}</dd></div>
      <div><dt>Perfumes processados</dt><dd>{integer(summary.perfumes_processed)}</dd></div>
      <div><dt>Já existentes no estoque</dt><dd>{integer(summary.perfumes_matched)}</dd></div>
      <div><dt>Criados a partir das vendas</dt><dd>{integer(summary.inventory_items_bootstrapped)}</dd></div>
    </dl>
    {(summary.paid_source_count>0||summary.awaiting_source_count>0||summary.unstated_payment_count>0)&&<p className="batch-summary-note">Na lista original: {integer(summary.paid_source_count)} pagas · {integer(summary.awaiting_source_count)} aguardando · {integer(summary.unstated_payment_count)} sem status informado. Os status originais foram preservados para revisão. As vendas importadas entraram como pendentes conforme a regra atual do CRM.</p>}
    {anyBootstrapped&&<div className="batch-bootstrap-warning"><AlertTriangle/> {countedLabel(summary.inventory_items_bootstrapped,'perfume foi registrado','perfumes foram registrados')} a partir das vendas e precisam de conferência física antes de liberar estoque operacional.</div>}
    {aiPending?<p className="batch-summary-ai batch-summary-ai-loading"><Loader2 className="spin"/> Preparando resumo…</p>:<div className="batch-summary-ai"><span>RESUMO RUAH</span><p>{aiText??buildAiImportSummarySentences(summary).join(' ')}</p></div>}
    <div className="batch-summary-actions">
      <button className="primary" onClick={close}>VER VENDAS IMPORTADAS</button>
      {summary.shipping_incomplete>0&&<button onClick={()=>{history.pushState({},'','/clientes');dispatchEvent(new PopStateEvent('popstate'));close()}}>VER CLIENTES INCOMPLETOS</button>}
      {anyBootstrapped&&<button onClick={()=>{history.pushState({},'','/estoque');dispatchEvent(new PopStateEvent('popstate'));close()}}>VER ESTOQUE A CONFERIR</button>}
      <button onClick={close}>CONCLUIR</button>
    </div>
  </div>:phase==='processing'?<div className="ai-batch-result"><Loader2 className="spin"/><span>IMPORTANDO VENDAS</span><h3>Registrando clientes, perfumes e vendas.</h3><p>Não feche esta janela.</p></div>:phase==='failed'?<div className="ai-batch-result"><AlertTriangle/><span>NENHUMA VENDA FOI CRIADA</span><h3>Não foi possível concluir a importação</h3><p>Motivo: {confirmError}</p><p className="batch-summary-note">Como o write é atômico, nenhuma parte deste lote foi gravada.</p><button className="primary" onClick={retry}>TENTAR NOVAMENTE</button></div>:!preview?<div className="ai-batch-input"><label><span>DATA DAS VENDAS</span><input type="date" value={date} onChange={e=>setDate(e.target.value)}/><small>Pré-preenchida com hoje. Ajuste antes de analisar.</small></label><label><span>MENSAGEM DO DAVI</span><textarea value={text} onChange={e=>setText(e.target.value)} placeholder="Cole aqui a publicação completa…"/></label><div className="ai-batch-safety">Analisar não cria vendas, clientes, reservas, envios ou etiquetas.</div><button className="primary" disabled={!text.trim()||!!busy} onClick={analyze}>{busy?'ANALISANDO…':'ANALISAR LISTA'}</button></div>:<div className="ai-batch-preview">
    {previewSummary&&<section className="batch-review-summary" aria-labelledby="batch-review-summary-title"><h4 id="batch-review-summary-title">RESUMO DA IMPORTAÇÃO</h4><div className="batch-review-metrics"><article><strong>{integer(previewSummary.sales)}</strong><span>VENDAS / PEDIDOS</span></article><article><strong>{integer(previewSummary.clients)}</strong><span>{previewSummary.clients===1?'CLIENTE':'CLIENTES'}</span></article><article><strong>{formatMl(previewSummary.volumeMl)}</strong><span>VOLUME VENDIDO</span></article><article><strong>{brl(previewSummary.amount)}</strong><span>VALOR TOTAL</span></article></div></section>}
    <section className="batch-overview"><div><span>{preview.source_format==='tsv'?'IMPORTAÇÃO COM VÁRIOS LOTES':preview.perfume}</span><h3>{preview.source_format==='tsv'?`${preview.groups?.length??0} perfumes encontrados`:`FRASCO ${preview.bottle_number??'—'}`}</h3><p>{preview.totals.sales} vendas · {preview.totals.volume_ml} ml · {brl(preview.totals.amount)}{preview.availability_rows?` · ${preview.availability_rows} saldos comerciais`:''}</p></div><div className={preview.totals.volume_consistent?'ok':'warning'}><strong>{preview.groups?.length??1}</strong><span>lotes</span><strong>{preview.totals.sales}</strong><span>vendas</span><strong>{preview.totals.volume_ml} ml</strong><span>volume</span></div></section>
    {preview.source_format==='tsv'?<section className="batch-match"><h4>PERFUMES</h4><div className="batch-group-list">{preview.groups?.map(groupCard)}</div><small>O saldo “Disponível para venda” permanece separado e não altera o estoque físico.</small></section>:<section id="single-perfume" className="batch-match"><h4>PERFUME NO ESTOQUE</h4><select aria-label="Buscar ou selecionar perfume do estoque" value={preview.inventory_item_id??''} onChange={e=>chooseInventory(e.target.value)}><option value="">Buscar ou selecionar perfume…</option>{inventory.map(item=><option key={item.item_id} value={item.item_id}>{item.perfume} — {Number(item.available_ml).toLocaleString('pt-BR')} ml disponíveis</option>)}</select><small>{preview.inventory_item_id?'✓ Item canônico do estoque selecionado.':'Selecione o perfume correspondente ou crie a partir das vendas reconhecidas.'}</small>{!preview.inventory_item_id&&preview.perfume_match_status==='new'&&<button className="batch-create-single" type="button" onClick={()=>openBootstrap({perfume:preview.perfume,raw_perfume_name:preview.raw_perfume_name??preview.perfume,normalized_perfume_name:preview.normalized_perfume_name??normalizeInventoryPerfumeName(preview.perfume),display_name:preview.display_name??preview.perfume,brand:preview.brand??null,bottle_number:preview.bottle_number,inventory_item_id:null,perfume_id:preview.perfume_id,perfume_match_status:'new',perfume_matches:preview.perfume_matches,inventory:null,sales:preview.sales,availability_rows:preview.availability_rows??0,totals:{sales:preview.totals.sales,volume_ml:preview.totals.volume_ml,amount:preview.totals.amount}})}><Plus/> CRIAR A PARTIR DESTAS VENDAS</button>}</section>}
    <section className="batch-dates"><label><span>DATA DAS VENDAS</span><input type="date" value={preview.sale_date} onChange={e=>setPreview({...preview,sale_date:e.target.value})}/></label><label><span>DISPONÍVEL PARA ENVIO</span><input type="date" value={preview.shipping_deadline_date??''} onChange={e=>setPreview({...preview,shipping_deadline_date:e.target.value||null})}/></label><small>{preview.deadline_raw??'Prazo não informado'}</small></section>
    <section><h4>CLIENTES E VENDAS</h4><div className="batch-quality"><span>{preview.summary.found} encontrados</span><span>{preview.summary.new} novos</span><span>{preview.summary.shipping_ready} prontos para envio</span><span>{preview.summary.shipping_incomplete} incompletos</span></div>{preview.source_format==='tsv'?preview.groups?.map((group,groupIndex)=><div className="batch-sales-group" key={group.normalized_perfume_name}><header><b>{String(groupIndex+1).padStart(2,'0')}</b><strong>{group.display_name}</strong><span>{group.totals.sales} vendas · {group.totals.volume_ml} ml</span></header>{preview.sales.map((sale,index)=>normalizeInventoryPerfumeName(sale.perfume_name)===group.normalized_perfume_name?saleCard(sale,index):null)}</div>):preview.sales.map(saleCard)}</section>
    {previewSummary&&<section className="batch-review-groups"><details><summary>PEDIDOS DESTA IMPORTAÇÃO <span>{countedLabel(previewSummary.sales,'venda','vendas')}</span></summary><div className="batch-review-card-list">{previewSummary.orders.map(order=><article key={order.index}><strong>{order.label}</strong><dl><div><dt>Cliente</dt><dd>{order.client}</dd></div><div><dt>Perfume</dt><dd>{order.perfume}</dd></div><div><dt>Tipo</dt><dd>{order.saleType}</dd></div><div><dt>Quantidade</dt><dd>{formatMl(order.volumeMl)}</dd></div><div><dt>Valor</dt><dd>{brl(order.amount)}</dd></div></dl></article>)}</div></details><details><summary>CLIENTES NESTE LOTE <span>{countedLabel(previewSummary.clients,'cliente','clientes')}</span></summary><div className="batch-aggregate-list">{previewSummary.byClient.map(client=><article key={client.key}><strong>{client.label}</strong><span>{countedLabel(client.sales,'venda','vendas')} · {formatMl(client.volumeMl)} · {brl(client.amount)}</span></article>)}</div></details><details><summary>PERFUMES DO LOTE <span>{countedLabel(previewSummary.byPerfume.length,'perfume resolvido','perfumes resolvidos')}</span></summary>{previewSummary.pendingPerfumes>0&&<p className="batch-review-pending">{countedLabel(previewSummary.pendingPerfumes,'perfume precisa','perfumes precisam')} de revisão.</p>}<div className="batch-aggregate-list">{previewSummary.byPerfume.map(perfume=><article key={perfume.key}><strong>{perfume.label}</strong><span>{countedLabel(perfume.sales,'venda','vendas')} · {formatMl(perfume.volumeMl)} · {brl(perfume.amount)}</span></article>)}</div></details></section>}
    {blockers.length>0&&<div className="batch-blockers"><AlertTriangle/><div><strong>IMPORTAÇÃO AINDA NÃO ESTÁ PRONTA</strong>{perfumePendingCount>0&&<span>{countedLabel(perfumePendingCount,'perfume precisa','perfumes precisam')} de revisão.</span>}{clientPendingCount>0&&<span>{clientPendingCount===1?'1 cliente precisa ser confirmado.':`${clientPendingCount} clientes precisam ser confirmados.`}</span>}{blockers.filter(b=>!b.target).map(x=><span key={x.text}>{x.text}</span>)}<button type="button" className="batch-blocker-goto" onClick={goToFirstPending}>IR PARA A PRIMEIRA PENDÊNCIA</button></div></div>}
    <footer>{previewSummary&&<div className="batch-confirm-summary"><strong>AO CONFIRMAR:</strong><span>{countedLabel(previewSummary.sales,'venda será criada','vendas serão criadas')}</span><span>{countedLabel(previewSummary.clients,'cliente envolvido','clientes envolvidos')}</span><span>{formatMl(previewSummary.volumeMl)} vendidos</span><span>{brl(previewSummary.amount)} em vendas</span><small>Nenhuma remessa, etiqueta ou baixa física será criada.</small></div>}<div className="batch-confirm-actions"><button onClick={()=>{setPreview(null);setPhase('input')}}>VOLTAR</button><button className="primary" disabled={!!busy||blockers.length>0} onClick={confirm}>{busy==='confirm'?'CRIANDO…':`CRIAR ${previewSummary?.sales??preview.sales.length} VENDAS`}</button></div></footer></div>}
  {error&&<div className="form-error">{error}</div>}
  {bootstrap&&ambiguousCandidates&&<div className="batch-confirm-layer" role="dialog" aria-modal="true" aria-labelledby="ambiguous-title"><section><span>PRECISA CONFIRMAR O PERFUME</span><h3 id="ambiguous-title">{bootstrap.display_name}</h3><p>Encontramos mais de um cadastro deste perfume. Selecione qual registro corresponde a este lote:</p><div className="batch-candidate-list">{ambiguousCandidates.map(candidate=><label key={candidate.perfume_id} className="batch-candidate"><input type="radio" name="perfume-candidate" value={candidate.perfume_id} onChange={()=>createFromSales(candidate.perfume_id)} disabled={busy==='bootstrap'}/><div><strong>{candidate.name}</strong><span>{candidate.brand?`Marca: ${candidate.brand}`:'Marca não informada'}{candidate.bottle_identifier?` · ${candidate.bottle_identifier}`:''}</span><small>{candidate.inventory_item_id?`Já possui item de estoque${candidate.reconciliation_status==='review_required'?' (aguardando conferência)':''}`:'Sem item de estoque vinculado ainda'}</small></div></label>)}</div><footer><button onClick={closeBootstrap}>CANCELAR</button></footer></section></div>}
  {bootstrap&&!ambiguousCandidates&&<div className="batch-confirm-layer" role="dialog" aria-modal="true" aria-labelledby="bootstrap-title"><section><span>ESTOQUE A CONFERIR</span><h3 id="bootstrap-title">CRIAR PERFUME NO ESTOQUE</h3><dl><dt>Perfume</dt><dd>{bootstrap.display_name}</dd><dt>Vendas reconhecidas</dt><dd>{bootstrap.totals.sales}</dd><dt>Volume vendido nesta lista</dt><dd>{bootstrap.totals.volume_ml} ml</dd></dl><p>Como o estoque físico ainda não foi cadastrado, o CRM registrará somente o volume mínimo comprovado por estas vendas.</p><div className="batch-bootstrap-warning"><AlertTriangle/> Este estoque ficará aguardando conferência física.</div><footer><button onClick={closeBootstrap}>CANCELAR</button><button className="primary" disabled={busy==='bootstrap'} onClick={()=>createFromSales()}>{busy==='bootstrap'?'CRIANDO…':'CRIAR E VINCULAR'}</button></footer></section></div>}
  </section></div></div>
}
