import {useMemo,useState} from 'react'
import {AlertTriangle,Check,Plus,Sparkles,X} from 'lucide-react'
import {brl} from '../lib/format'
import {normalizeInventoryPerfumeName,reconcileInventoryGroup} from '../lib/ai-inventory'
import {AiSalesBatchGroup,AiSalesBatchPreview,bootstrapAiBatchInventory,confirmAiSalesBatch,fetchOperationalInventory,OperationalInventoryRow,parseSalesBatch} from '../lib/records'

const today=()=>new Date().toISOString().slice(0,10)
const missingFields=['CPF','telefone','CEP','endereço','número','bairro','cidade','UF']

export function AiSalesBatchImport({close,completed}:{close:()=>void;completed:()=>void}){
  const [text,setText]=useState(''),[date,setDate]=useState(today()),[preview,setPreview]=useState<AiSalesBatchPreview|null>(null),[inventory,setInventory]=useState<OperationalInventoryRow[]>([]),[busy,setBusy]=useState(''),[error,setError]=useState(''),[result,setResult]=useState<{sales_created:number;clients_created:number;shipping_incomplete:number}|null>(null),[bootstrap,setBootstrap]=useState<AiSalesBatchGroup|null>(null)
  const blockers=useMemo(()=>preview?[!preview.totals.volume_consistent?'Volumes do lote não conferem':null,preview.source_format==='tsv'&&(preview.groups?.length??0)>1?'A criação multiperfume transacional ainda não está habilitada.':null,preview.source_format!=='tsv'&&!preview.inventory_item_id?'Resolva o perfume no estoque da RUAH':null,...preview.sales.filter(x=>x.client_match_status==='review'||(!x.client_id&&x.client_match_status!=='new')).map(x=>`Confirme quem é ${x.client_name}`),...preview.sales.filter(x=>x.possible_duplicate).map(x=>`Possível venda repetida para ${x.client_name}`),preview.duplicate_batch?'Esta lista parece já ter sido importada':null].filter(Boolean) as string[]:[],[preview])
  const analyze=async()=>{setBusy('analyze');setError('');try{const [parsed,items]=await Promise.all([parseSalesBatch(text,date),fetchOperationalInventory()]),sorted=[...items].sort((a,b)=>a.perfume.localeCompare(b.perfume,'pt-BR',{sensitivity:'base'})),groups=parsed.groups?.map(group=>reconcileInventoryGroup(group,sorted)),exact=sorted.filter(item=>item.perfume_id===parsed.perfume_id);setInventory(sorted);setPreview({...parsed,groups,inventory_item_id:exact.length===1?exact[0].item_id:parsed.inventory_item_id,inventory:exact.length===1?exact[0]:parsed.inventory,perfume_match_status:exact.length===1?'found':parsed.perfume_match_status})}catch(reason){setError(reason instanceof Error?reason.message:'Não foi possível analisar.')}finally{setBusy('')}}
  const chooseInventory=(itemId:string)=>{const item=inventory.find(row=>row.item_id===itemId);setPreview(current=>current?{...current,inventory_item_id:item?.item_id??null,perfume_id:item?.perfume_id??null,perfume:item?.perfume??current.perfume,inventory:item??null,perfume_match_status:item?'found':'review'}:current)}
  const chooseGroupInventory=(normalized:string,itemId:string)=>{const item=inventory.find(row=>row.item_id===itemId);setPreview(current=>current?{...current,groups:current.groups?.map(group=>group.normalized_perfume_name===normalized?{...group,inventory_item_id:item?.item_id??null,perfume_id:item?.perfume_id??null,inventory:item??null,perfume_match_status:item?'found':'review'}:group)}:current)}
  const chooseClient=(index:number,id:string)=>setPreview(current=>current?{...current,sales:current.sales.map((sale,i)=>i===index?{...sale,client_id:id||null,client_match_status:id?'found':'new',missing_shipping_fields:id?sale.suggestions.find(x=>x.id===id)?.missing_shipping_fields??[]:missingFields}:sale)}:current)
  const editSale=(index:number,field:'sale_type'|'volume_ml'|'amount',value:string)=>setPreview(current=>{if(!current)return current;const sales=current.sales.map((sale,i)=>i===index?{...sale,[field]:field==='sale_type'?value:Number(value),possible_duplicate:false}:sale),volume_ml=sales.reduce((sum,s)=>sum+s.volume_ml,0),amount=Math.round(sales.reduce((sum,s)=>sum+s.amount,0)*100)/100,calculated_balance_ml=current.original_volume_ml==null?null:current.original_volume_ml-volume_ml,volume_consistent=calculated_balance_ml==null||current.announced_balance_ml==null?true:Math.abs(calculated_balance_ml-current.announced_balance_ml)<.001;return{...current,sales,groups:current.groups?.map(group=>{const groupSales=sales.filter(sale=>normalizeInventoryPerfumeName(sale.perfume_name)===group.normalized_perfume_name);return{...group,sales:groupSales,totals:{sales:groupSales.length,volume_ml:groupSales.reduce((sum,sale)=>sum+sale.volume_ml,0),amount:Math.round(groupSales.reduce((sum,sale)=>sum+sale.amount,0)*100)/100}}}),totals:{...current.totals,volume_ml,amount,calculated_balance_ml,volume_consistent}}})
  const confirm=async()=>{if(!preview||blockers.length)return;setBusy('confirm');setError('');try{setResult(await confirmAiSalesBatch(preview));completed()}catch(reason){setError(reason instanceof Error?reason.message:'Não foi possível criar o lote.')}finally{setBusy('')}}
  const createFromSales=async()=>{if(!preview||!bootstrap)return;setBusy('bootstrap');setError('');try{const resolved=await bootstrapAiBatchInventory({fingerprint:preview.fingerprint,rawPerfumeName:bootstrap.raw_perfume_name,brand:bootstrap.brand,bottleNumber:bootstrap.bottle_number,referenceDate:preview.sale_date,sales:bootstrap.sales}),fresh=await fetchOperationalInventory(),row=fresh.find(item=>item.item_id===resolved.inventory_item_id);if(!row)throw new Error('O item foi criado, mas não pôde ser recarregado. Atualize a análise.');setInventory(fresh);setPreview(current=>current?{...current,groups:current.groups?.map(group=>group.normalized_perfume_name===bootstrap.normalized_perfume_name?{...group,inventory_item_id:row.item_id,perfume_id:row.perfume_id,inventory:row,perfume_match_status:'found'}:group),...(current.source_format==='tsv'?{}:{inventory_item_id:row.item_id,perfume_id:row.perfume_id,inventory:row,perfume_match_status:'found'})}:current);setBootstrap(null)}catch(reason){setError(reason instanceof Error?reason.message:'Não foi possível criar o estoque provisório.')}finally{setBusy('')}}

  const saleCard=(sale:AiSalesBatchPreview['sales'][number],index:number)=><article className="batch-sale" key={`${sale.client_name}-${index}`}><b>{String(index+1).padStart(2,'0')}</b><div><strong>{sale.client_name}</strong><div className="batch-sale-fields"><select aria-label={`Tipo de ${sale.client_name}`} value={sale.sale_type} onChange={e=>editSale(index,'sale_type',e.target.value)}><option>APC</option><option>SPLIT</option></select><input aria-label={`Volume de ${sale.client_name}`} type="number" min="0.001" step="0.001" value={sale.volume_ml} onChange={e=>editSale(index,'volume_ml',e.target.value)}/><input aria-label={`Valor de ${sale.client_name}`} type="number" min="0" step="0.01" value={sale.amount} onChange={e=>editSale(index,'amount',e.target.value)}/></div><small>Pagamento: aguardando confirmação{sale.possible_duplicate?' · ⚠ possível duplicidade':''}</small></div><label><span>CLIENTE NO CRM</span><select value={sale.client_id??''} onChange={e=>chooseClient(index,e.target.value)}><option value="">Criar novo cliente mínimo</option>{sale.suggestions.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><small>{sale.missing_shipping_fields.length?`Falta para envio: ${sale.missing_shipping_fields.join(', ')}`:'✓ Cadastro pronto para envio'}</small></label></article>
  const groupCard=(group:AiSalesBatchGroup)=><article key={group.normalized_perfume_name} className={`batch-perfume-card ${group.inventory_item_id?'found':group.perfume_match_status==='review'?'review':'missing'}`}><div><strong>{group.display_name||group.perfume}</strong><span>{group.totals.sales} vendas · {group.totals.volume_ml} ml · {brl(group.totals.amount)}</span>{group.bottle_number&&<small>Frasco {group.bottle_number}</small>}</div>{group.inventory_item_id?<div className="batch-perfume-state"><b>✓ NO ESTOQUE</b><span>{String(group.inventory?.perfume??group.display_name)}</span><small>{Number(group.inventory?.available_ml??0).toLocaleString('pt-BR')} ml registrados</small></div>:group.perfume_match_status==='review'?<div className="batch-perfume-state"><b>⚠ CONFIRMAR CORRESPONDÊNCIA</b><select aria-label={`Selecionar ${group.display_name}`} value="" onChange={e=>chooseGroupInventory(group.normalized_perfume_name,e.target.value)}><option value="">Selecionar perfume…</option>{inventory.map(item=><option key={item.item_id} value={item.item_id}>{item.perfume}</option>)}</select></div>:<div className="batch-perfume-state"><b>+ NÃO ESTÁ NO ESTOQUE</b><small>{group.totals.volume_ml} ml vendidos identificados</small><button type="button" onClick={()=>setBootstrap(group)}><Plus/> CRIAR A PARTIR DAS VENDAS</button></div>}</article>

  return <div className="ai-batch-layer"><section className="ai-batch-assistant"><header><div><span>RUAH · ASSISTENTE OPERACIONAL</span><h2><Sparkles/> Importar lista com IA</h2><p>A IA interpreta. Você revisa. O CRM só grava depois da confirmação.</p></div><button aria-label="Fechar" onClick={close}><X/></button></header>{result?<div className="ai-batch-result"><Check/><span>LOTE IMPORTADO</span><h3>{result.sales_created} vendas criadas</h3><p>{result.clients_created} clientes novos · {result.shipping_incomplete} cadastros precisam ser completados.</p><button onClick={close}>VER VENDAS</button></div>:!preview?<div className="ai-batch-input"><label><span>DATA DAS VENDAS</span><input type="date" value={date} onChange={e=>setDate(e.target.value)}/><small>Pré-preenchida com hoje. Ajuste antes de analisar.</small></label><label><span>MENSAGEM DO DAVI</span><textarea value={text} onChange={e=>setText(e.target.value)} placeholder="Cole aqui a publicação completa…"/></label><div className="ai-batch-safety">Analisar não cria vendas, clientes, reservas, envios ou etiquetas.</div><button className="primary" disabled={!text.trim()||!!busy} onClick={analyze}>{busy?'ANALISANDO…':'ANALISAR LISTA'}</button></div>:<div className="ai-batch-preview">
    <section className="batch-overview"><div><span>{preview.source_format==='tsv'?'IMPORTAÇÃO COM VÁRIOS LOTES':preview.perfume}</span><h3>{preview.source_format==='tsv'?`${preview.groups?.length??0} perfumes encontrados`:`FRASCO ${preview.bottle_number??'—'}`}</h3><p>{preview.totals.sales} vendas · {preview.totals.volume_ml} ml · {brl(preview.totals.amount)}{preview.availability_rows?` · ${preview.availability_rows} saldos comerciais`:''}</p></div><div className={preview.totals.volume_consistent?'ok':'warning'}><strong>{preview.groups?.length??1}</strong><span>lotes</span><strong>{preview.totals.sales}</strong><span>vendas</span><strong>{preview.totals.volume_ml} ml</strong><span>volume</span></div></section>
    {preview.source_format==='tsv'?<section className="batch-match"><h4>PERFUMES</h4><div className="batch-group-list">{preview.groups?.map(groupCard)}</div><small>O saldo “Disponível para venda” permanece separado e não altera o estoque físico.</small></section>:<section className="batch-match"><h4>PERFUME NO ESTOQUE</h4><select aria-label="Buscar ou selecionar perfume do estoque" value={preview.inventory_item_id??''} onChange={e=>chooseInventory(e.target.value)}><option value="">Buscar ou selecionar perfume…</option>{inventory.map(item=><option key={item.item_id} value={item.item_id}>{item.perfume} — {Number(item.available_ml).toLocaleString('pt-BR')} ml disponíveis</option>)}</select><small>{preview.inventory_item_id?'✓ Item canônico do estoque selecionado.':'Selecione o perfume correspondente ou crie a partir das vendas reconhecidas.'}</small>{!preview.inventory_item_id&&preview.perfume_match_status==='new'&&<button className="batch-create-single" type="button" onClick={()=>setBootstrap({perfume:preview.perfume,raw_perfume_name:preview.raw_perfume_name??preview.perfume,normalized_perfume_name:preview.normalized_perfume_name??normalizeInventoryPerfumeName(preview.perfume),display_name:preview.display_name??preview.perfume,brand:preview.brand??null,bottle_number:preview.bottle_number,inventory_item_id:null,perfume_id:preview.perfume_id,perfume_match_status:'new',perfume_matches:preview.perfume_matches,inventory:null,sales:preview.sales,availability_rows:preview.availability_rows??0,totals:{sales:preview.totals.sales,volume_ml:preview.totals.volume_ml,amount:preview.totals.amount}})}><Plus/> CRIAR A PARTIR DESTAS VENDAS</button>}</section>}
    <section className="batch-dates"><label><span>DATA DAS VENDAS</span><input type="date" value={preview.sale_date} onChange={e=>setPreview({...preview,sale_date:e.target.value})}/></label><label><span>DISPONÍVEL PARA ENVIO</span><input type="date" value={preview.shipping_deadline_date??''} onChange={e=>setPreview({...preview,shipping_deadline_date:e.target.value||null})}/><small>{preview.deadline_raw??'Prazo não informado'}</small></label></section>
    <section><h4>CLIENTES E VENDAS</h4><div className="batch-quality"><span>{preview.summary.found} encontrados</span><span>{preview.summary.new} novos</span><span>{preview.summary.shipping_ready} prontos para envio</span><span>{preview.summary.shipping_incomplete} incompletos</span></div>{preview.source_format==='tsv'?preview.groups?.map((group,groupIndex)=><div className="batch-sales-group" key={group.normalized_perfume_name}><header><b>{String(groupIndex+1).padStart(2,'0')}</b><strong>{group.display_name}</strong><span>{group.totals.sales} vendas · {group.totals.volume_ml} ml</span></header>{preview.sales.map((sale,index)=>normalizeInventoryPerfumeName(sale.perfume_name)===group.normalized_perfume_name?saleCard(sale,index):null)}</div>):preview.sales.map(saleCard)}</section>
    {blockers.length>0&&<div className="batch-blockers"><AlertTriangle/><div><strong>REVISÃO NECESSÁRIA</strong>{blockers.map(x=><span key={x}>{x}</span>)}</div></div>}<footer><p>Serão criadas {preview.sales.length} vendas pendentes. Nenhuma remessa, etiqueta ou baixa física será criada.</p><button onClick={()=>setPreview(null)}>VOLTAR</button><button className="primary" disabled={!!busy||blockers.length>0} onClick={confirm}>{busy==='confirm'?'CRIANDO…':`CRIAR ${preview.sales.length} VENDAS`}</button></footer></div>}{error&&<div className="form-error">{error}</div>}
    {bootstrap&&<div className="batch-confirm-layer" role="dialog" aria-modal="true" aria-labelledby="bootstrap-title"><section><span>ESTOQUE A CONFERIR</span><h3 id="bootstrap-title">CRIAR PERFUME NO ESTOQUE</h3><dl><dt>Perfume</dt><dd>{bootstrap.display_name}</dd><dt>Vendas reconhecidas</dt><dd>{bootstrap.totals.sales}</dd><dt>Volume vendido nesta lista</dt><dd>{bootstrap.totals.volume_ml} ml</dd></dl><p>Como o estoque físico ainda não foi cadastrado, o CRM registrará somente o volume mínimo comprovado por estas vendas.</p><div className="batch-bootstrap-warning"><AlertTriangle/> Este estoque ficará aguardando conferência física.</div><footer><button onClick={()=>setBootstrap(null)}>CANCELAR</button><button className="primary" disabled={busy==='bootstrap'} onClick={createFromSales}>{busy==='bootstrap'?'CRIANDO…':'CRIAR E VINCULAR'}</button></footer></section></div>}
  </section></div>
}
