import{useMemo,useRef,useState}from'react'
import{AlertTriangle,CheckCircle2,ChevronRight,Database,FileSpreadsheet,Info,LoaderCircle,RefreshCw,ShieldCheck,Upload,XCircle}from'lucide-react'
import{analyzeCurrentCrmState,analyzeDaviFile,CrmFinding,CurrentCrmDiagnostic,DaviDiagnosticReport,DaviDiagnosticRow,safeDaviRows}from'../lib/davi-import-diagnostics'
import{dateTime,shortDate}from'../lib/format'
import{useToast}from'./ui'
import'./DaviImportDiagnostics.css'

const money=(value:number|null)=>value==null?'—':new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(value)
const confidence=(value:number)=>`${Math.round(value*100)}%`
const displayStructuredDates=(value:unknown):unknown=>Array.isArray(value)?value.map(displayStructuredDates):value&&typeof value==='object'?Object.fromEntries(Object.entries(value).map(([key,item])=>[key,displayStructuredDates(item)])):typeof value==='string'&&/^\d{4}-\d{2}-\d{2}T/.test(value)?dateTime(value):typeof value==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(value)?shortDate(value):value

function SourceFields({row}:{row:DaviDiagnosticRow}){return <dl><div><dt>Cliente</dt><dd>{row.client||'—'}</dd></div><div><dt>Perfume</dt><dd>{row.perfume||'—'}</dd></div><div><dt>Data</dt><dd>{shortDate(row.date)}</dd></div><div><dt>Tipo</dt><dd>{row.type?.toUpperCase()||'—'}</dd></div><div><dt>ML</dt><dd>{row.ml??'—'}</dd></div><div><dt>Valor</dt><dd>{money(row.amount)}</dd></div></dl>}

function ReviewRows({rows,kind}:{rows:DaviDiagnosticRow[];kind:'duplicate'|'perfume'|'value'|'invalid'}){
 return <div className="davi-diagnostic-list">{rows.map(row=><article key={`${kind}-${row.source_row}`}>
  <header><strong>Linha {row.source_row}</strong><span>{row.reason}</span>{row.confidence>0&&<small>Confiança {confidence(row.confidence)}</small>}</header>
  <div className="davi-diagnostic-compare"><section><h5>PLANILHA</h5><SourceFields row={row}/></section>{kind!=='invalid'&&<section><h5>CRM</h5>{row.existing_matches?.length?row.existing_matches.map(candidate=><dl key={candidate.sale_id}><div><dt>Venda candidata</dt><dd>{candidate.sale_id.slice(0,8)}…</dd></div><div><dt>Cliente</dt><dd>{candidate.client}</dd></div><div><dt>Perfume</dt><dd>{candidate.perfume}</dd></div><div><dt>Data</dt><dd>{shortDate(candidate.date)}</dd></div><div><dt>Tipo / ML</dt><dd>{candidate.type.toUpperCase()} · {candidate.ml} ml</dd></div><div><dt>Valor</dt><dd>{money(candidate.amount)}</dd></div></dl>):<p>Nenhuma venda candidata inequívoca.</p>}</section>}</div>
  <footer><b>Ação recomendada:</b> deixar para revisão. Nenhuma alteração automática será feita.</footer>
 </article>)}</div>
}

function Metric({tone,label,value}:{tone:'ok'|'new'|'warn'|'bad';label:string;value:number}){return <div className={`davi-diagnostic-metric ${tone}`}><strong>{value.toLocaleString('pt-BR')}</strong><span>{label}</span></div>}

const severityTone:Record<CrmFinding['severity'],'bad'|'warn'|'new'|'ok'>={CRITICAL:'bad',WARNING:'warn',REVIEW:'warn',INFO:'new'}
function FindingList({findings}:{findings:CrmFinding[]}){return <div className="davi-current-findings">{findings.map(item=><article key={item.id} data-severity={item.severity}><header><span>{item.severity}</span><code>{item.code}</code>{item.sale_id&&<small>Venda {item.sale_id.slice(0,8)}…</small>}</header><h5>{item.title}</h5><p>{item.reason}</p><details><summary>Ver dados estruturados</summary><div><section><b>Esperado</b><pre>{JSON.stringify(displayStructuredDates(item.expected),null,2)}</pre></section><section><b>Encontrado</b><pre>{JSON.stringify(displayStructuredDates(item.actual),null,2)}</pre></section></div></details></article>)}</div>}

export function DaviImportDiagnostics(){
 const toast=useToast(),input=useRef<HTMLInputElement>(null),[file,setFile]=useState<File|null>(null),[report,setReport]=useState<DaviDiagnosticReport|null>(null),[loading,setLoading]=useState(false),[error,setError]=useState(''),[current,setCurrent]=useState<CurrentCrmDiagnostic|null>(null),[currentLoading,setCurrentLoading]=useState(false),[currentError,setCurrentError]=useState('')
 const groups=useMemo(()=>{const rows=report?.rows??[];return{duplicates:rows.filter(row=>row.identity_classification==='PROBABLE_DUPLICATE'),perfume:rows.filter(row=>row.identity_classification==='CONFLICT'&&row.reason.toLowerCase().includes('perfume')),value:rows.filter(row=>row.identity_classification==='CONFLICT'&&row.reason.toLowerCase().includes('valor')),otherConflicts:rows.filter(row=>row.identity_classification==='CONFLICT'&&!/perfume|valor/i.test(row.reason)),invalid:rows.filter(row=>row.identity_classification==='INVALID')}},[report])
 const safe=report?safeDaviRows(report):[]
 const analyze=async()=>{if(!file)return;setLoading(true);setError('');setReport(null);try{const result=await analyzeDaviFile(file);setReport(result);toast.push(`${result.total_lines.toLocaleString('pt-BR')} linhas analisadas sem alterar o CRM.`,{tone:'success'})}catch(reason){const message=reason instanceof Error?reason.message:'Não foi possível analisar a planilha.';setError(message);toast.push(message,{tone:'error'})}finally{setLoading(false)}}
 const verifyCurrent=async()=>{setCurrentLoading(true);setCurrentError('');try{const result=await analyzeCurrentCrmState();setCurrent(result);toast.push('Diagnóstico atual concluído sem alterar o CRM.',{tone:'success'})}catch(reason){const message=reason instanceof Error?reason.message:'Não foi possível verificar o CRM.';setCurrentError(message);toast.push(message,{tone:'error'})}finally{setCurrentLoading(false)}}
 const currentGroups=useMemo(()=>{const findings=current?.findings??[];return{duplicates:findings.filter(item=>item.category==='duplicates'),perfumes:findings.filter(item=>item.category==='perfumes'),inventory:findings.filter(item=>item.category==='inventory'),references:findings.filter(item=>item.category==='references'),commercial:findings.filter(item=>item.category==='commercial')}},[current])
 return <section className="davi-diagnostic" aria-label="Diagnóstico operacional do Davi Excel">
  <header><div><span>DIAGNÓSTICO OPERACIONAL</span><h2>Consistência do CRM</h2><p>Verifique a base atual ou analise uma nova planilha. Nenhuma dessas ações altera dados.</p></div><Database/></header>
  <section className="davi-current-check"><div><span>CRM ATUAL</span><h3>Verificar inconsistências</h3><p>Analisa vendas, referências, perfumes, estoque, alocações e operações atuais — sem upload.</p>{current&&<small>Última verificação: {dateTime(current.created_at)}</small>}</div><button className="primary" type="button" disabled={currentLoading} onClick={()=>void verifyCurrent()}>{currentLoading?<LoaderCircle className="spin"/>:<RefreshCw/>}{currentLoading?'VERIFICANDO…':'VERIFICAR AGORA'}</button></section>
  {currentError&&<p className="davi-diagnostic-error"><XCircle/>{currentError}</p>}
  {current&&<div className="davi-current-results"><div className="davi-diagnostic-heading"><div><span>DIAGNÓSTICO ATUAL DO CRM</span><h3>Base analisada agora</h3><p>Vendas: {current.analyzed.sales.toLocaleString('pt-BR')} · Clientes: {current.analyzed.clients.toLocaleString('pt-BR')} · Perfumes: {current.analyzed.perfumes.toLocaleString('pt-BR')}</p></div>{current.consistency.changed_during_read?<AlertTriangle/>:<CheckCircle2/>}</div>
   {current.consistency.changed_during_read&&<p className="davi-snapshot-warning"><AlertTriangle/>A base mudou durante a leitura. Execute novamente antes de tomar decisões.</p>}
   <div className="davi-diagnostic-metrics davi-severity-metrics"><Metric tone={severityTone.CRITICAL} value={current.severity.CRITICAL} label="críticos"/><Metric tone={severityTone.WARNING} value={current.severity.WARNING} label="alertas"/><Metric tone={severityTone.REVIEW} value={current.severity.REVIEW} label="revisões"/><Metric tone={severityTone.INFO} value={current.severity.INFO} label="informativos"/></div>
   <div className="davi-current-summary"><div><b>DUPLICIDADES</b><span>{current.summary.possible_duplicates} possíveis</span></div><div><b>PERFUMES</b><span>{current.summary.possible_aliases} possíveis aliases</span><span>{current.summary.perfume_conflicts} conflitos</span></div><div><b>ESTOQUE</b><span>{current.summary.sales_without_item} vendas sem item</span><span>{current.summary.paid_without_allocation} pagas sem alocação</span><span>{current.summary.incompatible_allocations} alocações incompatíveis</span><span>{current.summary.perfumes_with_projected_deficit} perfumes com déficit</span></div><div><b>REFERÊNCIAS</b><span>{current.summary.reference_inconsistencies} inconsistências</span></div><div><b>COMERCIAL</b><span>{current.summary.value_conflicts} conflitos de valor</span><span>{current.summary.commercial_incompatibilities} dados incompatíveis</span></div></div>
   <div className="davi-diagnostic-groups"><details><summary><AlertTriangle/>Duplicidades <b>{currentGroups.duplicates.length}</b><ChevronRight/></summary><FindingList findings={currentGroups.duplicates}/></details><details><summary><Info/>Perfumes e aliases <b>{currentGroups.perfumes.length}</b><ChevronRight/></summary><FindingList findings={currentGroups.perfumes}/></details><details><summary><AlertTriangle/>Estoque e alocações <b>{currentGroups.inventory.length}</b><ChevronRight/></summary><FindingList findings={currentGroups.inventory}/></details><details><summary><XCircle/>Referências <b>{currentGroups.references.length}</b><ChevronRight/></summary><FindingList findings={currentGroups.references}/></details><details><summary><AlertTriangle/>Dados comerciais e valores <b>{currentGroups.commercial.length}</b><ChevronRight/></summary><FindingList findings={currentGroups.commercial}/></details>
    <details><summary><ChevronRight/>Simulação agregada por perfume <b>{current.inventory_by_perfume.filter(item=>item.unallocated_demand_ml>0||item.deficit_ml>0).length}</b><ChevronRight/></summary><div className="davi-diagnostic-inventory">{current.inventory_by_perfume.filter(item=>item.unallocated_demand_ml>0||item.deficit_ml>0).map(item=><article key={item.inventory_item_id}><strong>{item.perfume}</strong><span>Disponível: {item.available_ml} ml</span><span>Reservado: {item.reserved_ml} ml</span><span>Demanda não alocada: {item.unallocated_demand_ml} ml</span><b>Saldo projetado: {item.projected_balance_ml} ml</b><span>Déficit: {item.deficit_ml} ml</span></article>)}</div></details>
   </div><p className="davi-readonly-note"><ShieldCheck/>Esse relatório não altera nada. Os códigos estruturados poderão alimentar ações de correção futuras.</p>
  </div>}
  <details className="davi-new-file-analysis"><summary><FileSpreadsheet/>ANALISAR NOVA PLANILHA<ChevronRight/></summary><p>Use esta opção somente quando houver uma nova versão da planilha operacional do Davi.</p><div className="davi-diagnostic-upload"><input ref={input} type="file" accept=".csv,.xlsx" onChange={event=>{setFile(event.target.files?.[0]??null);setReport(null);setError('')}}/><button type="button" onClick={()=>input.current?.click()}><Upload/> {file?'TROCAR ARQUIVO':'SELECIONAR PLANILHA'}</button><span>{file?.name??'Nenhum arquivo selecionado'}</span><button className="primary" type="button" disabled={!file||loading} onClick={()=>void analyze()}>{loading?<LoaderCircle className="spin"/>:<ShieldCheck/>}{loading?'ANALISANDO…':'ANALISAR PLANILHA'}</button></div>
  {error&&<p className="davi-diagnostic-error"><XCircle/>{error}</p>}
  {report&&<div className="davi-diagnostic-results">
   <div className="davi-diagnostic-heading"><div><span>ANÁLISE CONCLUÍDA</span><h3>{report.total_lines.toLocaleString('pt-BR')} linhas analisadas</h3><p>{safe.length?`${safe.length} alteração(ões) segura(s) aguardando confirmação.`:`Esta planilha não tem nenhuma alteração segura nova para aplicar. Existem ${report.stock.excluded_for_manual_review} itens para revisão.`}</p></div><CheckCircle2/></div>
   <div className="davi-diagnostic-metrics"><Metric tone="ok" value={report.identity.updates} label="vendas já conciliadas"/><Metric tone="new" value={report.identity.new_sales} label="vendas novas"/><Metric tone="ok" value={report.identity.updates_with_changes} label="atualizações seguras"/><Metric tone="warn" value={report.identity.probable_duplicates} label="possíveis duplicidades"/><Metric tone="warn" value={report.identity.conflicts} label="conflitos"/><Metric tone="bad" value={report.identity.invalid} label="linhas inválidas"/></div>
   <div className="davi-diagnostic-stock"><h4>ESTOQUE</h4>{report.stock.stock_ok.sales===0&&report.stock.stock_insufficient.sales===0&&report.stock.stock_item_missing.sales===0?<p><CheckCircle2/> Nenhuma nova demanda de estoque neste arquivo.</p>:<div className="davi-diagnostic-metrics"><Metric tone="ok" value={report.stock.stock_ok.sales} label={`${report.stock.stock_ok.ml} ml com estoque`}/><Metric tone="warn" value={report.stock.stock_insufficient.sales} label={`${report.stock.stock_insufficient.ml} ml insuficientes`}/><Metric tone="bad" value={report.stock.stock_item_missing.sales} label={`${report.stock.stock_item_missing.ml} ml sem item físico`}/></div>}
    {report.inventory_by_perfume.length>0&&<details><summary><ChevronRight/>Ver simulação por perfume</summary><div className="davi-diagnostic-inventory">{report.inventory_by_perfume.map(item=><article key={item.inventory_item_id}><strong>{item.perfume}</strong><span>Disponível: {item.available_ml} ml</span><span>Já reservado: {item.already_reserved_ml} ml</span><span>Nova demanda: {item.new_demand_ml} ml</span><b>Saldo projetado: {item.projected_balance_ml} ml</b></article>)}</div></details>}
   </div>
   <div className="davi-diagnostic-groups">
    <details><summary><AlertTriangle/>Possíveis duplicidades <b>{groups.duplicates.length}</b><ChevronRight/></summary><ReviewRows rows={groups.duplicates} kind="duplicate"/></details>
    <details><summary><AlertTriangle/>Conflitos de perfume <b>{groups.perfume.length}</b><ChevronRight/></summary><p className="davi-alias-note">Uma equivalência só poderá virar alias após aprovação administrativa. Similaridade textual nunca cria alias automaticamente.</p><ReviewRows rows={groups.perfume} kind="perfume"/></details>
    <details><summary><AlertTriangle/>Conflitos de valor <b>{groups.value.length}</b><ChevronRight/></summary><ReviewRows rows={groups.value} kind="value"/></details>
    {groups.otherConflicts.length>0&&<details><summary><AlertTriangle/>Outros conflitos <b>{groups.otherConflicts.length}</b><ChevronRight/></summary><ReviewRows rows={groups.otherConflicts} kind="duplicate"/></details>}
    <details><summary><XCircle/>Linhas inválidas <b>{groups.invalid.length}</b><ChevronRight/></summary><ReviewRows rows={groups.invalid} kind="invalid"/></details>
   </div>
   <footer className="davi-diagnostic-actions"><div><strong>{safe.length} item(ns) seguro(s)</strong><span>Duplicidades, conflitos, inválidas e falhas de estoque nunca entram no apply.</span></div><button type="button" disabled title={safe.length?'A integração final com o apply aguarda validação desta tela.':'Nenhuma alteração segura para aplicar.'}>APLICAR ALTERAÇÕES SEGURAS</button></footer>
  </div>}</details>
 </section>
}
