import {AlertTriangle,Check,ChevronRight,Copy,ExternalLink,Printer} from 'lucide-react'
import type {OperationalShipment} from '../lib/records'
import {brl,shortDate} from '../lib/format'
import {operationalLabel} from '../lib/presentation'

type Item=OperationalShipment['shipment_items'][number]
type Props={shipment:OperationalShipment;items:Item[];onEdit:()=>void;onChange:(item:Item,kind:'separated'|'checked',value:boolean)=>void;onDivergence:(item:Item,value:string)=>void}

export function RuahBrand({print=false}:{print?:boolean}){return <img className={`ruah-brand ${print?'ruah-brand-print':''}`} src="/ruah-brand.svg" alt="RUAH Parfums"/>}

const humanStatus=(s:OperationalShipment)=>s.status==='delivered'?'Entregue':s.status==='posted'?'Objeto postado':s.print_available?'Etiqueta pronta para imprimir':s.superfrete_order_id?(s.superfrete_status==='pending'?'Etiqueta sendo preparada':'Etiqueta aguardando liberação'):s.checkout_status==='cart_created'?'Etiqueta aguardando pagamento':s.status==='customer_approved'?'Cliente aprovou o frete':s.status==='awaiting_customer_approval'?'Aguardando aprovação do cliente':s.selected_quote_id?'Frete calculado':s.shipment_items.every(i=>i.checked_at&&!i.divergence_note)?'Pronto para calcular frete':s.shipment_items.some(i=>i.separated_at)?'Aguardando conferência':'Preparando produtos'
const progressIndex=(s:OperationalShipment)=>s.status==='delivered'?7:s.status==='posted'?6:s.print_available?5:s.superfrete_order_id?5:s.status==='customer_approved'?4:s.status==='awaiting_customer_approval'?3:s.selected_quote_id?3:s.shipment_items.every(i=>i.checked_at&&!i.divergence_note)?2:s.shipment_items.some(i=>i.separated_at)?1:0
const stages=['Produtos','Separação','Conferência','Frete','Aprovação','Etiqueta','Postagem','Entrega']
const weight=(kg:number|null)=>kg==null?'—':`${Math.round(Number(kg)*1000).toLocaleString('pt-BR')} g`

export function ShipmentStatus({shipment}:{shipment:OperationalShipment}){return <div className="shipment-status" role="status"><i/><div><span>Status atual</span><strong>{humanStatus(shipment)}</strong></div></div>}

export function ShipmentJourney({shipment}:{shipment:OperationalShipment}){const active=progressIndex(shipment);return <nav className="shipment-journey" aria-label="Progresso do envio">{stages.map((stage,index)=><div key={stage} className={`${index<active?'done':''} ${index===active?'active':''}`}><b>{index<active?<Check/>:String(index+1).padStart(2,'0')}</b><span>{stage}</span></div>)}</nav>}

function SectionTitle({number,title,aside}:{number:string;title:string;aside?:string}){return <header className="shipment-section-title"><span>{number}</span><div><h2>{title}</h2>{aside&&<p>{aside}</p>}</div></header>}

export function ShipmentHeader({shipment,onEdit}:{shipment:OperationalShipment;onEdit:()=>void}){return <><header className="shipment-premium-head"><RuahBrand/><div className="shipment-title"><span>ENVIO 360</span><h1>{shipment.recipient_name}</h1><p>Envio #{shipment.id.slice(0,8).toUpperCase()} <i/> {shortDate(shipment.created_at)}</p></div><ShipmentStatus shipment={shipment}/></header><div className="next-action"><div><span>PRÓXIMO PASSO</span><strong>{humanStatus(shipment)}</strong><small>A operação atual está preservada. Continue pela ação indicada.</small></div><button className="primary" onClick={onEdit}>CONTINUAR OPERAÇÃO <ChevronRight/></button></div></>}

export function ShipmentChecklist({items,onChange,onDivergence}:{items:Item[];onChange:Props['onChange'];onDivergence:Props['onDivergence']}){const separated=items.filter(i=>i.separated_at).length,checked=items.filter(i=>i.checked_at).length,pending=items.length-checked,divergent=items.filter(i=>i.divergence_note);return <section className="shipment-editorial-section checklist-section"><SectionTitle number="01—02" title="Produtos · Separação e conferência" aside="Ordem alfabética para conferência física"/><div className="checklist-totals"><div><strong>{items.length}</strong><span>itens</span></div><div><strong>{separated}</strong><span>separados</span></div><div><strong>{checked}</strong><span>conferidos</span></div><div className={pending?'pending':''}><strong>{pending}</strong><span>pendentes</span></div></div>{divergent.length>0&&<div className="divergence-callout"><AlertTriangle/><div><strong>ATENÇÃO — CONFERÊNCIA NECESSÁRIA</strong>{divergent.map(i=><p key={i.allocation_id}>{i.sales?.perfume_name_raw||'Produto'}: {i.divergence_note}. Resolva antes de emitir a etiqueta.</p>)}</div></div>}<div className="premium-checklist" role="table" aria-label="Produtos para conferência em ordem alfabética">{items.map((item,index)=><article key={item.allocation_id} role="row"><span className="item-number">{String(index+1).padStart(2,'0')}</span><div className="item-name"><strong>{item.sales?.perfume_name_raw||'Produto'}</strong><span>{item.quantity_ml} ML · {item.sales?.sale_type||'Tipo não informado'}</span></div><button className={`check-action ${item.separated_at?'complete':''}`} aria-pressed={Boolean(item.separated_at)} onClick={()=>onChange(item,'separated',!item.separated_at)}>{item.separated_at&&<Check/>}{item.separated_at?'SEPARADO':'MARCAR SEPARADO'}</button><button className={`check-action ${item.checked_at?'complete':''}`} aria-pressed={Boolean(item.checked_at)} onClick={()=>onChange(item,'checked',!item.checked_at)}>{item.checked_at&&<Check/>}{item.checked_at?'CONFERIDO':'MARCAR CONFERIDO'}</button><label className="divergence-select"><span>Divergência</span><select aria-label={`Divergência de ${item.sales?.perfume_name_raw||'produto'}`} value={item.divergence_note||''} onChange={e=>onDivergence(item,e.target.value)}><option value="">Sem divergência</option>{['Item faltando','Item extra','Perfume diferente','ML diferente','Quantidade diferente','Outro'].map(v=><option key={v}>{v}</option>)}</select></label></article>)}</div></section>}

export function ShipmentFacts({shipment,onEdit}:{shipment:OperationalShipment;onEdit:()=>void}){return <div className="shipment-facts"><section className="shipment-editorial-section"><SectionTitle number="03" title="Dados do destinatário"/><dl><dt>Nome</dt><dd>{shipment.recipient_name}</dd><dt>Telefone</dt><dd>{shipment.recipient_phone||'Não informado'}</dd><dt>Documento</dt><dd>{shipment.recipient_document||'Não informado'}</dd><dt>CEP</dt><dd>{shipment.recipient_postal_code||'Não informado'}</dd><dt>Endereço</dt><dd>{[shipment.recipient_address,shipment.recipient_number,shipment.recipient_complement].filter(Boolean).join(', ')||'Não informado'}</dd><dt>Cidade / UF</dt><dd>{[shipment.recipient_city,shipment.recipient_state].filter(Boolean).join(' / ')||'Não informado'}</dd></dl></section><section className="shipment-editorial-section package-section"><SectionTitle number="04" title="Pacote e frete"/><div className="package-measure"><div><span>Peso</span><strong>{weight(shipment.package_weight)}</strong></div><div><span>Dimensões</span><strong>{shipment.package_length??'—'} × {shipment.package_width??'—'} × {shipment.package_height??'—'} cm</strong></div></div><div className="freight-summary"><span>FRETE</span>{shipment.service?<><h3>{shipment.carrier} · {shipment.service}</h3><strong>{shipment.shipping_price==null?'Valor não informado':brl(Number(shipment.shipping_price))}</strong><p><Check/> Frete escolhido</p></>:<><h3>Opções ainda não calculadas</h3><p>Calcule os serviços disponíveis para este endereço.</p><button onClick={onEdit}>CALCULAR FRETE</button></>}</div></section></div>}

export function ShipmentLabelCenter({shipment,onEdit}:{shipment:OperationalShipment;onEdit:()=>void}){const url=shipment.print_url||shipment.label_pdf_url;const processing=Boolean(shipment.superfrete_order_id)&&!shipment.print_available;return <section className="shipment-editorial-section label-center"><SectionTitle number="05—06" title="Aprovação e etiqueta"/><div className="label-stage"><span>{shipment.print_available?'ETIQUETA PRONTA':processing?'ETIQUETA SENDO PREPARADA':shipment.status==='awaiting_customer_approval'?'AGUARDANDO APROVAÇÃO DO CLIENTE':shipment.status==='customer_approved'?'CLIENTE APROVOU O FRETE':'CENTRAL DE ETIQUETA'}</span><h3>{shipment.print_available?'Arquivo oficial liberado para impressão':processing?'A SuperFrete está processando o arquivo.':'Continue a operação para preparar a etiqueta.'}</h3>{shipment.tracking_code&&<p>Rastreio <strong>{shipment.tracking_code}</strong></p>}{shipment.integration_error&&<div className="label-error"><AlertTriangle/><span>Não foi possível atualizar sua etiqueta agora. A etiqueta existente continua preservada.</span></div>}<div className="label-actions">{shipment.print_available&&url?<a className="primary" href={url} target="_blank" rel="noreferrer">IMPRIMIR ETIQUETA <ExternalLink/></a>:<button className="primary" onClick={onEdit}>{processing?'ATUALIZAR STATUS':'CONTINUAR OPERAÇÃO'}</button>}{shipment.tracking_code&&<button onClick={()=>navigator.clipboard.writeText(shipment.tracking_code!)}><Copy/> COPIAR RASTREIO</button>}<button onClick={()=>window.print()}><Printer/> IMPRIMIR FOLHA DO ENVIO</button></div></div></section>}

export function ShipmentTimeline({shipment}:{shipment:OperationalShipment}){return <section className="shipment-editorial-section timeline-section"><SectionTitle number="07" title="Histórico do envio"/>{shipment.shipment_events?.map(e=><div key={e.id}><span>{shortDate(e.created_at)}</span><strong>{operationalLabel(e.event_type)}</strong><small>{operationalLabel(e.from_status||'Início')} → {operationalLabel(e.to_status||'Atual')}</small></div>)}{!shipment.shipment_events?.length&&<p>Nenhum evento registrado.</p>}</section>}

export function ShipmentPrintView({shipment,items}:{shipment:OperationalShipment;items:Item[]}){const now=new Intl.DateTimeFormat('pt-BR',{dateStyle:'short',timeStyle:'short'}).format(new Date());return <section className="shipment-print-view"><RuahBrand print/><header><span>FOLHA DO ENVIO</span><h1>#{shipment.id.slice(0,8).toUpperCase()}</h1><h2>{shipment.recipient_name}</h2><p>{shortDate(shipment.created_at)}</p></header><div className="print-summary"><h3>SEPARAÇÃO E CONFERÊNCIA</h3><dl><dt>Itens esperados</dt><dd>{items.length}</dd><dt>Separados</dt><dd>{items.filter(i=>i.separated_at).length}</dd><dt>Conferidos</dt><dd>{items.filter(i=>i.checked_at).length}</dd><dt>Divergências</dt><dd>{items.filter(i=>i.divergence_note).length}</dd></dl></div><table><thead><tr><th>Nº</th><th>Perfume</th><th>ML</th><th>Tipo</th><th>Separado</th><th>Conferido</th></tr></thead><tbody>{items.map((i,n)=><tr key={i.allocation_id}><td>{String(n+1).padStart(2,'0')}</td><td>{i.sales?.perfume_name_raw||'Produto'}</td><td>{i.quantity_ml}</td><td>{i.sales?.sale_type||'—'}</td><td>{i.separated_at?'✓':'○'}</td><td>{i.checked_at?'✓':'○'}</td></tr>)}</tbody></table><div className="print-signatures"><span>Separado por:</span><span>Conferido por:</span></div><footer>RUAH Intelligence · Operação logística <small>Impresso em {now}</small></footer></section>}

export function Shipment360View(props:Props){return <><div className="shipment-screen"><ShipmentHeader shipment={props.shipment} onEdit={props.onEdit}/><ShipmentJourney shipment={props.shipment}/><ShipmentChecklist items={props.items} onChange={props.onChange} onDivergence={props.onDivergence}/><ShipmentFacts shipment={props.shipment} onEdit={props.onEdit}/><ShipmentLabelCenter shipment={props.shipment} onEdit={props.onEdit}/><ShipmentTimeline shipment={props.shipment}/></div><ShipmentPrintView shipment={props.shipment} items={props.items}/></>}
