import {useEffect,useMemo,useState} from 'react'
import {AlertTriangle,Check,Copy,ExternalLink,PackageCheck,RefreshCw,Truck,X} from 'lucide-react'
import {brl,shortDate} from '../lib/format'
import {approveShipmentForLabel,createSuperFreteLabel,fetchOperationalShipments,fetchShippingSettings,OperationalShipment,quoteShipment,refreshShipmentRecipient,saveShippingSettings,selectShipmentQuote,ShippingSettings,syncSuperFreteShipment,updateShipmentShippingData} from '../lib/records'
import {canBuyLabel,canQuoteShipment,missingLabelFields,missingQuoteFields,shipmentStatusLabels} from '../lib/superfrete'

const emptySettings:Partial<ShippingSettings>={default_format:'box',calculator_services:'1,2,17,3,31'}
const shipmentKeys=['recipient_name','recipient_phone','recipient_document','recipient_email','recipient_postal_code','recipient_address','recipient_number','recipient_complement','recipient_district','recipient_city','recipient_state','package_weight','package_height','package_width','package_length','declared_value'] as const

export function OperationalShipments(){
  const [rows,setRows]=useState<OperationalShipment[]>([]),[selected,setSelected]=useState<OperationalShipment|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState('')
  const reload=()=>fetchOperationalShipments().then(data=>{setRows(data);setError('')}).catch(reason=>setError(reason instanceof Error?reason.message:'Não foi possível carregar os envios.')).finally(()=>setLoading(false))
  useEffect(()=>{reload()},[])
  const counts=useMemo(()=>rows.reduce((acc,row)=>{acc[row.status]=(acc[row.status]||0)+1;return acc},{} as Record<string,number>),[rows])
  return <section className="shipment-operations">
    {selected&&<ShipmentEditor shipment={selected} close={()=>setSelected(null)} saved={()=>{setSelected(null);reload()}}/>}
    <div className="shipment-summary card"><div><Truck/><span>Em preparação<strong>{(counts.draft||0)+(counts.requested||0)}</strong></span></div><div><PackageCheck/><span>Aguardando cliente<strong>{counts.awaiting_customer_approval||0}</strong></span></div><div><Check/><span>Prontos/postados<strong>{(counts.label_released||0)+(counts.posted||0)}</strong></span></div></div>
    <div className="card clients-table"><div className="clients-caption"><div><strong>Shipments operacionais</strong><span>Uma etiqueta pode reunir várias compras do mesmo cliente.</span></div><span className="live-dot">SUPERFRETE</span></div>
      {error?<div className="notice"><AlertTriangle/><span>{error}</span></div>:loading?<div className="inline-empty">Carregando envios…</div>:<div className="table-wrap"><table><thead><tr><th>Cliente</th><th>Produtos</th><th>Status</th><th>Serviço</th><th>Frete</th><th>Rastreio</th><th>Criado</th><th>Ação</th></tr></thead><tbody>{rows.map(row=><tr key={row.id}><td><strong>{row.clients?.name||row.recipient_name}</strong></td><td>{row.shipment_items.length} · {row.shipment_items.reduce((sum,item)=>sum+Number(item.quantity_ml),0)} ml</td><td><span className={`badge ${['posted','delivered'].includes(row.status)?'paid':'pending'}`}>{shipmentStatusLabels[row.status]||row.status}</span></td><td>{row.service||'Não selecionado'}</td><td>{row.shipping_price==null?'—':brl(Number(row.shipping_price))}</td><td>{row.tracking_code||'—'}</td><td>{shortDate(row.created_at)}</td><td><button onClick={()=>setSelected(row)}>Abrir envio</button></td></tr>)}</tbody></table>{!rows.length&&<div className="inline-empty">Nenhum Shipment criado. No Cliente 360°, selecione produtos reservados e use “Preparar envio”.</div>}</div>}
    </div>
  </section>
}

function ShipmentEditor({shipment,close,saved}:{shipment:OperationalShipment;close:()=>void;saved:()=>void}){
  const [form,setForm]=useState<Record<string,string>>(()=>Object.fromEntries(shipmentKeys.map(key=>[key,String((shipment as unknown as Record<string,unknown>)[key]??'')])))
  const [busy,setBusy]=useState(''),[error,setError]=useState('')
  const live={...shipment,...form},quoteMissing=missingQuoteFields(live),labelMissing=missingLabelFields(live)
  const act=async(label:string,fn:()=>Promise<unknown>,confirmation?:string)=>{if(confirmation&&!confirm(confirmation))return;setBusy(label);setError('');try{await fn();saved()}catch(reason){setError(reason instanceof Error?reason.message:'Não foi possível concluir a ação.')}finally{setBusy('')}}
  const payload=()=>({...form,package_format:'box',fiscal_mode:'declaration'})
  const save=()=>act('save',()=>updateShipmentShippingData(shipment.id,payload()))
  const calculate=()=>act('quote',async()=>{await updateShipmentShippingData(shipment.id,payload());await quoteShipment(shipment.id)})
  const confirmation=`CONFIRMAR COMPRA REAL DA ETIQUETA\n\nCliente: ${shipment.recipient_name}\nCEP: ${shipment.recipient_postal_code}\nEndereço: ${shipment.recipient_address}, ${shipment.recipient_number}\nServiço: ${shipment.carrier||''} ${shipment.service||''}\nValor: ${brl(Number(shipment.shipping_price||0))}\nPeso: ${shipment.package_weight} kg\nDimensões: ${shipment.package_length} × ${shipment.package_width} × ${shipment.package_height} cm\n\nEsta ação utilizará saldo real da SuperFrete. Continuar?`
  return <div className="modal-layer"><button className="modal-scrim" aria-label="Fechar" onClick={close}/><div className="modal-panel shipment-panel"><div className="modal-title"><div><span>SHIPMENT · SUPERFRETE</span><h2>{shipment.recipient_name}</h2></div><button onClick={close}><X/></button></div><div className="record-form">
    <div className="shipment-state"><span className="badge pending">{shipmentStatusLabels[shipment.status]||shipment.status}</span>{shipment.integration_error&&<em>{shipment.integration_error}</em>}</div>
    <div className="shipment-products"><h3>Produtos neste envio</h3>{shipment.shipment_items.map(item=><div key={item.sales?.id||item.quantity_ml}><span>{item.sales?.perfume_name_raw||'Produto'}</span><strong>{item.quantity_ml} ml · {brl(Number(item.sales?.amount||0))}</strong></div>)}</div>
    {canQuoteShipment(shipment.status)&&<><div className="section-heading"><h3>Destinatário</h3><button onClick={()=>act('refresh',()=>refreshShipmentRecipient(shipment.id))}><RefreshCw/> Atualizar do Cliente 360°</button></div><div className="form-grid">{[['recipient_name','Nome'],['recipient_phone','Telefone'],['recipient_document','CPF/CNPJ'],['recipient_email','E-mail'],['recipient_postal_code','CEP'],['recipient_address','Endereço'],['recipient_number','Número'],['recipient_complement','Complemento'],['recipient_district','Bairro'],['recipient_city','Cidade'],['recipient_state','UF']].map(([key,label])=><label className={`field ${key==='recipient_address'?'wide':''}`} key={key}><span>{label}</span><input value={form[key]} onChange={event=>setForm({...form,[key]:event.target.value})}/></label>)}</div><h3>Pacote e valor</h3><div className="form-grid">{[['package_weight','Peso (kg)'],['package_height','Altura (cm)'],['package_width','Largura (cm)'],['package_length','Comprimento (cm)'],['declared_value','Valor declarado']].map(([key,label])=><label className="field" key={key}><span>{label}</span><input inputMode="decimal" value={form[key]} onChange={event=>setForm({...form,[key]:event.target.value})}/></label>)}</div>{quoteMissing.length>0&&<div className="incomplete-data"><AlertTriangle/><div><strong>DADOS PARA COTAÇÃO INCOMPLETOS</strong><span>{quoteMissing.join(', ')}</span></div></div>}<div className="form-actions"><button disabled={!!busy} onClick={save}>Salvar dados</button><button className="primary" disabled={!!busy||quoteMissing.length>0} onClick={calculate}>CALCULAR FRETE</button></div></>}
    {shipment.shipment_quotes?.length>0&&canQuoteShipment(shipment.status)&&<div className="quote-grid">{shipment.shipment_quotes.map(quote=><button disabled={!quote.available||!!busy} key={quote.id} onClick={()=>act('select',()=>selectShipmentQuote(shipment.id,quote.id))}><strong>{quote.carrier} · {quote.service_name}</strong><span>{brl(Number(quote.price))}</span><small>{quote.delivery_days?`${quote.delivery_days} dias úteis`:(quote.safe_error||'Prazo não informado')}</small></button>)}</div>}
    {shipment.status==='awaiting_customer_approval'&&<div className="approval-box"><strong>AGUARDANDO APROVAÇÃO DO CLIENTE</strong><span>{shipment.carrier} · {shipment.service} · {brl(Number(shipment.shipping_price))}</span><button className="primary" disabled={!!busy} onClick={()=>act('approve',()=>approveShipmentForLabel(shipment.id),'Confirma que o cliente aprovou o serviço e o valor exibidos?')}>APROVADO PELO CLIENTE</button></div>}
    {shipment.status==='customer_approved'&&<>{labelMissing.length>0?<div className="incomplete-data"><AlertTriangle/><div><strong>DADOS DE ENVIO INCOMPLETOS</strong><span>{labelMissing.join(', ')}</span><a href={`/clientes/${shipment.client_id}`}>Completar dados do cliente <ExternalLink/></a></div></div>:<button className="primary buy-label" disabled={!!busy||!canBuyLabel(shipment.status,labelMissing)} onClick={()=>act('label',()=>createSuperFreteLabel(shipment.id),confirmation)}>APROVADO PELO CLIENTE — EMITIR ETIQUETA</button>}</>}
    {shipment.superfrete_order_id&&<div className="shipment-actions"><button disabled={!!busy} onClick={()=>act('sync',()=>syncSuperFreteShipment(shipment.id))}><RefreshCw/> Sincronizar status</button>{(shipment.print_url||shipment.label_pdf_url)&&<a href={shipment.print_url||shipment.label_pdf_url||'#'} target="_blank" rel="noreferrer">Imprimir etiqueta <ExternalLink/></a>}{shipment.tracking_code&&<button onClick={()=>navigator.clipboard.writeText(shipment.tracking_code!)}><Copy/> Copiar rastreio</button>}</div>}
    {['cart_uncertain','checkout_uncertain'].includes(String(shipment.checkout_status))&&<div className="incomplete-data"><AlertTriangle/><div><strong>RECONCILIAÇÃO NECESSÁRIA</strong><span>A operação não será repetida. Use “Sincronizar status” para consultar o pedido existente.</span></div></div>}
    {error&&<div className="form-error">{error}</div>}</div></div></div>
}

export function ShippingSettingsPage(){
  const [form,setForm]=useState<Partial<ShippingSettings>>(emptySettings),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[message,setMessage]=useState('')
  const [configured,setConfigured]=useState(false)
  useEffect(()=>{fetchShippingSettings().then(data=>{setConfigured(Boolean(data));setForm(data||emptySettings)}).catch(()=>setMessage('Não foi possível carregar a configuração.')).finally(()=>setLoading(false))},[])
  const set=(key:keyof ShippingSettings,value:string)=>setForm(current=>({...current,[key]:value}))
  const required:[keyof ShippingSettings,string][]=[['sender_name','Nome / razão social'],['sender_document','CPF/CNPJ'],['sender_email','E-mail'],['sender_phone','Telefone'],['sender_postal_code','CEP'],['sender_address','Endereço'],['sender_number','Número'],['sender_district','Bairro'],['sender_city','Cidade'],['sender_state','UF'],['default_weight','Peso padrão'],['default_height','Altura padrão'],['default_width','Largura padrão'],['default_length','Comprimento padrão']]
  const missing=required.filter(([key])=>!String(form[key]??'').trim()).map(([,label])=>label)
  const submit=async()=>{if(missing.length){setMessage(`Preencha os campos obrigatórios: ${missing.join(', ')}.`);return}setSaving(true);setMessage('');try{await saveShippingSettings(form);setConfigured(true);setMessage('Configuração salva e persistida. O token continua somente nos Secrets do Supabase.')}catch(reason){setMessage(reason instanceof Error?reason.message:'Falha ao salvar.')}finally{setSaving(false)}}
  return <div className="page"><div className="page-lead"><div><h2>Configurações</h2><p>Remetente e pacote padrão da operação logística.</p></div></div><div className="card settings-card"><div className="card-title"><div><h3>SuperFrete — Produção</h3><p>Nenhuma credencial é armazenada ou exibida no navegador.</p></div><span className="live-dot">{configured?'CONFIGURADO':'CONFIGURAÇÃO PENDENTE'}</span></div>{loading?<div className="inline-empty">Carregando…</div>:<div className="record-form">{!configured&&<div className="incomplete-data"><AlertTriangle/><div><strong>SUPERFRETE AINDA NÃO ESTÁ PRONTA PARA USO</strong><span>Preencha o remetente real e o pacote padrão. Sem isso, o cálculo de frete será bloqueado com segurança.</span></div></div>}<div className="form-grid">{[['sender_name','Nome do remetente'],['sender_document','CPF/CNPJ'],['sender_email','E-mail'],['sender_phone','Telefone'],['sender_postal_code','CEP'],['sender_address','Endereço'],['sender_number','Número'],['sender_complement','Complemento'],['sender_district','Bairro'],['sender_city','Cidade'],['sender_state','UF'],['default_weight','Peso padrão (kg)'],['default_height','Altura padrão (cm)'],['default_width','Largura padrão (cm)'],['default_length','Comprimento padrão (cm)'],['calculator_services','Serviços (IDs separados por vírgula)']].map(([key,label])=><label className={`field ${['sender_address','calculator_services'].includes(key)?'wide':''}`} key={key}><span>{label}{required.some(([requiredKey])=>requiredKey===key)&&' *'}</span><input value={String(form[key as keyof ShippingSettings]??'')} onChange={event=>set(key as keyof ShippingSettings,event.target.value)}/></label>)}</div>{missing.length>0&&<div className="incomplete-data"><AlertTriangle/><div><strong>CAMPOS OBRIGATÓRIOS AUSENTES</strong><span>{missing.join(', ')}</span></div></div>}{message&&<div className="notice"><span>{message}</span></div>}<div className="form-actions"><button className="primary" disabled={saving} onClick={submit}>{saving?'Salvando…':'Salvar configuração'}</button></div></div>}</div></div>
}
